// Generated content bank. Edit the source lists, keep RU and EN aligned.
export const CHAOS_PROMPTS: { readonly ru: readonly string[]; readonly en: readonly string[] } = {
  ru: [
    "Худший способ познакомиться: ___",
    "На следующую тусу я принесу ___",
    "Мой секретный талант: ___",
    "Нас спасло только ___",
    "Идеальный подарок бывшему: ___",
    "Главный тренд этого лета: ___",
    "Почему я опоздал? Из-за ___",
    "Бабушка узнала про ___",
    "В моём резюме в графе «навыки» написано: ___",
    "Лучший способ пережить понедельник: ___",
    "На свадьбе всех удивил(а) ___",
    "Моя новая мотивация по утрам: ___",
    "Главный секрет долгой дружбы: ___",
    "В чате родителей обсуждают ___",
    "Мой психолог говорит, что всё из-за ___",
    "Новый вкус чипсов: ___",
    "Самое странное в моём холодильнике: ___",
    "Идеальное первое свидание: ___",
    "Меня выгнали из караоке за ___",
    "Олимпийский вид спорта будущего: ___",
    "В Алматы теперь можно увидеть ___",
    "Что сломало интернет сегодня? ___",
    "Мой начальник не знает о ___",
    "Я плачу каждый раз, когда вижу ___",
    "Новая суперсила: ___",
    "Главный герой моей жизни: ___",
    "На корпоративе всех запомнило ___",
    "Лучший тост звучит так: «Выпьем за ___»",
    "Мой кот считает, что я ___",
    "В новом сезоне сериала появится ___",
    "Ученые наконец объяснили ___",
    "Идеальное название для моей автобиографии: ___",
    "Если бы у меня был миллион, я бы купил ___",
    "Главная причина пробок: ___",
    "Секретный ингредиент плова: ___",
    "Что спрятано в сумке у мамы? ___",
    "Новый праздник для всей страны: ___",
    "Мой сосед снова ___",
    "Все мои проблемы решит ___",
    "Последний звонок был из-за ___",
    "Лучшее оправдание для диеты: ___",
    "Эту тусу запомнят благодаря ___",
    "Меня бросили из-за ___",
    "Новая звезда TikTok: ___",
    "Худший сосед по купе: ___",
    "Мой стиль одежды можно описать как ___",
    "Идеальный подарок на 8 марта: ___",
    "Худшая начинка для пирожка: ___",
    "Космонавты взяли с собой ___",
    "Мой план на выходные: ___",
    "Причина, почему я не сплю ночью: ___",
    "Всё изменилось, когда в мою жизнь пришёл ___",
    "Я стал знаменитым благодаря ___",
    "Главный хит лета называется ___",
    "На необитаемом острове мне нужен только ___",
    "Совет от бабушки: никогда не доверяй ___",
    "Моя тайная страсть: ___",
    "Новый аттракцион на Кок-Тобе: ___",
    "Меня не пустили в самолёт из-за ___",
    "Главный вопрос на собеседовании: ___",
    "Этот день был бы лучше без ___",
    "На выпускном я запомнил ___",
    "Инопланетяне прилетели ради ___",
    "Лучшая часть любой свадьбы: ___",
    "Меня уволили из-за ___",
    "Новое правило в общем чате: запрещено ___",
    "Что делает этот вечер особенным? ___",
    "Мой дед снова рассказывает про ___",
    "Самая дорогая вещь в моём доме: ___",
    "Лучшее лекарство от скуки: ___",
    "Новый герой Marvel: ___",
    "Это не баг, это ___",
    "На дастархане не хватало ___",
    "Сегодня я наконец-то понял ___",
    "Пятница начинается с ___",
    "Лучший способ понравиться тёще: ___",
    "Меня разбудил ___",
    "Если что-то пошло не так, вини ___",
    "Мечта детства: ___",
    "Главное правило этой компании: ___",
  ],
  en: [
    "The worst way to meet someone is ___",
    "At the next party I'll bring ___",
    "My secret talent is ___",
    "The only thing that saved us was ___",
    "The perfect gift for an ex is ___",
    "This summer's biggest trend is ___",
    "Why was I late? Because of ___",
    "Grandma found out about ___",
    "The skills section of my CV says ___",
    "The best way to survive Monday is ___",
    "Everyone at the wedding was shocked by ___",
    "My new morning motivation is ___",
    "The secret to a long friendship is ___",
    "The parents' group chat is discussing ___",
    "My therapist says it's all because of ___",
    "The new chip flavor is ___",
    "The strangest thing in my fridge is ___",
    "The perfect first date is ___",
    "I got kicked out of karaoke for ___",
    "The Olympic sport of the future is ___",
    "Now you can see ___ in Almaty",
    "What broke the internet today? ___",
    "My boss doesn't know about ___",
    "I cry every time I see ___",
    "A new superpower: ___",
    "The main character of my life is ___",
    "Everyone remembers the office party because of ___",
    "The best toast is: \"Let's drink to ___\"",
    "My cat thinks I am ___",
    "The new season will feature ___",
    "Scientists have finally explained ___",
    "The perfect title for my autobiography is ___",
    "With a million, I would buy ___",
    "The main cause of traffic jams is ___",
    "The secret pilaf ingredient is ___",
    "What's hiding in mom's bag? ___",
    "A new national holiday: ___",
    "My neighbor is doing ___ again",
    "All my problems will be solved by ___",
    "The last phone call was about ___",
    "The best excuse to skip the diet is ___",
    "This party will be remembered for ___",
    "I got dumped because of ___",
    "The new TikTok star is ___",
    "The worst train compartment neighbor is ___",
    "My fashion style is ___",
    "The perfect gift for Women's Day is ___",
    "The worst pie filling is ___",
    "The astronauts took ___ with them",
    "My weekend plan is ___",
    "The reason I can't sleep at night is ___",
    "Everything changed when ___ came into my life",
    "I became famous thanks to ___",
    "The summer hit is called ___",
    "On a desert island I only need ___",
    "Grandma's advice: never trust ___",
    "My secret passion is ___",
    "The new ride on Kok-Tobe is ___",
    "They didn't let me on the plane because of ___",
    "The main interview question is about ___",
    "This day would be better without ___",
    "What I remember from prom is ___",
    "The aliens came here for ___",
    "The best part of any wedding is ___",
    "I got fired because of ___",
    "New group chat rule: no more ___",
    "What makes tonight special? ___",
    "Grandpa is talking about ___ again",
    "The most expensive thing in my home is ___",
    "The best cure for boredom is ___",
    "The new Marvel hero is ___",
    "It's not a bug, it's ___",
    "The dastarkhan was missing ___",
    "Today I finally understood ___",
    "Friday begins with ___",
    "The best way to impress your mother-in-law is ___",
    "I was woken up by ___",
    "If something goes wrong, blame ___",
    "My childhood dream is ___",
    "The main rule of this group is ___",
  ],
};

export const CHAOS_CARDS: { readonly ru: readonly string[]; readonly en: readonly string[] } = {
  ru: [
    "танец с холодильником",
    "подозрительный плов",
    "голосовое на 12 минут",
    "мамин тапок",
    "караоке без музыки",
    "пакет с пакетами",
    "последний кусок пиццы",
    "легендарный сосед",
    "зарядка на один процент",
    "чай без кружки",
    "случайный лайк из 2017 года",
    "одинокий носок",
    "кот, который всё знает",
    "бабушкины пирожки",
    "бесконечный созвон",
    "кредит на айфон",
    "танцы до утра",
    "баурсаки в промышленных масштабах",
    "сосед с перфоратором",
    "утренний будильник",
    "третий кофе за час",
    "кнопка «ответить всем»",
    "неудачное селфи",
    "бывший в сторис",
    "групповой чат на 300 человек",
    "очередь в поликлинике",
    "папины шутки",
    "ремонт у соседей",
    "шашлык на балконе",
    "пробка на Аль-Фараби",
    "горы Алатау",
    "случайный тамада",
    "свадьба на 600 гостей",
    "спор о политике",
    "кот на клавиатуре",
    "пароль «123456»",
    "забытый день рождения",
    "прогулка под дождём",
    "пицца с ананасами",
    "неловкое молчание",
    "внезапный дедлайн",
    "отпуск мечты",
    "незакрытая вкладка",
    "танец маленьких утят",
    "шуба в июле",
    "голодный студент",
    "соседский вай-фай",
    "загадочный запах",
    "тётя, которая спрашивает про свадьбу",
    "мем из 2012 года",
    "бесплатная дегустация",
    "селфи с верблюдом",
    "песня, которая застряла в голове",
    "ночной жор",
    "новый тикток-тренд",
    "понедельник",
    "кредитная карта",
    "шоколадка на ночь",
    "подарок из фикс-прайса",
    "лучший друг из детства",
    "разбитый экран",
    "бесплатный сыр",
    "тайная вечеринка",
    "тётушкин салат оливье",
    "сапоги на каблуке",
    "дед на мотоцикле",
    "голуби в городе",
    "мой внутренний критик",
    "огромный чемодан",
    "навигатор, который ошибся",
    "незнакомец в лифте",
    "бутерброд маслом вниз",
    "спойлер финала",
    "полночный звонок",
    "неожиданный гость",
    "соседская собака",
    "сломанный зонт",
    "фотография паспорта",
    "кружка с надписью «лучший босс»",
    "хор из офисных коллег",
    "мокрые носки",
    "торт в форме лошади",
    "случайный комплимент",
    "запах шашлыка",
    "детский утренник",
    "последняя электричка",
    "мама на связи",
    "курьер в неправильном подъезде",
    "бесконечная реклама",
    "лишние калории",
    "диван, который зовёт",
    "холодный чай",
    "забытые пароли",
    "костюм динозавра",
    "пенсионер в спортзале",
    "тренажёр для пресса",
    "очень серьёзный хомяк",
    "танцующий охранник",
    "бабушка в TikTok",
    "неправильный автобус",
    "курс английского за три дня",
    "загадочный незнакомец",
    "ананас на голове",
    "сосед за стенкой",
    "торт без свечей",
    "семейный чат",
    "идеальная причёска",
    "лишний человек в такси",
    "шапка с помпоном",
    "кофе на вынос",
    "забытая сдача",
    "пятничный вечер",
    "неловкое объятие",
    "полный багажник арбузов",
    "мой первый телефон",
    "лимонад из детства",
    "огромный пёс",
    "маленький, но злой кот",
    "обиженный попугай",
    "песня Scorpions",
    "танец с шарфом",
    "дядя с баяном",
    "вечер настольных игр",
    "провал в Монополии",
    "спонтанный отпуск",
    "утро без кофе",
    "пельмени в три часа ночи",
    "заначка под матрасом",
    "лотерейный билет",
    "забытый зонтик",
    "пять будильников подряд",
    "тёплый плед",
    "бесконечный сериал",
    "приключение в IKEA",
    "кот в коробке",
    "соседские сплетни",
    "курс по саморазвитию",
    "сломанный лифт",
    "свадебный торт",
    "неудачный маникюр",
    "селфи-палка",
    "секретный рецепт",
    "лучшая подруга мамы",
    "кошачьи видео",
    "последний день отпуска",
    "неоплаченный штраф",
    "чужой зарядник",
    "танцпол",
    "слишком громкий смех",
    "кастрюля борща",
    "шампанское в полночь",
    "бенгальские огни",
    "новогодний оливье на 1 января",
    "дружеский совет",
    "бесплатный Wi-Fi",
    "опоздавший жених",
    "сбежавшая невеста",
    "лишний тост",
    "детский смех",
    "грустный клоун",
    "кот, который ненавидит понедельники",
    "кубок чемпиона",
    "заваленный экзамен",
    "шпаргалка в рукаве",
    "велосипед без тормозов",
    "случайная встреча с учителем",
    "ночной поход в магазин",
    "огромный арбуз",
    "мама, которая всё знала",
    "запах новой машины",
    "пустой холодильник",
    "поездка на Медеу",
    "вид с Кок-Тобе",
    "восьмой кусок торта",
    "видео с котиком в 4K",
    "лайфхак из интернета",
    "танец на столе",
    "последний билет на концерт",
    "случайный спойлер",
    "перегоревшая лампочка",
    "бесплатная доставка",
    "мой внутренний ребёнок",
    "утренняя пробежка",
    "кредит доверия",
    "огромные солнечные очки",
    "очень громкий будильник",
    "неправильный адрес",
    "голос из GPS",
    "тётя с тортом",
    "ночной кошмар",
    "дракон в подвале",
    "забытый пароль от Wi-Fi",
    "наушники, которые запутались",
    "перепутанные тапочки",
    "подарок, который передарили",
    "куча немытой посуды",
    "игра в прятки на работе",
    "романтический ужин из доставки",
    "кофемашина, которая сломалась",
    "бесплатные образцы",
    "новая причёска",
    "огромная очередь",
    "жвачка под партой",
    "кошачья шерсть на всём",
    "очень умный пылесос",
    "рыбалка без рыбы",
    "дача с комарами",
    "семейное фото 1998 года",
    "бабушкин ковёр на стене",
    "газировка без газа",
    "мороженое зимой",
    "торт, который упал",
    "танец на свадьбе дяди",
    "гадалка на рынке",
    "вечный студент",
    "огромный букет",
    "слишком честный друг",
    "любимая футболка с дыркой",
    "пакет с сюрпризом",
    "случайная влюблённость",
    "сосед, который поёт в душе",
    "дорогой кофе",
    "вечеринка в пижамах",
    "неожиданный отпуск",
    "три пропущенных от мамы",
    "курица из микроволновки",
    "кот, который уронил ёлку",
    "чек на 40 тысяч тенге",
    "таксист-философ",
    "кальян с дыней",
    "детский бассейн с шариками",
    "холодные пельмени",
    "голосовое от начальника в 23:59",
    "сломанный принтер",
    "дедушкины усы",
    "самокат на тротуаре",
    "очень злой гусь",
    "поддельные «Адидас»",
    "песня Димаша на повторе",
    "стоматолог с юмором",
    "лишний килограмм мандаринов",
    "игра в «Мафию» до пяти утра",
    "незнакомец на моей свадьбе",
    "тётя с камерой",
    "утюг, который я не выключил",
    "автомойка под дождём",
    "тайный поклонник",
    "кот в шапке",
    "соседи снизу",
    "мой бывший начальник",
    "стиральная машина на отжиме",
    "пятый кусок торта",
    "кумыс натощак",
    "курт в кармане",
    "горы грязной посуды",
    "голый король",
    "дракон на парковке",
    "купон на скидку 3%",
    "билет в один конец",
    "сломанная молния на джинсах",
    "шапка-ушанка",
    "чужой ребёнок в самолёте",
    "спящий охранник",
    "лекция о криптовалюте",
    "пробежка в 6 утра",
    "смузи из шпината",
    "неловкий тост на свадьбе",
    "вечный ремонт дороги",
    "мультиварка",
    "секретный чат выпускников",
    "пылесос-робот, который застрял",
    "разговор с автоответчиком",
    "соседская кошка на моём балконе",
    "первое свидание в столовой",
    "зонт в солнечный день",
    "пакет пакетов в пакете",
    "мама в «Одноклассниках»",
    "самый длинный тост дяди",
    "трёхчасовая очередь в ЦОН",
    "батарейка на 2%",
    "кот, который смотрит в стену",
    "второй завтрак",
    "носки с сандалиями",
    "карта лояльности на 200 магазинов",
    "сосед-диджей",
    "плед с рукавами",
    "кактус, который я залил",
    "лифт, который едет не туда",
    "песня из рекламы",
    "бабушкино варенье",
    "картошка в мундире",
    "пикник под дождём",
    "групповое фото с закрытыми глазами",
    "ёлка в марте",
    "костюм Деда Мороза",
    "весы, которые врут",
    "будильник на 4:30",
    "вечер без интернета",
    "сушёная рыба в офисе",
    "случайный звонок по видео",
    "кот, который открыл холодильник",
    "жвачка на подошве",
    "лягушка в кармане",
    "сюрприз-вечеринка, о которой я знал",
    "бесплатная пробная версия",
    "подписка, которую я забыл отменить",
    "ночная смена",
    "сосед с барабанами",
    "тренер по личностному росту",
    "очень дорогая вода",
    "пончик с сюрпризом",
    "тетрадь с секретами",
    "сломанный кондиционер в июле",
    "отопление в мае",
    "селфи в лифте",
    "песня «Кукушка» у костра",
    "гитара без двух струн",
    "забытый пакет в такси",
    "уставший официант",
    "кошачья шерсть на чёрном свитере",
    "новые кроссовки в луже",
    "дядя, который знает всё про футбол",
    "торт «Наполеон»",
    "фотка паспорта в 16 лет",
    "мой школьный дневник",
    "кружок по вязанию",
    "поход без палатки",
    "сухой паёк",
    "слон в посудной лавке",
    "тапочки-зайцы",
    "шарик, который улетел",
    "смешной акцент",
    "ведро попкорна",
    "фильм, который все хвалят",
    "последняя серия сезона",
    "тайная комната в IKEA",
    "случайный гость в Zoom",
    "выключенный микрофон",
    "включённая камера в пижаме",
    "пять минут до дедлайна",
    "приглашение на свадьбу бывшей",
    "огурцы бабушки",
    "пароль, записанный на стикере",
    "курсы игры на домбре",
    "тандыр во дворе",
    "дастархан на 30 человек",
    "лагман, который не кончается",
    "чак-чак на завтрак",
    "плохой перевод инструкции",
    "мебель без инструкции",
    "лишний болт",
    "сосед, который паркуется на двух местах",
    "тонированная «Приора»",
    "тюнингованная «Камри»",
    "соседский петух",
    "кот, который орёт в 5 утра",
    "холодильник с одной горчицей",
    "курс похудения за 7 дней",
    "гантели под кроватью",
    "абонемент в спортзал, который пылится",
    "чужие наушники",
    "песня, под которую все плачут",
    "караоке-баттл",
    "микрофон, который фонит",
    "уставший аниматор",
    "надувной батут",
    "вата на палочке",
    "колесо обозрения",
    "американские горки",
    "чемодан без колеса",
    "паспорт, забытый дома",
    "отменённый рейс",
    "ночь в аэропорту",
    "сувенир из Турции",
    "магнит на холодильник",
    "курортный роман",
    "загар в форме футболки",
    "солнечный ожог",
    "медуза на пляже",
    "водный пистолет",
    "надувной фламинго",
    "бабушка на лавочке",
    "соседский мальчик с мячом",
    "разбитое окно",
    "школьная дискотека",
    "выпускной альбом",
    "учительница химии",
    "взрыв на уроке химии",
    "двойка по поведению",
    "записка от родителей",
    "справка от врача",
    "сломанная нога на лыжах",
    "Шымбулак в выходные",
    "Медеу в воскресенье",
    "Кок-Тобе с туристами",
    "Большое Алматинское озеро",
    "Чарынский каньон",
    "верблюд, который плюнул",
    "лошадь с характером",
    "беркут на плече",
    "юрта в центре города",
    "наурыз-коже на весь двор",
    "шашлычник с золотыми зубами",
    "тойхана",
    "ведущий с баяном",
    "конкурс «кто громче»",
    "выкуп невесты",
    "подарок в конверте",
    "торт с фотографией",
    "фейерверк у соседей",
    "мигающая гирлянда",
    "новогодняя речь",
    "мандарины под ёлкой",
    "салют из хлопушки",
    "костюм снежинки",
    "утренник в детском саду",
    "носки на Новый год",
    "открытка с блёстками",
    "бесконечный семейный ужин",
    "вопрос «когда внуки?»",
    "кузен-блогер",
    "тётя-сетевик",
    "секретный ингредиент бабушки",
    "сгоревшая яичница",
    "дымящая сковородка",
    "пожарная сигнализация",
    "соседи, которые вызвали полицию",
    "бой подушками",
    "форт из одеял",
    "ночной марафон фильмов",
    "страшилка у костра",
    "шорох в темноте",
    "кот, который всё это время был в шкафу",
    "потерянные ключи",
    "запасной ключ под ковриком",
    "домофон, который не работает",
    "курьер, который звонит в 7 утра",
    "посылка из Китая за полгода",
    "товар, который не подошёл",
    "возврат на маркетплейсе",
    "отзыв на одну звезду",
    "кнопка «купить в один клик»",
    "чёрная пятница",
    "скидка 90% на всё ненужное",
    "кешбэк на кешбэк",
    "банковское приложение на обновлении",
    "перевод не тому человеку",
    "долг другу в 500 тенге",
    "общий счёт в ресторане",
    "чаевые монетками",
    "официант, который всё перепутал",
    "суп с мухой",
    "десерт за счёт заведения",
    "шеф-повар в плохом настроении",
    "ресторан, где все поют",
    "живая музыка слишком близко",
    "танцы на корпоративе",
    "начальник в караоке",
    "тимбилдинг в лесу",
    "верёвочный парк",
    "пейнтбол с бухгалтерией",
    "созвон, который мог быть письмом",
    "презентация на 80 слайдов",
    "Excel, который завис",
    "кнопка «сохранить», которую я не нажал",
    "стажёр, который всё починил",
    "пятничный релиз",
    "отпуск, который перенесли",
    "больничный в пятницу",
    "кофе из автомата",
    "печеньки в переговорке",
    "чужой обед в холодильнике",
  ],
  en: [
    "a fridge dance",
    "suspicious pilaf",
    "a 12-minute voice note",
    "mom's slipper",
    "karaoke without music",
    "a bag full of bags",
    "the last slice of pizza",
    "a legendary neighbor",
    "one percent battery",
    "tea without a mug",
    "a random like from 2017",
    "a lonely sock",
    "a cat that knows everything",
    "grandma's pies",
    "an endless video call",
    "a loan for an iPhone",
    "dancing until dawn",
    "industrial amounts of baursaks",
    "a neighbor with a drill",
    "the morning alarm",
    "the third coffee in an hour",
    "the reply-all button",
    "a bad selfie",
    "an ex in my stories",
    "a 300-person group chat",
    "the queue at the clinic",
    "dad jokes",
    "the neighbors' renovation",
    "barbecue on the balcony",
    "a traffic jam on Al-Farabi",
    "the Alatau mountains",
    "a random wedding host",
    "a 600-guest wedding",
    "a political argument",
    "a cat on the keyboard",
    "the password 123456",
    "a forgotten birthday",
    "a walk in the rain",
    "pineapple pizza",
    "awkward silence",
    "a sudden deadline",
    "a dream vacation",
    "an unclosed browser tab",
    "the chicken dance",
    "a fur coat in July",
    "a hungry student",
    "the neighbor's Wi-Fi",
    "a mysterious smell",
    "the aunt asking about my wedding",
    "a meme from 2012",
    "a free tasting",
    "a selfie with a camel",
    "a song stuck in my head",
    "midnight snacking",
    "a new TikTok trend",
    "Monday",
    "a credit card",
    "chocolate at midnight",
    "a dollar-store gift",
    "a childhood best friend",
    "a cracked screen",
    "free cheese",
    "a secret party",
    "auntie's Olivier salad",
    "high-heeled boots",
    "grandpa on a motorbike",
    "city pigeons",
    "my inner critic",
    "a giant suitcase",
    "a GPS that got it wrong",
    "a stranger in the elevator",
    "a sandwich butter side down",
    "a finale spoiler",
    "a midnight phone call",
    "an unexpected guest",
    "the neighbor's dog",
    "a broken umbrella",
    "a passport photo",
    "a \"world's best boss\" mug",
    "a choir of coworkers",
    "wet socks",
    "a horse-shaped cake",
    "a random compliment",
    "the smell of barbecue",
    "a kids' matinee",
    "the last train home",
    "mom on the line",
    "a courier at the wrong entrance",
    "endless ads",
    "extra calories",
    "a sofa calling my name",
    "cold tea",
    "forgotten passwords",
    "a dinosaur costume",
    "a retiree at the gym",
    "an ab machine",
    "a very serious hamster",
    "a dancing security guard",
    "grandma on TikTok",
    "the wrong bus",
    "a three-day English course",
    "a mysterious stranger",
    "a pineapple on my head",
    "the neighbor behind the wall",
    "a cake without candles",
    "the family chat",
    "perfect hair",
    "an extra person in the taxi",
    "a pom-pom hat",
    "coffee to go",
    "forgotten change",
    "Friday night",
    "an awkward hug",
    "a trunk full of watermelons",
    "my first phone",
    "childhood lemonade",
    "a huge dog",
    "a small but angry cat",
    "an offended parrot",
    "a Scorpions song",
    "a scarf dance",
    "an uncle with an accordion",
    "board game night",
    "a Monopoly disaster",
    "a spontaneous vacation",
    "a morning without coffee",
    "dumplings at 3 am",
    "cash hidden under the mattress",
    "a lottery ticket",
    "a forgotten umbrella",
    "five alarms in a row",
    "a warm blanket",
    "a never-ending TV series",
    "an IKEA adventure",
    "a cat in a box",
    "neighborhood gossip",
    "a self-help course",
    "a broken elevator",
    "a wedding cake",
    "a bad manicure",
    "a selfie stick",
    "a secret recipe",
    "mom's best friend",
    "cat videos",
    "the last day of vacation",
    "an unpaid fine",
    "someone else's charger",
    "the dance floor",
    "laughing too loud",
    "a pot of borscht",
    "champagne at midnight",
    "sparklers",
    "leftover Olivier on January 1st",
    "friendly advice",
    "free Wi-Fi",
    "a late groom",
    "a runaway bride",
    "one toast too many",
    "children's laughter",
    "a sad clown",
    "a cat that hates Mondays",
    "a champion's trophy",
    "a failed exam",
    "a cheat sheet up my sleeve",
    "a bike without brakes",
    "bumping into my old teacher",
    "a late-night shop run",
    "a giant watermelon",
    "mom who knew all along",
    "new car smell",
    "an empty fridge",
    "a trip to Medeu",
    "the view from Kok-Tobe",
    "the eighth slice of cake",
    "a 4K cat video",
    "an internet life hack",
    "dancing on a table",
    "the last concert ticket",
    "an accidental spoiler",
    "a burnt-out light bulb",
    "free delivery",
    "my inner child",
    "a morning jog",
    "a line of trust",
    "huge sunglasses",
    "a very loud alarm",
    "the wrong address",
    "the GPS voice",
    "an auntie with a cake",
    "a nightmare",
    "a dragon in the basement",
    "a forgotten Wi-Fi password",
    "tangled headphones",
    "mixed-up slippers",
    "a regifted present",
    "a pile of dirty dishes",
    "hide and seek at work",
    "a romantic dinner from delivery",
    "a broken coffee machine",
    "free samples",
    "a new haircut",
    "a huge queue",
    "gum under the desk",
    "cat hair on everything",
    "a very smart vacuum",
    "fishing without fish",
    "a country house full of mosquitoes",
    "a family photo from 1998",
    "grandma's rug on the wall",
    "flat soda",
    "ice cream in winter",
    "a cake that fell",
    "dancing at my uncle's wedding",
    "a fortune teller at the market",
    "an eternal student",
    "a huge bouquet",
    "a brutally honest friend",
    "a favorite shirt with a hole",
    "a mystery bag",
    "a sudden crush",
    "a neighbor who sings in the shower",
    "overpriced coffee",
    "a pajama party",
    "an unexpected day off",
    "three missed calls from mom",
    "microwave chicken",
    "a cat that knocked over the tree",
    "a 40,000 tenge receipt",
    "a philosopher taxi driver",
    "a melon hookah",
    "a ball pit",
    "cold dumplings",
    "a voice note from the boss at 11:59 pm",
    "a broken printer",
    "grandpa's mustache",
    "a scooter on the sidewalk",
    "a very angry goose",
    "fake Adidas",
    "a Dimash song on repeat",
    "a dentist with jokes",
    "an extra kilo of tangerines",
    "Mafia until 5 am",
    "a stranger at my wedding",
    "an aunt with a camera",
    "the iron I left on",
    "a car wash in the rain",
    "a secret admirer",
    "a cat in a hat",
    "the downstairs neighbors",
    "my ex-boss",
    "a washing machine on spin",
    "the fifth slice of cake",
    "kumis on an empty stomach",
    "kurt in my pocket",
    "mountains of dirty dishes",
    "the naked emperor",
    "a dragon in the parking lot",
    "a 3% discount coupon",
    "a one-way ticket",
    "a broken zipper on jeans",
    "a fur hat with ear flaps",
    "someone else's kid on the plane",
    "a sleeping security guard",
    "a lecture about crypto",
    "a 6 am jog",
    "a spinach smoothie",
    "an awkward wedding toast",
    "endless road repairs",
    "a slow cooker",
    "a secret alumni chat",
    "a stuck robot vacuum",
    "a chat with voicemail",
    "the neighbor's cat on my balcony",
    "a first date in a cafeteria",
    "an umbrella on a sunny day",
    "a bag of bags in a bag",
    "mom on Facebook",
    "my uncle's longest toast",
    "a three-hour line at the service center",
    "a battery at 2%",
    "a cat staring at the wall",
    "second breakfast",
    "socks with sandals",
    "loyalty cards for 200 stores",
    "a DJ neighbor",
    "a blanket with sleeves",
    "the cactus I overwatered",
    "an elevator going the wrong way",
    "a jingle from an ad",
    "grandma's jam",
    "jacket potatoes",
    "a picnic in the rain",
    "a group photo with closed eyes",
    "a Christmas tree in March",
    "a Santa suit",
    "a lying bathroom scale",
    "a 4:30 alarm",
    "an evening without internet",
    "dried fish in the office",
    "an accidental video call",
    "a cat that opened the fridge",
    "gum on my shoe",
    "a frog in my pocket",
    "a surprise party I knew about",
    "a free trial",
    "a subscription I forgot to cancel",
    "a night shift",
    "a neighbor with drums",
    "a life coach",
    "very expensive water",
    "a donut with a surprise",
    "a notebook of secrets",
    "a broken AC in July",
    "heating in May",
    "an elevator selfie",
    "a campfire guitar song",
    "a guitar missing two strings",
    "a bag left in a taxi",
    "a tired waiter",
    "cat hair on a black sweater",
    "new sneakers in a puddle",
    "an uncle who knows everything about football",
    "a Napoleon cake",
    "my passport photo at 16",
    "my school diary",
    "a knitting club",
    "a camping trip without a tent",
    "a ration pack",
    "a bull in a china shop",
    "bunny slippers",
    "a balloon that flew away",
    "a funny accent",
    "a bucket of popcorn",
    "a movie everyone praises",
    "a season finale",
    "a secret room in IKEA",
    "a random guest in Zoom",
    "a muted microphone",
    "a camera left on in pajamas",
    "five minutes to deadline",
    "an invite to my ex's wedding",
    "grandma's pickles",
    "a password on a sticky note",
    "dombra lessons",
    "a tandoor in the yard",
    "a feast for 30 people",
    "endless lagman",
    "chak-chak for breakfast",
    "a badly translated manual",
    "flat-pack furniture without instructions",
    "a spare bolt",
    "a neighbor who parks across two spots",
    "a tinted old sedan",
    "a tuned Camry",
    "the neighbor's rooster",
    "a cat yelling at 5 am",
    "a fridge with only mustard",
    "a 7-day weight loss course",
    "dumbbells under the bed",
    "a dusty gym membership",
    "someone else's headphones",
    "a song that makes everyone cry",
    "a karaoke battle",
    "a squealing microphone",
    "a tired party entertainer",
    "a bouncy castle",
    "cotton candy",
    "a Ferris wheel",
    "a roller coaster",
    "a suitcase missing a wheel",
    "a passport left at home",
    "a canceled flight",
    "a night at the airport",
    "a souvenir from Turkey",
    "a fridge magnet",
    "a vacation romance",
    "a T-shirt tan",
    "a sunburn",
    "a jellyfish on the beach",
    "a water gun",
    "an inflatable flamingo",
    "a grandma on a bench",
    "the neighbor kid with a ball",
    "a broken window",
    "a school dance",
    "a graduation album",
    "the chemistry teacher",
    "an explosion in chemistry class",
    "an F for behavior",
    "a note from my parents",
    "a doctor's note",
    "a leg broken skiing",
    "the ski resort on a weekend",
    "the skating rink on Sunday",
    "the TV tower hill with tourists",
    "the big mountain lake",
    "Charyn Canyon",
    "a camel that spat",
    "a horse with attitude",
    "a golden eagle on my shoulder",
    "a yurt downtown",
    "spring soup for the whole yard",
    "a kebab chef with gold teeth",
    "a wedding hall",
    "an MC with an accordion",
    "a who's-the-loudest contest",
    "the bride ransom",
    "a gift in an envelope",
    "a cake with a photo on it",
    "the neighbors' fireworks",
    "blinking string lights",
    "a New Year's speech",
    "tangerines under the tree",
    "a party popper",
    "a snowflake costume",
    "a kindergarten show",
    "socks for New Year",
    "a glitter card",
    "an endless family dinner",
    "the \"when are the grandkids coming?\" question",
    "a blogger cousin",
    "an MLM aunt",
    "grandma's secret ingredient",
    "burnt eggs",
    "a smoking frying pan",
    "a smoke alarm",
    "neighbors who called the police",
    "a pillow fight",
    "a blanket fort",
    "a movie marathon",
    "a campfire ghost story",
    "a rustle in the dark",
    "a cat that was in the closet all along",
    "lost keys",
    "a spare key under the mat",
    "a broken intercom",
    "a courier calling at 7 am",
    "a package from China after six months",
    "an order that doesn't fit",
    "a marketplace return",
    "a one-star review",
    "the buy-in-one-click button",
    "Black Friday",
    "90% off everything useless",
    "cashback on cashback",
    "a banking app mid-update",
    "a transfer to the wrong person",
    "owing a friend 500 tenge",
    "splitting the bill",
    "a tip in coins",
    "a waiter who mixed everything up",
    "soup with a fly",
    "a dessert on the house",
    "a chef in a bad mood",
    "a restaurant where everyone sings",
    "live music way too close",
    "dancing at the office party",
    "the boss at karaoke",
    "team building in the woods",
    "a rope course",
    "paintball with accounting",
    "a meeting that could've been an email",
    "an 80-slide presentation",
    "a frozen spreadsheet",
    "the save button I didn't press",
    "the intern who fixed everything",
    "a Friday release",
    "a postponed vacation",
    "a sick day on Friday",
    "vending machine coffee",
    "cookies in the meeting room",
    "someone else's lunch in the fridge",
  ],
};
