// Generated content bank. Edit the source lists, keep RU and EN aligned.
export const FAKE_FACT_QUESTIONS: ReadonlyArray<{ ru: { question: string; truth: string }; en: { question: string; truth: string } }> = [
  { ru: { question: "Сколько часовых поясов в России?", truth: "11" }, en: { question: "How many time zones does Russia have?", truth: "11" } },
  { ru: { question: "Какое национальное животное Шотландии?", truth: "Единорог" }, en: { question: "What is Scotland's national animal?", truth: "Unicorn" } },
  { ru: { question: "Сколько сердец у осьминога?", truth: "Три" }, en: { question: "How many hearts does an octopus have?", truth: "Three" } },
  { ru: { question: "Какого цвета кровь у осьминога?", truth: "Голубая" }, en: { question: "What color is octopus blood?", truth: "Blue" } },
  { ru: { question: "Какой фрукт с точки зрения ботаники является ягодой?", truth: "Банан" }, en: { question: "Which fruit is botanically a berry?", truth: "Banana" } },
  { ru: { question: "Сколько лет может храниться мёд, не портясь?", truth: "Тысячи лет" }, en: { question: "How long can honey keep without spoiling?", truth: "Thousands of years" } },
  { ru: { question: "Как называется страх длинных слов?", truth: "Гиппопотомонстросесквиппедалиофобия" }, en: { question: "What is the fear of long words called?", truth: "Hippopotomonstrosesquippedaliophobia" } },
  { ru: { question: "Сколько времени идёт свет от Солнца до Земли?", truth: "Около 8 минут" }, en: { question: "How long does sunlight take to reach Earth?", truth: "About 8 minutes" } },
  { ru: { question: "Какое животное может спать стоя?", truth: "Лошадь" }, en: { question: "Which animal can sleep standing up?", truth: "Horse" } },
  { ru: { question: "Кто придумал слово «робот»?", truth: "Брат Карела Чапека" }, en: { question: "Who coined the word robot?", truth: "Karel Čapek's brother" } },
  { ru: { question: "Сколько костей у взрослого человека?", truth: "206" }, en: { question: "How many bones does an adult human have?", truth: "206" } },
  { ru: { question: "Сколько костей у новорождённого примерно?", truth: "Около 300" }, en: { question: "Roughly how many bones does a newborn have?", truth: "About 300" } },
  { ru: { question: "Какое животное изображено на флаге Уэльса?", truth: "Дракон" }, en: { question: "What animal is on the flag of Wales?", truth: "A dragon" } },
  { ru: { question: "Что изначально продавала компания Nokia?", truth: "Бумагу" }, en: { question: "What did Nokia originally make?", truth: "Paper" } },
  { ru: { question: "Какая страна изобрела бумагу?", truth: "Китай" }, en: { question: "Which country invented paper?", truth: "China" } },
  { ru: { question: "Что означает слово «Алматы» по популярной версии?", truth: "Яблочный" }, en: { question: "What does the name Almaty popularly mean?", truth: "Place of apples" } },
  { ru: { question: "Сколько глаз у пчелы?", truth: "Пять" }, en: { question: "How many eyes does a bee have?", truth: "Five" } },
  { ru: { question: "Какая единственная буква не встречается в названиях штатов США?", truth: "Q" }, en: { question: "Which letter appears in no US state name?", truth: "Q" } },
  { ru: { question: "Какое животное не может прыгать?", truth: "Слон" }, en: { question: "Which large animal cannot jump?", truth: "The elephant" } },
  { ru: { question: "Сколько минут длился полёт Гагарина?", truth: "108" }, en: { question: "How many minutes did Gagarin's flight last?", truth: "108" } },
  { ru: { question: "Какой газ делает голос смешным и тонким?", truth: "Гелий" }, en: { question: "Which gas makes your voice sound squeaky?", truth: "Helium" } },
  { ru: { question: "Какой цвет у чёрного ящика самолёта на самом деле?", truth: "Оранжевый" }, en: { question: "What color is an airplane's black box?", truth: "Orange" } },
  { ru: { question: "Сколько раз примерно в день моргает человек?", truth: "Около 15 тысяч" }, en: { question: "Roughly how many times a day does a person blink?", truth: "About 15,000" } },
  { ru: { question: "Какая планета вращается «лёжа на боку»?", truth: "Уран" }, en: { question: "Which planet spins on its side?", truth: "Uranus" } },
  { ru: { question: "Как называется группа фламинго?", truth: "Фламбоянс" }, en: { question: "What is a group of flamingos called?", truth: "A flamboyance" } },
  { ru: { question: "Сколько сердцебиений в минуту у колибри может быть?", truth: "Больше 1000" }, en: { question: "How fast can a hummingbird's heart beat per minute?", truth: "Over 1,000" } },
  { ru: { question: "Какой вкус не чувствуют кошки?", truth: "Сладкий" }, en: { question: "Which taste can cats not detect?", truth: "Sweet" } },
  { ru: { question: "Что было первым видео на YouTube?", truth: "Прогулка по зоопарку" }, en: { question: "What was the first video on YouTube?", truth: "A trip to the zoo" } },
  { ru: { question: "Сколько длилась самая короткая война в истории?", truth: "Около 40 минут" }, en: { question: "How long did the shortest war in history last?", truth: "About 40 minutes" } },
  { ru: { question: "Как назывался первый клонированный из взрослой клетки млекопитающее?", truth: "Овечка Долли" }, en: { question: "What was the first mammal cloned from an adult cell?", truth: "Dolly the sheep" } },
  { ru: { question: "Какой напиток изначально продавали как лекарство?", truth: "Кока-колу" }, en: { question: "Which soft drink was first sold as a medicine?", truth: "Coca-Cola" } },
  { ru: { question: "Какое копытное животное считается ближайшим живым родственником кита?", truth: "Бегемот" }, en: { question: "Which hoofed animal is the whale's closest living relative?", truth: "The hippopotamus" } },
  { ru: { question: "Сколько лет длилась Столетняя война?", truth: "116" }, en: { question: "How long did the Hundred Years' War last?", truth: "116 years" } },
  { ru: { question: "Что изобрёл Джеймс Нейсмит в 1891 году?", truth: "Баскетбол" }, en: { question: "What did James Naismith invent in 1891?", truth: "Basketball" } },
  { ru: { question: "Чем изначально были мячи для гольфа, по одной из версий, в XVII веке?", truth: "Кожей, набитой перьями" }, en: { question: "What were early golf balls made of?", truth: "Leather stuffed with feathers" } },
  { ru: { question: "Какой рыбе приписывают трёхсекундную память, хотя это миф?", truth: "Золотой рыбке" }, en: { question: "Which fish is wrongly said to have a three-second memory?", truth: "The goldfish" } },
  { ru: { question: "Как называется детёныш кенгуру?", truth: "Джоуи" }, en: { question: "What is a baby kangaroo called?", truth: "A joey" } },
  { ru: { question: "Какое животное спит, держась за лапы, чтобы не уплыть?", truth: "Калан" }, en: { question: "Which animal holds hands while sleeping so it won't drift apart?", truth: "The sea otter" } },
  { ru: { question: "Сколько ног у омара?", truth: "10" }, en: { question: "How many legs does a lobster have?", truth: "10" } },
  { ru: { question: "Как звали первую собаку на орбите?", truth: "Лайка" }, en: { question: "What was the name of the first dog in orbit?", truth: "Laika" } },
  { ru: { question: "Какое государство самое маленькое в мире?", truth: "Ватикан" }, en: { question: "What is the world's smallest country?", truth: "Vatican City" } },
  { ru: { question: "В какой стране больше всего озёр?", truth: "Канада" }, en: { question: "Which country has the most lakes?", truth: "Canada" } },
  { ru: { question: "Что едят панды почти всё время?", truth: "Бамбук" }, en: { question: "What do pandas eat almost all the time?", truth: "Bamboo" } },
  { ru: { question: "Что появилось раньше: мамонты вымерли или построили пирамиды?", truth: "Пирамиды построили раньше" }, en: { question: "What came first: the last mammoths dying out or the pyramids?", truth: "The pyramids" } },
  { ru: { question: "Как называется пустое место между передними зубами?", truth: "Диастема" }, en: { question: "What is a gap between front teeth called?", truth: "Diastema" } },
  { ru: { question: "Какой частью тела слышат змеи вибрации?", truth: "Челюстью" }, en: { question: "What body part helps snakes sense vibrations?", truth: "Their jaw" } },
  { ru: { question: "Как называется запах земли после дождя?", truth: "Петрикор" }, en: { question: "What is the smell of earth after rain called?", truth: "Petrichor" } },
  { ru: { question: "Как называют точку над буквами i и j?", truth: "Титл" }, en: { question: "What is the dot over i and j called?", truth: "A tittle" } },
  { ru: { question: "Как называется пластиковый наконечник шнурка?", truth: "Эглет" }, en: { question: "What is the plastic tip of a shoelace called?", truth: "An aglet" } },
  { ru: { question: "Как называется страх остаться без телефона?", truth: "Номофобия" }, en: { question: "What is the fear of being without your phone?", truth: "Nomophobia" } },
  { ru: { question: "Кто был первым человеком, вышедшим в открытый космос?", truth: "Алексей Леонов" }, en: { question: "Who made the first spacewalk?", truth: "Alexei Leonov" } },
  { ru: { question: "Какой город раньше назывался Верный?", truth: "Алматы" }, en: { question: "Which city was once called Verny?", truth: "Almaty" } },
  { ru: { question: "Какой город раньше назывался Целиноград?", truth: "Астана" }, en: { question: "Which city was once called Tselinograd?", truth: "Astana" } },
  { ru: { question: "Сколько метров высоты у Байтерека?", truth: "97" }, en: { question: "How tall is Baiterek in meters?", truth: "97" } },
  { ru: { question: "Почему высота Байтерека именно такая?", truth: "В честь 1997 года переноса столицы" }, en: { question: "Why is Baiterek that exact height?", truth: "For 1997, when the capital moved" } },
  { ru: { question: "На какой высоте над морем каток Медеу примерно?", truth: "Около 1700 метров" }, en: { question: "At roughly what altitude is Medeu ice rink?", truth: "About 1,700 meters" } },
  { ru: { question: "Какое растение считается предком всех культурных яблонь?", truth: "Яблоня Сиверса" }, en: { question: "Which wild tree is the ancestor of the domestic apple?", truth: "Sievers' apple" } },
  { ru: { question: "Где растёт дикая яблоня Сиверса?", truth: "В горах Казахстана" }, en: { question: "Where does the wild Sievers' apple grow?", truth: "In the mountains of Kazakhstan" } },
  { ru: { question: "Какая птица может летать задом наперёд?", truth: "Колибри" }, en: { question: "Which bird can fly backwards?", truth: "Hummingbird" } },
  { ru: { question: "Какое животное имеет квадратные экскременты?", truth: "Вомбат" }, en: { question: "Which animal produces cube-shaped poop?", truth: "The wombat" } },
  { ru: { question: "Какой фрукт плавает в воде, потому что на четверть состоит из воздуха?", truth: "Яблоко" }, en: { question: "Which fruit floats because it is about a quarter air?", truth: "Apple" } },
  { ru: { question: "Сколько дней длится год на Меркурии?", truth: "88" }, en: { question: "How many Earth days is a year on Mercury?", truth: "88" } },
  { ru: { question: "Сколько весит облако среднего размера примерно?", truth: "Сотни тонн" }, en: { question: "Roughly how much does an average cloud weigh?", truth: "Hundreds of tonnes" } },
  { ru: { question: "Сколько секунд длился первый полёт братьев Райт?", truth: "12" }, en: { question: "How many seconds did the Wright brothers' first flight last?", truth: "12" } },
  { ru: { question: "Каким был первый компьютерный «баг» в прямом смысле?", truth: "Мотылёк" }, en: { question: "What was the first literal computer bug?", truth: "A moth" } },
  { ru: { question: "Что делали из тыкв до изобретения стеклянных фонарей на Хэллоуин в Ирландии?", truth: "Фонари из репы" }, en: { question: "What did the Irish carve before pumpkins?", truth: "Turnips" } },
  { ru: { question: "Как называется лишний день високосного года?", truth: "29 февраля" }, en: { question: "What is the extra day in a leap year?", truth: "February 29" } },
  { ru: { question: "Сколько зубов у улитки примерно?", truth: "Тысячи" }, en: { question: "Roughly how many teeth does a snail have?", truth: "Thousands" } },
];
