export const LOST_LOCATION_ROUNDS: ReadonlyArray<{ ru: string; en: string }> = [
  { ru: "Пляж", en: "Beach" },
  { ru: "Больница", en: "Hospital" },
  { ru: "Космическая станция", en: "Space station" },
  { ru: "Школа", en: "School" },
  { ru: "Ресторан", en: "Restaurant" },
  { ru: "Аэропорт", en: "Airport" },
  { ru: "Музей", en: "Museum" },
  { ru: "Вокзал", en: "Train station" },
  { ru: "Кинотеатр", en: "Movie theater" },
  { ru: "Зоопарк", en: "Zoo" },
  { ru: "Цирк", en: "Circus" },
  { ru: "Банк", en: "Bank" },
  { ru: "Полицейский участок", en: "Police station" },
  { ru: "Пожарная часть", en: "Fire station" },
  { ru: "Подводная лодка", en: "Submarine" },
  { ru: "Пиратский корабль", en: "Pirate ship" },
  { ru: "Круизный лайнер", en: "Cruise ship" },
  { ru: "Самолёт", en: "Airplane" },
  { ru: "Поезд дальнего следования", en: "Long-distance train" },
  { ru: "Метро", en: "Subway" },
  { ru: "Супермаркет", en: "Supermarket" },
  { ru: "Базар", en: "Bazaar" },
  { ru: "Торговый центр", en: "Shopping mall" },
  { ru: "Спортзал", en: "Gym" },
  { ru: "Стадион", en: "Stadium" },
  { ru: "Бассейн", en: "Swimming pool" },
  { ru: "Горнолыжный курорт", en: "Ski resort" },
  { ru: "Каток", en: "Ice rink" },
  { ru: "Аквапарк", en: "Water park" },
  { ru: "Парк аттракционов", en: "Amusement park" },
  { ru: "Библиотека", en: "Library" },
  { ru: "Университет", en: "University" },
  { ru: "Детский сад", en: "Kindergarten" },
  { ru: "Офис", en: "Office" },
  { ru: "Стройка", en: "Construction site" },
  { ru: "Ферма", en: "Farm" },
  { ru: "Юрта в степи", en: "Yurt in the steppe" },
  { ru: "Дача", en: "Country house" },
  { ru: "Палаточный лагерь", en: "Campsite" },
  { ru: "Пещера", en: "Cave" },
  { ru: "Пустыня", en: "Desert" },
  { ru: "Джунгли", en: "Jungle" },
  { ru: "Необитаемый остров", en: "Desert island" },
  { ru: "Северный полюс", en: "North Pole" },
  { ru: "Лунная база", en: "Moon base" },
  { ru: "Замок", en: "Castle" },
  { ru: "Королевский дворец", en: "Royal palace" },
  { ru: "Тюрьма", en: "Prison" },
  { ru: "Казино", en: "Casino" },
  { ru: "Ночной клуб", en: "Nightclub" },
  { ru: "Караоке-бар", en: "Karaoke bar" },
  { ru: "Кофейня", en: "Coffee shop" },
  { ru: "Пекарня", en: "Bakery" },
  { ru: "Парикмахерская", en: "Barbershop" },
  { ru: "Салон красоты", en: "Beauty salon" },
  { ru: "Баня", en: "Bathhouse" },
  { ru: "Спа-салон", en: "Spa" },
  { ru: "Автосервис", en: "Car repair shop" },
  { ru: "Заправка", en: "Gas station" },
  { ru: "Свадьба", en: "Wedding" },
  { ru: "Выпускной", en: "Prom" },
  { ru: "Корпоратив", en: "Office party" },
  { ru: "Концерт", en: "Concert" },
  { ru: "Театр", en: "Theater" },
  { ru: "Оперный театр", en: "Opera house" },
  { ru: "Телестудия", en: "TV studio" },
  { ru: "Радиостудия", en: "Radio station" },
  { ru: "Съёмочная площадка", en: "Film set" },
  { ru: "Редакция газеты", en: "Newsroom" },
  { ru: "Лаборатория", en: "Laboratory" },
  { ru: "Обсерватория", en: "Observatory" },
  { ru: "Посольство", en: "Embassy" },
  { ru: "Суд", en: "Courtroom" },
  { ru: "Церковь", en: "Church" },
  { ru: "Мечеть", en: "Mosque" },
  { ru: "Кладбище", en: "Cemetery" },
  { ru: "Маяк", en: "Lighthouse" },
  { ru: "Порт", en: "Harbor" },
  { ru: "Рыбацкая лодка", en: "Fishing boat" },
  { ru: "Военная база", en: "Military base" },
  { ru: "Олимпийская деревня", en: "Olympic village" },
  { ru: "Медеу", en: "Medeu ice rink" },
  { ru: "Шымбулак", en: "Shymbulak ski resort" },
  { ru: "Кок-Тобе", en: "Kok-Tobe hill" },
  { ru: "Зелёный базар", en: "Green Bazaar" },
  { ru: "Отель", en: "Hotel" },
  { ru: "Хостел", en: "Hostel" },
  { ru: "Боулинг", en: "Bowling alley" },
  { ru: "Квест-комната", en: "Escape room" },
  { ru: "Ветеринарная клиника", en: "Vet clinic" },
  { ru: "Стоматология", en: "Dental clinic" },
  { ru: "Почта", en: "Post office" },
  { ru: "Автобус", en: "Bus" },
  { ru: "Такси", en: "Taxi" },
  { ru: "Лифт", en: "Elevator" },
  { ru: "Школьный автобус", en: "School bus" },
  { ru: "Кухня ресторана", en: "Restaurant kitchen" },
  { ru: "Музей восковых фигур", en: "Wax museum" },
  { ru: "Планетарий", en: "Planetarium" },
  { ru: "Океанариум", en: "Aquarium" },
  { ru: "Ботанический сад", en: "Botanical garden" },
  { ru: "Шоколадная фабрика", en: "Chocolate factory" },
  { ru: "Модный показ", en: "Fashion show" },
  { ru: "Аукцион", en: "Auction house" },
  { ru: "Турнир по шахматам", en: "Chess tournament" },
  { ru: "Автосалон", en: "Car dealership" },
];
