import type { CopyKey, Locale } from "@/lib/i18n";

export type GameCategory = "full_game" | "quick_tool" | "experimental";
export type GameAgeRating = "kids" | "teen" | "adult";
export type GameReleaseStatus = "beta" | "certified";
export type GameCapability = "rounds" | "timer" | "submissions" | "voting" | "teams" | "secret_state" | "drawing" | "cards" | "spectators" | "score_tracking";

export interface GameDefinition {
  id: string;
  titleKey: CopyKey;
  descKey: CopyKey;
  icon: string;
  tone: "lime" | "pink" | "blue" | "cream";
  category: GameCategory;
  releaseStatus: GameReleaseStatus;
  minPlayers: number;
  maxPlayers: number;
  ageRating: GameAgeRating;
  supportedLocales: readonly Locale[];
  capabilities: readonly GameCapability[];
  seo: { slug: string; legacySlugs?: readonly string[]; durationMinutes: number; equipment: "phones" | "phones_and_stage" };
}

const locales = ["ru", "en"] as const satisfies readonly Locale[];

function game<T extends GameDefinition>(definition: T) { return definition; }

export const GAME_MANIFEST = [
  game({ id: "alias", titleKey: "gamesAliasTitle", descKey: "gamesAliasDesc", icon: "record_voice_over", tone: "lime", category: "full_game", releaseStatus: "beta", minPlayers: 4, maxPlayers: 20, ageRating: "kids", supportedLocales: locales, capabilities: ["rounds", "timer", "teams", "spectators"], seo: { slug: "word-blast", legacySlugs: ["alias"], durationMinutes: 15, equipment: "phones_and_stage" } }),
  game({ id: "mafia", titleKey: "gamesMafiaTitle", descKey: "gamesMafiaDesc", icon: "mystery", tone: "pink", category: "full_game", releaseStatus: "beta", minPlayers: 5, maxPlayers: 20, ageRating: "teen", supportedLocales: locales, capabilities: ["rounds", "timer", "voting", "secret_state", "spectators"], seo: { slug: "mafia-lite", durationMinutes: 25, equipment: "phones_and_stage" } }),
  game({ id: "truth", titleKey: "gamesTruthTitle", descKey: "gamesTruthDesc", icon: "casino", tone: "blue", category: "full_game", releaseStatus: "beta", minPlayers: 2, maxPlayers: 20, ageRating: "adult", supportedLocales: locales, capabilities: ["rounds", "spectators"], seo: { slug: "truth-or-dare", durationMinutes: 20, equipment: "phones" } }),
  game({ id: "never", titleKey: "gamesNeverTitle", descKey: "gamesNeverDesc", icon: "front_hand", tone: "cream", category: "full_game", releaseStatus: "beta", minPlayers: 3, maxPlayers: 20, ageRating: "adult", supportedLocales: locales, capabilities: ["rounds", "submissions", "spectators"], seo: { slug: "never-have-i-ever", durationMinutes: 15, equipment: "phones" } }),
  game({ id: "beer", titleKey: "gamesBeerTitle", descKey: "gamesBeerDesc", icon: "sports_bar", tone: "pink", category: "quick_tool", releaseStatus: "beta", minPlayers: 2, maxPlayers: 12, ageRating: "adult", supportedLocales: locales, capabilities: ["score_tracking"], seo: { slug: "cup-toss-score", legacySlugs: ["beer-pong"], durationMinutes: 20, equipment: "phones" } }),
  game({ id: "quiz", titleKey: "gamesQuizTitle", descKey: "gamesQuizDesc", icon: "quiz", tone: "lime", category: "full_game", releaseStatus: "beta", minPlayers: 2, maxPlayers: 30, ageRating: "kids", supportedLocales: locales, capabilities: ["rounds", "timer", "submissions", "spectators"], seo: { slug: "quiz-battle", durationMinutes: 15, equipment: "phones_and_stage" } }),
  game({ id: "pairs", titleKey: "gamesPairsTitle", descKey: "gamesPairsDesc", icon: "shuffle", tone: "blue", category: "quick_tool", releaseStatus: "beta", minPlayers: 4, maxPlayers: 30, ageRating: "kids", supportedLocales: locales, capabilities: ["teams"], seo: { slug: "random-pairs", durationMinutes: 5, equipment: "phones" } }),
  game({ id: "uno", titleKey: "gamesUnoTitle", descKey: "gamesUnoDesc", icon: "style", tone: "cream", category: "full_game", releaseStatus: "beta", minPlayers: 2, maxPlayers: 10, ageRating: "kids", supportedLocales: locales, capabilities: ["rounds", "cards", "secret_state", "spectators"], seo: { slug: "color-cards", legacySlugs: ["uno"], durationMinutes: 25, equipment: "phones" } }),
  game({ id: "werewolf", titleKey: "gamesWerewolfTitle", descKey: "gamesWerewolfDesc", icon: "bug_report", tone: "pink", category: "full_game", releaseStatus: "beta", minPlayers: 4, maxPlayers: 20, ageRating: "teen", supportedLocales: locales, capabilities: ["rounds", "timer", "voting", "secret_state", "spectators"], seo: { slug: "night-wolves", legacySlugs: ["werewolf"], durationMinutes: 20, equipment: "phones_and_stage" } }),
  game({ id: "codenames", titleKey: "gamesCodenamesTitle", descKey: "gamesCodenamesDesc", icon: "vpn_key", tone: "blue", category: "full_game", releaseStatus: "beta", minPlayers: 4, maxPlayers: 20, ageRating: "kids", supportedLocales: locales, capabilities: ["rounds", "teams", "secret_state", "spectators"], seo: { slug: "secret-grid", legacySlugs: ["codenames"], durationMinutes: 20, equipment: "phones_and_stage" } }),
  game({ id: "spyfall", titleKey: "gamesSpyfallTitle", descKey: "gamesSpyfallDesc", icon: "visibility", tone: "lime", category: "full_game", releaseStatus: "beta", minPlayers: 4, maxPlayers: 16, ageRating: "teen", supportedLocales: locales, capabilities: ["rounds", "timer", "voting", "secret_state", "spectators"], seo: { slug: "lost-location", legacySlugs: ["spyfall"], durationMinutes: 15, equipment: "phones" } }),
  game({ id: "impostor", titleKey: "gamesImpostorTitle", descKey: "gamesImpostorDesc", icon: "person_off", tone: "cream", category: "full_game", releaseStatus: "beta", minPlayers: 4, maxPlayers: 20, ageRating: "teen", supportedLocales: locales, capabilities: ["rounds", "voting", "secret_state", "spectators"], seo: { slug: "impostor", durationMinutes: 15, equipment: "phones" } }),
  game({ id: "crocodil", titleKey: "gamesCrocodilTitle", descKey: "gamesCrocodilDesc", icon: "theater_comedy", tone: "lime", category: "full_game", releaseStatus: "beta", minPlayers: 4, maxPlayers: 24, ageRating: "kids", supportedLocales: locales, capabilities: ["rounds", "timer", "teams", "spectators"], seo: { slug: "mime-riot", legacySlugs: ["crocodil"], durationMinutes: 20, equipment: "phones_and_stage" } }),
  game({ id: "headsup", titleKey: "gamesHeadsUpTitle", descKey: "gamesHeadsUpDesc", icon: "cell_tower", tone: "blue", category: "full_game", releaseStatus: "beta", minPlayers: 2, maxPlayers: 20, ageRating: "kids", supportedLocales: locales, capabilities: ["rounds", "timer", "secret_state"], seo: { slug: "forehead-guess", legacySlugs: ["heads-up"], durationMinutes: 15, equipment: "phones" } }),
  game({ id: "quiplash", titleKey: "gamesQuiplashTitle", descKey: "gamesQuiplashDesc", icon: "emoji_emotions", tone: "pink", category: "full_game", releaseStatus: "beta", minPlayers: 3, maxPlayers: 16, ageRating: "teen", supportedLocales: locales, capabilities: ["rounds", "submissions", "voting", "spectators"], seo: { slug: "punchline", legacySlugs: ["quiplash"], durationMinutes: 20, equipment: "phones_and_stage" } }),
  game({ id: "fibbage", titleKey: "gamesFibbageTitle", descKey: "gamesFibbageDesc", icon: "psychology", tone: "cream", category: "full_game", releaseStatus: "beta", minPlayers: 3, maxPlayers: 16, ageRating: "teen", supportedLocales: locales, capabilities: ["rounds", "submissions", "voting", "spectators"], seo: { slug: "fake-fact", legacySlugs: ["fibbage"], durationMinutes: 20, equipment: "phones_and_stage" } }),
  game({ id: "wouldRather", titleKey: "gamesWouldRatherTitle", descKey: "gamesWouldRatherDesc", icon: "compare", tone: "lime", category: "full_game", releaseStatus: "beta", minPlayers: 2, maxPlayers: 30, ageRating: "teen", supportedLocales: locales, capabilities: ["rounds", "voting", "spectators"], seo: { slug: "would-you-rather", durationMinutes: 15, equipment: "phones" } }),
  game({ id: "twoTruths", titleKey: "gamesTwoTruthsTitle", descKey: "gamesTwoTruthsDesc", icon: "fact_check", tone: "blue", category: "full_game", releaseStatus: "beta", minPlayers: 3, maxPlayers: 20, ageRating: "kids", supportedLocales: locales, capabilities: ["rounds", "submissions", "voting", "spectators"], seo: { slug: "two-truths-and-a-lie", durationMinutes: 20, equipment: "phones" } }),
  game({ id: "blankSlate", titleKey: "gamesBlankSlateTitle", descKey: "gamesBlankSlateDesc", icon: "edit_note", tone: "cream", category: "full_game", releaseStatus: "beta", minPlayers: 3, maxPlayers: 20, ageRating: "kids", supportedLocales: locales, capabilities: ["rounds", "submissions", "spectators"], seo: { slug: "same-word", legacySlugs: ["blank-slate"], durationMinutes: 15, equipment: "phones_and_stage" } }),
  game({ id: "wavelength", titleKey: "gamesWavelengthTitle", descKey: "gamesWavelengthDesc", icon: "tune", tone: "pink", category: "full_game", releaseStatus: "beta", minPlayers: 4, maxPlayers: 20, ageRating: "kids", supportedLocales: locales, capabilities: ["rounds", "teams", "submissions", "spectators"], seo: { slug: "spectrum", legacySlugs: ["wavelength"], durationMinutes: 20, equipment: "phones_and_stage" } }),
  game({ id: "brainBurst", titleKey: "gamesBrainBurstTitle", descKey: "gamesBrainBurstDesc", icon: "bolt", tone: "lime", category: "full_game", releaseStatus: "beta", minPlayers: 2, maxPlayers: 30, ageRating: "kids", supportedLocales: locales, capabilities: ["rounds", "timer", "submissions", "spectators"], seo: { slug: "brain-burst", durationMinutes: 15, equipment: "phones_and_stage" } }),
  game({ id: "guessSong", titleKey: "gamesGuessSongTitle", descKey: "gamesGuessSongDesc", icon: "music_note", tone: "blue", category: "full_game", releaseStatus: "beta", minPlayers: 2, maxPlayers: 30, ageRating: "teen", supportedLocales: locales, capabilities: ["rounds", "timer", "submissions", "spectators"], seo: { slug: "guess-the-song", durationMinutes: 20, equipment: "phones_and_stage" } }),
  game({ id: "bombParty", titleKey: "gamesBombPartyTitle", descKey: "gamesBombPartyDesc", icon: "local_fire_department", tone: "pink", category: "full_game", releaseStatus: "beta", minPlayers: 2, maxPlayers: 20, ageRating: "kids", supportedLocales: locales, capabilities: ["rounds", "timer", "submissions", "spectators"], seo: { slug: "word-bomb", legacySlugs: ["bomb-party"], durationMinutes: 15, equipment: "phones_and_stage" } }),
  game({ id: "bunker", titleKey: "gamesBunkerTitle", descKey: "gamesBunkerDesc", icon: "shield", tone: "cream", category: "full_game", releaseStatus: "beta", minPlayers: 5, maxPlayers: 20, ageRating: "teen", supportedLocales: locales, capabilities: ["rounds", "submissions", "voting", "secret_state", "spectators"], seo: { slug: "bunker", durationMinutes: 35, equipment: "phones_and_stage" } }),
  game({ id: "wheel", titleKey: "gamesWheelTitle", descKey: "gamesWheelDesc", icon: "casino", tone: "lime", category: "quick_tool", releaseStatus: "beta", minPlayers: 2, maxPlayers: 30, ageRating: "kids", supportedLocales: locales, capabilities: ["score_tracking"], seo: { slug: "wheel-of-fate", durationMinutes: 5, equipment: "phones" } }),
  game({ id: "kissMarry", titleKey: "gamesKissMarryTitle", descKey: "gamesKissMarryDesc", icon: "favorite", tone: "pink", category: "full_game", releaseStatus: "beta", minPlayers: 3, maxPlayers: 20, ageRating: "adult", supportedLocales: locales, capabilities: ["rounds", "voting", "spectators"], seo: { slug: "pick-three", legacySlugs: ["kiss-marry-kill"], durationMinutes: 15, equipment: "phones" } }),
  game({ id: "charades", titleKey: "gamesCharadesTitle", descKey: "gamesCharadesDesc", icon: "theater_comedy", tone: "blue", category: "full_game", releaseStatus: "beta", minPlayers: 4, maxPlayers: 24, ageRating: "kids", supportedLocales: locales, capabilities: ["rounds", "timer", "teams", "spectators"], seo: { slug: "charades", durationMinutes: 20, equipment: "phones_and_stage" } }),
  game({ id: "trivia", titleKey: "gamesTriviaTitle", descKey: "gamesTriviaDesc", icon: "school", tone: "cream", category: "full_game", releaseStatus: "beta", minPlayers: 2, maxPlayers: 30, ageRating: "kids", supportedLocales: locales, capabilities: ["rounds", "timer", "submissions", "spectators"], seo: { slug: "trivia", durationMinutes: 15, equipment: "phones_and_stage" } }),
  game({ id: "pictionary", titleKey: "gamesPictionaryTitle", descKey: "gamesPictionaryDesc", icon: "draw", tone: "lime", category: "full_game", releaseStatus: "beta", minPlayers: 3, maxPlayers: 20, ageRating: "kids", supportedLocales: locales, capabilities: ["rounds", "timer", "drawing", "secret_state", "spectators"], seo: { slug: "draw-and-guess", legacySlugs: ["pictionary"], durationMinutes: 20, equipment: "phones_and_stage" } }),
  game({ id: "gartic", titleKey: "gamesGarticTitle", descKey: "gamesGarticDesc", icon: "gesture", tone: "blue", category: "full_game", releaseStatus: "beta", minPlayers: 4, maxPlayers: 16, ageRating: "kids", supportedLocales: locales, capabilities: ["rounds", "drawing", "submissions", "secret_state", "spectators"], seo: { slug: "draw-chain", legacySlugs: ["gartic-phone"], durationMinutes: 25, equipment: "phones_and_stage" } }),
  game({ id: "cardsChaos", titleKey: "gamesCardsChaosTitle", descKey: "gamesCardsChaosDesc", icon: "playing_cards", tone: "pink", category: "full_game", releaseStatus: "beta", minPlayers: 3, maxPlayers: 16, ageRating: "adult", supportedLocales: locales, capabilities: ["rounds", "cards", "submissions", "secret_state", "voting", "spectators"], seo: { slug: "cards-of-chaos", durationMinutes: 25, equipment: "phones_and_stage" } }),
  game({ id: "musicQuiz", titleKey: "gamesMusicQuizTitle", descKey: "gamesMusicQuizDesc", icon: "library_music", tone: "cream", category: "full_game", releaseStatus: "beta", minPlayers: 2, maxPlayers: 30, ageRating: "teen", supportedLocales: locales, capabilities: ["rounds", "timer", "submissions", "spectators"], seo: { slug: "music-quiz", durationMinutes: 20, equipment: "phones_and_stage" } }),
] as const;

export type GameId = (typeof GAME_MANIFEST)[number]["id"];
export const GAME_COUNT = GAME_MANIFEST.length;

export function getGameById(id: string) { return GAME_MANIFEST.find((game) => game.id === id); }
export function getGameBySlug(slug: string) { return GAME_MANIFEST.find((game) => game.seo.slug === slug || ("legacySlugs" in game.seo && game.seo.legacySlugs?.includes(slug))); }
export function isGameId(value: string): value is GameId { return GAME_MANIFEST.some((game) => game.id === value); }
export function formatPlayerRange(game: Pick<GameDefinition, "minPlayers" | "maxPlayers">) { return game.maxPlayers >= 30 ? `${game.minPlayers}+` : `${game.minPlayers}–${game.maxPlayers}`; }
