export const MIME_RIOT_WORDS = {
  ru: [
    "Готовишь ужин",
    "Бежишь марафон",
    "Ведёшь машину",
    "Ловишь рыбу",
    "Играешь на гитаре",
    "Плывёшь",
    "Лезешь на дерево",
    "Танцуешь балет",
    "Лепишь снеговика",
    "Рисуешь картину",
    "Выгуливаешь собаку",
    "Едешь на велосипеде",
    "Катаешься на лыжах",
    "Играешь в баскетбол",
    "Сражаешься с драконом",
    "Прыгаешь с парашютом",
  ],
  en: [
    "Cooking dinner",
    "Running a marathon",
    "Driving a car",
    "Fishing",
    "Playing guitar",
    "Swimming",
    "Climbing a tree",
    "Dancing ballet",
    "Building a snowman",
    "Painting a picture",
    "Walking a dog",
    "Riding a bicycle",
    "Skiing",
    "Playing basketball",
    "Fighting a dragon",
    "Skydiving",
  ],
} as const;
