// Generated content bank. Edit the source lists, keep RU and EN aligned.
export const PICK_THREE_SETS: ReadonlyArray<readonly [string, string, string]> = [
  ["Tom Hanks", "Zendaya", "Keanu Reeves"],
  ["Beyoncé", "Ryan Gosling", "Dwayne Johnson"],
  ["Taylor Swift", "Chris Hemsworth", "Emma Stone"],
  ["Leonardo DiCaprio", "Ariana Grande", "Idris Elba"],
  ["Timothée Chalamet", "Rihanna", "Pedro Pascal"],
  ["Brad Pitt", "Lady Gaga", "Jackie Chan"],
  ["Harry Styles", "Scarlett Johansson", "Will Smith"],
  ["Johnny Depp", "Margot Robbie", "Bruno Mars"],
  ["Tom Holland", "Billie Eilish", "Morgan Freeman"],
  ["Robert Downey Jr.", "Selena Gomez", "Jason Momoa"],
  ["Keira Knightley", "Ed Sheeran", "Hugh Jackman"],
  ["Jennifer Aniston", "The Rock", "Justin Bieber"],
  ["Angelina Jolie", "Cristiano Ronaldo", "Adele"],
  ["Lionel Messi", "Kim Kardashian", "Benedict Cumberbatch"],
  ["Shakira", "Jake Gyllenhaal", "Anne Hathaway"],
  ["Dua Lipa", "Henry Cavill", "Jim Carrey"],
  ["Natalie Portman", "Drake", "Matt Damon"],
  ["Gal Gadot", "Snoop Dogg", "Daniel Radcliffe"],
  ["Emma Watson", "Rowan Atkinson", "Post Malone"],
  ["Katy Perry", "Chris Evans", "Tom Cruise"],
  ["Nicole Kidman", "Eminem", "Mr. Bean"],
  ["Cameron Diaz", "Vin Diesel", "Harry Potter"],
  ["Shrek", "Batman", "Darth Vader"],
  ["Iron Man", "Spider-Man", "Captain America"],
  ["Jack Sparrow", "James Bond", "Indiana Jones"],
  ["Sherlock Holmes", "Dr. Watson", "Hercule Poirot"],
  ["Barbie", "Ken", "Wednesday Addams"],
  ["Cinderella", "Rapunzel", "Snow White"],
  ["Elsa", "Moana", "Mulan"],
  ["Aladdin", "Jasmine", "Genie"],
  ["Thor", "Loki", "Hulk"],
  ["Joker", "Harley Quinn", "Catwoman"],
  ["Gandalf", "Aragorn", "Legolas"],
  ["Hermione Granger", "Ron Weasley", "Draco Malfoy"],
  ["Ross", "Rachel", "Chandler"],
  ["Joey", "Monica", "Phoebe"],
  ["Homer Simpson", "SpongeBob", "Patrick Star"],
  ["Mickey Mouse", "Donald Duck", "Goofy"],
  ["Winnie the Pooh", "Tigger", "Eeyore"],
  ["Masha", "the Bear", "Cheburashka"],
  ["Mario", "Luigi", "Princess Peach"],
  ["Sonic", "Pikachu", "Pac-Man"],
  ["Rocky Balboa", "Terminator", "RoboCop"],
  ["Forrest Gump", "Jack Dawson", "Neo"],
  ["Wolverine", "Deadpool", "Superman"],
  ["Wonder Woman", "Black Widow", "Captain Marvel"],
  ["Tony Stark", "Bruce Wayne", "Clark Kent"],
  ["Mr. Darcy", "Romeo", "Christian Grey"],
  ["Edward Cullen", "Jacob Black", "Count Dracula"],
  ["Buzz Lightyear", "Woody", "Mr. Potato Head"],
  ["Simba", "Nala", "Timon"],
  ["Nemo", "Dory", "Bruce the shark"],
  ["Olaf", "Sven", "Kristoff"],
  ["Yoda", "Chewbacca", "R2-D2"],
  ["Shrek", "Donkey", "Fiona"],
  ["Peter Pan", "Captain Hook", "Tinker Bell"],
  ["Beauty", "the Beast", "Gaston"],
  ["Tarzan", "Mowgli", "Robin Hood"],
  ["Sherlock", "Moriarty", "Mrs. Hudson"],
  ["Walter White", "Jesse Pinkman", "Saul Goodman"],
  ["Jon Snow", "Daenerys", "Tyrion Lannister"],
  ["Arya Stark", "Sansa Stark", "Cersei Lannister"],
  ["Eleven", "Steve Harrington", "Hopper"],
  ["Dr. House", "Dr. Wilson", "Dr. Cuddy"],
  ["Michael Scott", "Dwight Schrute", "Jim Halpert"],
  ["Sheldon Cooper", "Penny", "Leonard"],
  ["Bart Simpson", "Lisa Simpson", "Marge Simpson"],
  ["Garfield", "Tom the cat", "Puss in Boots"],
  ["Kung Fu Panda", "Master Shifu", "Tigress"],
  ["Maleficent", "Ursula", "Cruella de Vil"],
  ["Aang", "Zuko", "Katara"],
  ["Naruto", "Sasuke", "Goku"],
  ["Lara Croft", "Geralt of Rivia", "Master Chief"],
  ["Minion Bob", "Gru", "Dr. Nefario"],
  ["Stitch", "Lilo", "Baymax"],
  ["Paddington", "Mr. Bean", "Mary Poppins"],
  ["Dracula", "Frankenstein", "the Mummy"],
  ["Santa Claus", "Father Frost", "the Grinch"],
  ["Aldar Kose", "Khoja Nasreddin", "Baba Yaga"],
  ["Gingerbread Man", "Pinocchio", "Buratino"],
];
