// Generated content bank. Edit the source lists, keep RU and EN aligned.
export const PUNCHLINE_PROMPTS: { readonly ru: readonly string[]; readonly en: readonly string[] } = {
  ru: [
    "Худшее, что можно сказать на первом свидании",
    "Самая бесполезная суперспособность",
    "Что инопланетяне думают о Земле",
    "Плохое оправдание опоздания",
    "Ужасное название для рок-группы",
    "Что кот сказал бы первым, если бы заговорил",
    "Новый вкус мороженого, который никто не купит",
    "Что написано на могиле самого ленивого человека",
    "Худший подарок на свадьбу",
    "Название для сериала о жизни этой компании",
    "Самая странная причина уволиться",
    "Что нельзя говорить таксисту",
    "Слоган для самого честного банка",
    "Новый праздник, который нужен Казахстану",
    "Худший совет от бабушки",
    "Что прячет у себя в холодильнике супергерой",
    "Первое, что сделает робот, получив выходной",
    "Самый неловкий статус в соцсетях",
    "Что говорит навигатор, когда обиделся",
    "Название ресторана, в который никто не пойдёт",
    "Худшая тема для тоста на свадьбе",
    "Секретный ингредиент бабушкиного плова",
    "Что думает собака, когда хозяин уходит на работу",
    "Самая скучная суперсила злодея",
    "Новое правило для очереди в поликлинике",
    "Что на самом деле означает «я уже выхожу»",
    "Идеальное название для стартапа-провала",
    "Худшая фраза для собеседования",
    "Что шепчет пылесос, когда его выключают",
    "Название для духов с запахом понедельника",
    "Самый странный вопрос в анкете для знакомств",
    "Как назвать кота, который умнее хозяина",
    "Что сказал бы Колобок в интервью",
    "Лучшее оправдание, почему не помыл посуду",
    "Слоган для чемпионата по лени",
    "Что пишут на открытке человеку, которого не знаешь",
    "Худшее место для первого поцелуя",
    "Что спрятано в сумке у мамы на все случаи жизни",
    "Новая функция смартфона, которая всех бесит",
    "Что говорит кондиционер зимой",
    "Название для бренда носков, которые всегда теряются",
    "Худший сюжет для фильма ужасов",
    "Что делает Дед Мороз летом",
    "Самая неудачная фраза для извинения",
    "Причина, почему динозавры вымерли на самом деле",
    "Что написано в резюме у пирата",
    "Главный секрет этой тусы",
    "Самое бессмысленное изобретение",
    "Что стоит на заставке телефона у злодея",
    "Худший способ признаться в любви",
    "Новый олимпийский вид спорта для ленивых",
    "Что кричат болельщики на чемпионате по шахматам",
    "Название приложения, которое никто не скачает",
    "Что говорит холодильник ночью",
    "Самый странный подарок начальнику",
    "Лучшее название для домашнего Wi-Fi",
    "Что пишут в отзыве на самый плохой отель",
    "Как узнать, что ты слишком долго дома",
    "Худшее, что можно услышать от пилота",
    "Что прячут под подушкой взрослые",
    "Новый вид такси, который обречён на провал",
    "Что сказал бы беркут, если бы вёл блог",
    "Как назвать мем про эту компанию",
    "Худший саундтрек для свадьбы",
    "Что думает кактус о своей жизни",
    "Самая честная реклама фастфуда",
    "Слоган для караоке, где поют только мимо нот",
    "Как объяснить бабушке, что такое NFT",
    "Худшее блюдо на дастархане",
    "Что обычно говорят в лифте незнакомцы",
    "Название для книги о вашей последней поездке",
    "Самое ужасное хобби для соседа сверху",
    "Что кричит чайник, когда закипает",
    "Худшее имя для питомца-дракона",
    "Новая эмоция, для которой нужна эмодзи",
    "Что сделает человек, выигравший тонну баурсаков",
    "Самая странная причина для вечеринки",
    "Как назвать группу в чате родителей",
    "Тост, после которого все замолчали",
    "Что делает ленивец в пятницу вечером",
    "Самый опасный ингредиент для торта",
    "Как понять, что вечеринка удалась",
    "Худший способ разбудить соседа",
    "Что видел будильник, чего не видели мы",
    "Реклама школы, где учат опаздывать",
    "Что ответит голосовой помощник на «Как дела?» в плохой день",
    "Самая скучная тема для подкаста",
    "Как назвать коктейль, после которого все танцуют",
    "Первое правило бойцовского клуба бабушек",
    "Что скрывает кнопка «Пропустить рекламу»",
    "Самое неудачное время для чихания",
    "Что говорит мама, когда видит твою комнату",
    "Новая профессия будущего, которая звучит странно",
    "Худший спойлер в истории",
    "Почему у кота на самом деле девять жизней",
    "Что лежит в чемодане у путешественника во времени",
    "Название фитнес-программы для любителей дивана",
    "Самая странная просьба к курьеру",
    "Что шепчут друг другу деревья в Медеу",
    "Главный закон вашей тусовки",
    "Что пишут на кружке самого вредного начальника",
    "Худшее место для отпуска",
    "Что сделал бы единорог с миллионом долларов",
    "Самая смешная причина для штрафа",
    "Название для ток-шоу, которое ведёт кот",
    "Что скажет тесто, когда его месят",
    "Худшее, что можно написать в общий чат",
    "Как попросить повышение у дракона",
    "Секретное оружие против понедельника",
    "Новая традиция на Новый год",
    "Что спрашивает Siri у Алисы при встрече",
    "Самое плохое место для свидания в Алматы",
    "Что снится роботу-пылесосу",
    "Лозунг для забастовки носков",
  ],
  en: [
    "The worst thing to say on a first date",
    "The most useless superpower",
    "What aliens think about Earth",
    "A terrible excuse for being late",
    "A terrible name for a rock band",
    "The first thing a cat would say if it could talk",
    "An ice cream flavor nobody would buy",
    "What is written on the laziest person's gravestone",
    "The worst wedding gift",
    "A TV show title about this group",
    "The strangest reason to quit a job",
    "Something you should never say to a taxi driver",
    "A slogan for the most honest bank",
    "A new holiday Kazakhstan needs",
    "The worst advice from grandma",
    "What a superhero hides in their fridge",
    "The first thing a robot does on its day off",
    "The most awkward social media status",
    "What a GPS says when it is offended",
    "A restaurant name that would scare everyone away",
    "The worst topic for a wedding toast",
    "The secret ingredient in grandma's pilaf",
    "What a dog thinks when its owner leaves for work",
    "The most boring villain superpower",
    "A new rule for the clinic queue",
    "What \"I'm leaving now\" really means",
    "The perfect name for a failed startup",
    "The worst line in a job interview",
    "What a vacuum whispers when turned off",
    "A perfume name that smells like Monday",
    "The strangest question on a dating profile",
    "A name for a cat smarter than its owner",
    "What the Gingerbread Man would say in an interview",
    "The best excuse for not doing the dishes",
    "A slogan for the laziness championship",
    "What to write on a card for someone you don't know",
    "The worst place for a first kiss",
    "What mom keeps in her bag for every emergency",
    "A new phone feature that annoys everyone",
    "What an air conditioner says in winter",
    "A brand name for socks that always go missing",
    "The worst plot for a horror movie",
    "What Father Frost does in summer",
    "The worst possible apology",
    "The real reason dinosaurs went extinct",
    "What a pirate writes on their CV",
    "The biggest secret of this party",
    "The most pointless invention",
    "What a villain has as their phone wallpaper",
    "The worst way to confess love",
    "A new Olympic sport for lazy people",
    "What fans shout at a chess championship",
    "An app nobody would download",
    "What the fridge says at night",
    "The strangest gift for a boss",
    "The best name for a home Wi-Fi network",
    "A review of the worst hotel ever",
    "How you know you've been home too long",
    "The worst thing to hear from a pilot",
    "What adults hide under their pillow",
    "A new kind of taxi doomed to fail",
    "What an eagle would post if it had a blog",
    "A name for a meme about this group",
    "The worst wedding soundtrack",
    "What a cactus thinks about its life",
    "The most honest fast food ad",
    "A slogan for an off-key karaoke bar",
    "How to explain NFTs to grandma",
    "The worst dish on a dastarkhan",
    "What strangers say in an elevator",
    "A title for a book about your last trip",
    "The worst hobby for an upstairs neighbor",
    "What a kettle yells when it boils",
    "The worst name for a pet dragon",
    "A new emotion that needs an emoji",
    "What someone would do after winning a ton of baursaks",
    "The strangest reason to throw a party",
    "A name for the parents' group chat",
    "The toast that made everyone go silent",
    "What a sloth does on Friday night",
    "The most dangerous cake ingredient",
    "How you know the party was a success",
    "The worst way to wake a roommate",
    "What the alarm clock has seen that we haven't",
    "An ad for a school that teaches lateness",
    "What a voice assistant says to \"How are you?\" on a bad day",
    "The most boring podcast topic",
    "A cocktail name that makes everyone dance",
    "The first rule of grandma fight club",
    "What the Skip Ad button is hiding",
    "The worst moment to sneeze",
    "What mom says when she sees your room",
    "A strange-sounding future job",
    "The worst spoiler in history",
    "Why cats really have nine lives",
    "What a time traveler packs",
    "A fitness program for couch lovers",
    "The strangest request to a courier",
    "What the trees in Medeu whisper to each other",
    "The main law of your crew",
    "What's written on the grumpiest boss's mug",
    "The worst vacation destination",
    "What a unicorn would do with a million dollars",
    "The funniest reason to get fined",
    "A talk show hosted by a cat",
    "What dough says while being kneaded",
    "The worst thing to post in a group chat",
    "How to ask a dragon for a raise",
    "The secret weapon against Monday",
    "A new New Year tradition",
    "What Siri asks Alexa when they meet",
    "The worst date spot in Almaty",
    "What a robot vacuum dreams about",
    "A slogan for a sock strike",
  ],
};
