import type { GameId } from "./manifest";

export type GameRules = { overview: string; steps: string[]; tips: string[] };
export const GAME_RULES: Record<"ru" | "en", Record<GameId, GameRules>> = {
  en: {
    alias:{overview:"Explain the secret word to your team without saying it.",steps:["Join the lobby and form teams.","The active player explains the prompt before time expires.","Mark correct answers and rotate the active player."],tips:["Use short clues.","Keep a phone per player connected."]},
    mafia:{overview:"A social deduction game with private roles, night actions and public voting.",steps:["Five or more players join; the stage deals roles.","At night, special roles choose on their own phones.","Discuss by day, vote, then reveal the result."],tips:["Never reveal another player’s screen.","Reopen the same party after a disconnect."]},
    truth:{overview:"The stage chooses Truth or Dare and everyone plays the same round.",steps:["The stage chooses a card.","Players answer or skip from their phones.","Start the next card when the group is ready."],tips:["Respect a skip without questions.","Use the safe profile for an all-ages party."]},
    never:{overview:"Read the statement and privately mark whether it applies to you.",steps:["Read the shared statement.","Each player chooses Me or Skip once.","The stage advances to the next statement."],tips:["No one must explain an answer.","Keep the mood light and consensual."]},
    beer:{overview:"A shared cup-toss scorekeeper for two teams.",steps:["Choose a side.","Any participant records hits or returned cups.","The stage finishes when the match is over."],tips:["Agree on the score before recording.","This is a score tool, not a drinking rulebook."]},
    quiz:{overview:"Answer the same question faster than everyone else.",steps:["Read the question and options.","Pick one answer before the timer ends.","The stage reveals the answer and starts the next round."],tips:["Answers lock after one tap.","Fast correct answers earn more points."]},
    pairs:{overview:"The server creates fresh pairs from everyone in the session.",steps:["Join the game lobby.","Read the pair challenge.","The stage generates the next pairing."],tips:["Odd players become a rotating trio.","Use the same party session so everyone sees the pairs."]},
    uno:{overview:"A private-hand colour card game with shared turn order.",steps:["Join before the stage starts.","Play a legal card or draw on your turn.","Empty your hand to win the round."],tips:["Only your own hand is visible.","Reconnect restores your hand and turn."]},
    werewolf:{overview:"Private roles, night actions, discussion and elimination voting.",steps:["Five or more players join and receive roles.","Night roles act privately.","The group discusses and votes until a side wins."],tips:["Do not show role cards.","Dead players should not influence votes."]},
    codenames:{overview:"Two teams connect words using clues from their spymasters.",steps:["Assign one spymaster per team.","The active spymaster gives a clue and number.","Teammates reveal words without hitting the assassin."],tips:["Only spymasters see hidden colours.","Use one clue per turn."]},
    spyfall:{overview:"Most players know the location; one spy tries to blend in.",steps:["Receive your private role.","Ask questions without naming the location.","Vote or let the spy make a final guess."],tips:["Ask specific but non-obvious questions.","Never read a role aloud."]},
    impostor:{overview:"Find the player without the shared word.",steps:["Read your private word or impostor role.","Everyone gives one clue.","Vote and reveal the outcome."],tips:["Give useful but not obvious clues.","The impostor may attempt a word guess."]},
    crocodil:{overview:"Act out a prompt while your team guesses.",steps:["The active player sees the prompt.","Act without speaking.","Mark correct or pass before the timer ends."],tips:["Keep gestures visible to the group.","Rotate the phone after every turn."]},
    headsup:{overview:"Guess the word on your forehead using friends’ clues.",steps:["One player holds the controller facing away.","Others give clues without saying the word.","Mark correct or skip and rotate."],tips:["The active player should not see the prompt.","Use landscape mode for larger cards."]},
    quiplash:{overview:"Write funny answers and vote for the strongest one.",steps:["Submit one answer privately.","Read the anonymous choices.","Vote for another player’s answer."],tips:["You cannot vote for yourself.","Keep answers party-safe."]},
    fibbage:{overview:"Invent believable fake answers around one real fact.",steps:["Write a convincing false answer.","Choose the answer you think is true.","Reveal truth and score correct or deceptive votes."],tips:["Do not copy the real answer.","Read every option before voting."]},
    wouldRather:{overview:"Make a choice, then compare the room’s split.",steps:["Read both options.","Vote once from your phone.","Reveal the group split and continue."],tips:["There is no wrong answer.","Use safe mode for family prompts."]},
    twoTruths:{overview:"Spot the lie among three statements.",steps:["Read the three statements.","Vote for the one you think is false.","Reveal the lie and continue."],tips:["Vote only once.","Discuss before the reveal."]},
    blankSlate:{overview:"Match other players with the same one-word answer.",steps:["Write one answer privately.","Wait until everyone submits.","Reveal matches and score shared ideas."],tips:["Short common answers work best.","Other answers stay hidden until reveal."]},
    wavelength:{overview:"Give a clue for a hidden position on a spectrum.",steps:["The clue-giver receives the hidden target.","Give one clue to the team.","Teammates place their guess and reveal."],tips:["Avoid number-like clues.","The target remains hidden until reveal."]},
    brainBurst:{overview:"A rapid-fire quiz with a short timer.",steps:["Read the question.","Choose one answer before time runs out.","Reveal and move to the next question."],tips:["Fast correct answers earn bonus points.","Do not refresh to change an answer."]},
    guessSong:{overview:"Identify a song from artist, year and a factual clue.",steps:["Read the shared clue.","Type one title before the timer ends.","See the answer and leaderboard."],tips:["The title is hidden server-side until reveal.","Use the official title when possible."]},
    bombParty:{overview:"Find unique words under pressure.",steps:["Read the required starting letters.","Submit a valid unused word.","The stage resolves the round and eliminations."],tips:["Duplicate words do not count.","Think ahead while others type."]},
    bunker:{overview:"Argue for a place in the bunker and vote strategically.",steps:["Join the lobby and receive your profile.","Reveal information and make your case.","Vote each round until the group is resolved."],tips:["Keep private cards private.","Use the safe content profile when needed."]},
    wheel:{overview:"Build a shared wheel, then let the server choose.",steps:["Anyone adds an option.","The stage spins the wheel.","Use the result or spin a new round."],tips:["Duplicate options are blocked.","The result is not chosen by the client."]},
    kissMarry:{overview:"Assign three playful choices to three people.",steps:["Read the three names.","Assign each action exactly once.","Reveal the group’s choices."],tips:["Keep it consensual and respectful.","Use safe mode for younger groups."]},
    charades:{overview:"Perform a prompt while your team guesses against the timer.",steps:["The active player receives a word.","Act it out without speaking.","Mark correct, pass or finish the turn."],tips:["Only the active player sees the word.","Rotate roles after each turn."]},
    trivia:{overview:"A five-round knowledge quiz.",steps:["Read each question.","Choose one option before the deadline.","Reveal the correct option and scores."],tips:["One answer per player.","Fast correct answers score more."]},
    pictionary:{overview:"Draw the secret prompt while others guess.",steps:["The artist gets a private prompt.","Draw on the shared board.","Players submit guesses until someone is correct."],tips:["Do not write letters in the drawing.","Reconnect restores the round state."]},
    gartic:{overview:"Pass drawings and guesses through a creative chain.",steps:["Receive a private prompt.","Draw or guess for your current turn.","Reveal the final chain together."],tips:["Keep each turn short.","Do not reveal your prompt early."]},
    cardsChaos:{overview:"Match a response card to the funniest prompt.",steps:["Choose one card from your private hand.","The judge picks a winner.","Draw again and start the next round."],tips:["The judge cannot submit a card.","Hands remain private."]},
    musicQuiz:{overview:"A timed music knowledge round with factual clues.",steps:["Read the artist and era clue.","Send one title.","Reveal the answer and continue."],tips:["No lyrics are required.","Your answer is locked after sending."]},
  },
  ru: {} as Record<GameId, GameRules>,
};

const ruOverview: Record<GameId, string> = { alias:"Объясняйте слова команде на скорость.",mafia:"Найдите мафию через ночные действия и голосование.",truth:"Выбирайте правду или задание и играйте в комфортном темпе.",never:"Отмечайте личный ответ на общий вопрос без обязательных объяснений.",beer:"Ведите общий счёт двух команд.",quiz:"Отвечайте на вопросы быстрее остальных.",pairs:"Получайте новые пары и совместные задания.",uno:"Избавьтесь от закрытой руки цветных карт.",werewolf:"Используйте тайные роли, ночь и дневное голосование.",codenames:"Соединяйте слова командными подсказками.",spyfall:"Найдите шпиона, не раскрыв локацию.",impostor:"Выявите игрока без общего слова.",crocodil:"Показывайте слово без речи.",headsup:"Угадайте слово по подсказкам друзей.",quiplash:"Пишите смешные ответы и голосуйте за другие.",fibbage:"Придумывайте правдоподобные версии и находите факт.",wouldRather:"Выбирайте один вариант и сравнивайте ответы.",twoTruths:"Найдите ложь среди трёх утверждений.",blankSlate:"Совпадите с другими в одном слове.",wavelength:"Поставьте командную догадку на шкале.",brainBurst:"Пройдите быстрые вопросы на время.",guessSong:"Угадайте трек по безопасной фактической подсказке.",bombParty:"Называйте уникальные слова до взрыва таймера.",bunker:"Аргументируйте место в бункере и голосуйте.",wheel:"Соберите варианты и крутите общее колесо.",kissMarry:"Распределите три действия между тремя именами.",charades:"Показывайте слово, пока команда угадывает.",trivia:"Пройдите пять раундов вопросов.",pictionary:"Рисуйте секретное слово, пока остальные угадывают.",gartic:"Передавайте рисунки и догадки по цепочке.",cardsChaos:"Подбирайте карту-ответ и выбирайте самый смешной вариант.",musicQuiz:"Угадайте песню по артисту, эпохе и факту." };
for (const id of Object.keys(GAME_RULES.en) as GameId[]) {
  GAME_RULES.ru[id] = { overview: ruOverview[id], steps:["Подключитесь к лобби этой игры со своего устройства.","Следуйте общей подсказке на экране и отправьте своё действие только один раз.","Дождитесь результата раунда или следующей команды хоста."], tips:["После перезагрузки откройте ту же тусу, и сессия восстановится.","Не показывайте другим игрокам приватные роли, карты и ответы."] };
}
