// Generated content bank. Edit the source lists, keep RU and EN aligned.
export const SPECTRUM_PAIRS: { readonly ru: ReadonlyArray<readonly [string, string]>; readonly en: ReadonlyArray<readonly [string, string]> } = {
  ru: [
    ["Горячо", "Холодно"],
    ["Скучно", "Захватывающе"],
    ["Дёшево", "Дорого"],
    ["Безопасно", "Рискованно"],
    ["Старое", "Новое"],
    ["Обычное", "Странное"],
    ["Полезная еда", "Вредная еда"],
    ["Легко выучить", "Сложно выучить"],
    ["Грустная песня", "Весёлая песня"],
    ["Переоценено", "Недооценено"],
    ["Милое животное", "Страшное животное"],
    ["Для детей", "Для взрослых"],
    ["Тихое место", "Шумное место"],
    ["Бесполезный навык", "Полезный навык"],
    ["Ужасный фильм", "Шедевр"],
    ["Маленькое", "Огромное"],
    ["Мягкое", "Твёрдое"],
    ["Скучная профессия", "Крутая профессия"],
    ["Лёгкий вид спорта", "Тяжёлый вид спорта"],
    ["Летняя вещь", "Зимняя вещь"],
    ["Романтично", "Совсем не романтично"],
    ["Знаменитость на час", "Легенда навсегда"],
    ["Сладкое", "Солёное"],
    ["Уютно", "Неуютно"],
    ["Пахнет приятно", "Пахнет ужасно"],
    ["Быстро", "Медленно"],
    ["Умный", "Глупый"],
    ["Модно", "Старомодно"],
    ["Хороший подарок", "Плохой подарок"],
    ["Реальное", "Вымышленное"],
    ["Злодей", "Герой"],
    ["Утреннее занятие", "Вечернее занятие"],
    ["Легко нарисовать", "Сложно нарисовать"],
    ["Нормальная пицца", "Странная пицца"],
    ["Хорошая суперсила", "Плохая суперсила"],
    ["Спокойное животное", "Опасное животное"],
    ["Можно есть руками", "Нужны приборы"],
    ["Интроверт", "Экстраверт"],
    ["Для первого свидания", "Для десятого свидания"],
    ["Лёгкий", "Тяжёлый"],
    ["Классика", "Новинка"],
    ["Популярное", "Нишевое"],
    ["Хорошая привычка", "Плохая привычка"],
    ["Кот одобрит", "Кот возненавидит"],
    ["Важное изобретение", "Бесполезное изобретение"],
    ["Легко объяснить", "Сложно объяснить"],
    ["Праздничное", "Будничное"],
    ["Гениальная идея", "Ужасная идея"],
    ["Естественное", "Искусственное"],
    ["Честно", "Нечестно"],
    ["Полезно для здоровья", "Вредно для здоровья"],
    ["Круто в 15 лет", "Круто в 50 лет"],
    ["Лучше одному", "Лучше с компанией"],
    ["Надолго", "Ненадолго"],
    ["Нужная вещь в походе", "Бесполезная вещь в походе"],
    ["Мирно", "Хаотично"],
    ["Красиво", "Некрасиво"],
    ["Чисто", "Грязно"],
    ["Вкусный напиток", "Невкусный напиток"],
    ["Серьёзно", "Смешно"],
    ["Секрет", "Все знают"],
    ["Слабый", "Сильный"],
    ["Хороший сосед", "Ужасный сосед"],
    ["Хорошее имя для питомца", "Плохое имя для питомца"],
    ["Близко", "Далеко"],
    ["Простое блюдо", "Сложное блюдо"],
    ["Вредный совет", "Мудрый совет"],
    ["Лучшее время года", "Худшее время года"],
    ["Смелый поступок", "Трусливый поступок"],
    ["Мокрое", "Сухое"],
    ["Громко", "Тихо"],
    ["Ленивое хобби", "Активное хобби"],
    ["Скучная тема для разговора", "Интересная тема"],
    ["Легко потерять", "Сложно потерять"],
    ["Популярно в Алматы", "Популярно в Астане"],
    ["Легенда караоке", "Худшая песня для караоке"],
    ["Хорошая работа мечты", "Работа на кошмар"],
    ["Идеальный отпуск", "Худший отпуск"],
    ["Стоит своих денег", "Не стоит своих денег"],
    ["Взрослое решение", "Детское решение"],
    ["Раздражает", "Успокаивает"],
    ["Люксовое", "Бюджетное"],
    ["Спортивно", "Неспортивно"],
    ["Тёмное", "Светлое"],
    ["Опасно для телефона", "Безопасно для телефона"],
    ["Сюжет для драмы", "Сюжет для комедии"],
    ["Предсказуемо", "Неожиданно"],
    ["Хорошее первое впечатление", "Плохое первое впечатление"],
    ["Традиционное", "Современное"],
    ["Жёсткое правило", "Мягкое правило"],
    ["Тяжело ждать", "Легко ждать"],
    ["Социальная сеть для бабушек", "Социальная сеть для подростков"],
    ["Хорошо пахнет в машине", "Плохо пахнет в машине"],
    ["Нужно на тусе", "Лишнее на тусе"],
  ],
  en: [
    ["Hot", "Cold"],
    ["Boring", "Exciting"],
    ["Cheap", "Expensive"],
    ["Safe", "Risky"],
    ["Old", "New"],
    ["Ordinary", "Strange"],
    ["Healthy food", "Junk food"],
    ["Easy to learn", "Hard to learn"],
    ["Sad song", "Happy song"],
    ["Overrated", "Underrated"],
    ["Cute animal", "Scary animal"],
    ["For kids", "For adults"],
    ["Quiet place", "Loud place"],
    ["Useless skill", "Useful skill"],
    ["Terrible movie", "Masterpiece"],
    ["Tiny", "Huge"],
    ["Soft", "Hard"],
    ["Boring job", "Cool job"],
    ["Easy sport", "Hard sport"],
    ["Summer thing", "Winter thing"],
    ["Romantic", "Not romantic at all"],
    ["Fifteen minutes of fame", "Legend forever"],
    ["Sweet", "Salty"],
    ["Cozy", "Uncomfortable"],
    ["Smells great", "Smells awful"],
    ["Fast", "Slow"],
    ["Smart", "Silly"],
    ["Trendy", "Old-fashioned"],
    ["Great gift", "Bad gift"],
    ["Real", "Fictional"],
    ["Villain", "Hero"],
    ["Morning activity", "Evening activity"],
    ["Easy to draw", "Hard to draw"],
    ["Normal pizza", "Weird pizza"],
    ["Good superpower", "Bad superpower"],
    ["Calm animal", "Dangerous animal"],
    ["Finger food", "Needs cutlery"],
    ["Introvert", "Extrovert"],
    ["First date idea", "Tenth date idea"],
    ["Light", "Heavy"],
    ["Classic", "Brand new"],
    ["Mainstream", "Niche"],
    ["Good habit", "Bad habit"],
    ["A cat would approve", "A cat would hate it"],
    ["Important invention", "Pointless invention"],
    ["Easy to explain", "Hard to explain"],
    ["Festive", "Everyday"],
    ["Genius idea", "Terrible idea"],
    ["Natural", "Artificial"],
    ["Fair", "Unfair"],
    ["Good for health", "Bad for health"],
    ["Cool at 15", "Cool at 50"],
    ["Better alone", "Better with friends"],
    ["Lasts long", "Short-lived"],
    ["Camping essential", "Camping clutter"],
    ["Peaceful", "Chaotic"],
    ["Beautiful", "Ugly"],
    ["Clean", "Dirty"],
    ["Tasty drink", "Nasty drink"],
    ["Serious", "Funny"],
    ["Secret", "Common knowledge"],
    ["Weak", "Strong"],
    ["Great neighbor", "Awful neighbor"],
    ["Good pet name", "Bad pet name"],
    ["Near", "Far"],
    ["Simple dish", "Complicated dish"],
    ["Bad advice", "Wise advice"],
    ["Best season", "Worst season"],
    ["Brave act", "Cowardly act"],
    ["Wet", "Dry"],
    ["Loud", "Quiet"],
    ["Lazy hobby", "Active hobby"],
    ["Boring topic", "Interesting topic"],
    ["Easy to lose", "Hard to lose"],
    ["Popular in Almaty", "Popular in Astana"],
    ["Karaoke legend", "Worst karaoke song"],
    ["Dream job", "Nightmare job"],
    ["Perfect vacation", "Worst vacation"],
    ["Worth the money", "Not worth it"],
    ["Grown-up choice", "Childish choice"],
    ["Annoying", "Relaxing"],
    ["Luxury", "Budget"],
    ["Sporty", "Unsporty"],
    ["Dark", "Bright"],
    ["Dangerous for a phone", "Safe for a phone"],
    ["Drama plot", "Comedy plot"],
    ["Predictable", "Surprising"],
    ["Good first impression", "Bad first impression"],
    ["Traditional", "Modern"],
    ["Strict rule", "Loose rule"],
    ["Hard to wait for", "Easy to wait for"],
    ["Social network for grandmas", "Social network for teens"],
    ["Nice car smell", "Bad car smell"],
    ["Party essential", "Party killer"],
  ],
};
