// Generated content bank. Edit the source lists, keep RU and EN aligned.
export const WOULD_RATHER_PROMPTS: ReadonlyArray<{ ru: { a: string; b: string }; en: { a: string; b: string } }> = [
  { ru: { a: "Уметь летать", b: "Становиться невидимым" }, en: { a: "Be able to fly", b: "Be able to turn invisible" } },
  { ru: { a: "Жить без музыки", b: "Жить без фильмов" }, en: { a: "Live without music", b: "Live without movies" } },
  { ru: { a: "Всегда опаздывать на 10 минут", b: "Всегда приходить на 20 минут раньше" }, en: { a: "Always be 10 minutes late", b: "Always be 20 minutes early" } },
  { ru: { a: "Говорить на всех языках мира", b: "Разговаривать с животными" }, en: { a: "Speak every human language", b: "Talk to animals" } },
  { ru: { a: "Никогда больше не есть сладкое", b: "Никогда больше не есть фастфуд" }, en: { a: "Never eat sweets again", b: "Never eat fast food again" } },
  { ru: { a: "Жить в горах", b: "Жить у моря" }, en: { a: "Live in the mountains", b: "Live by the sea" } },
  { ru: { a: "Путешествовать в прошлое", b: "Путешествовать в будущее" }, en: { a: "Travel to the past", b: "Travel to the future" } },
  { ru: { a: "Иметь личного повара", b: "Иметь личного водителя" }, en: { a: "Have a personal chef", b: "Have a personal driver" } },
  { ru: { a: "Всю жизнь носить только чёрное", b: "Всю жизнь носить только яркое" }, en: { a: "Wear only black forever", b: "Wear only bright colors forever" } },
  { ru: { a: "Знать дату своей смерти", b: "Знать причину своей смерти" }, en: { a: "Know the date of your death", b: "Know the cause of your death" } },
  { ru: { a: "Быть самым умным в комнате", b: "Быть самым смешным в комнате" }, en: { a: "Be the smartest person in the room", b: "Be the funniest person in the room" } },
  { ru: { a: "Каждый день петь вместо того, чтобы говорить", b: "Каждый день танцевать вместо того, чтобы ходить" }, en: { a: "Sing instead of speaking every day", b: "Dance instead of walking every day" } },
  { ru: { a: "Остаться без телефона на месяц", b: "Остаться без интернета на месяц" }, en: { a: "Go a month without your phone", b: "Go a month without the internet" } },
  { ru: { a: "Жить в огромном городе", b: "Жить в маленькой деревне" }, en: { a: "Live in a huge city", b: "Live in a tiny village" } },
  { ru: { a: "Иметь суперпамять", b: "Иметь супер-скорость чтения" }, en: { a: "Have a perfect memory", b: "Read at superhuman speed" } },
  { ru: { a: "Всегда говорить правду", b: "Всегда уметь убедительно врать" }, en: { a: "Always tell the truth", b: "Always be able to lie convincingly" } },
  { ru: { a: "Выиграть миллион завтра", b: "Получать зарплату в два раза больше всю жизнь" }, en: { a: "Win a million tomorrow", b: "Earn double your salary for life" } },
  { ru: { a: "Никогда не болеть", b: "Никогда не уставать" }, en: { a: "Never get sick", b: "Never get tired" } },
  { ru: { a: "Иметь кнопку паузы для жизни", b: "Иметь кнопку перемотки назад" }, en: { a: "Have a pause button for life", b: "Have a rewind button for life" } },
  { ru: { a: "Жить без кофе", b: "Жить без чая" }, en: { a: "Live without coffee", b: "Live without tea" } },
  { ru: { a: "Отпуск на пляже", b: "Отпуск в горах" }, en: { a: "Beach vacation", b: "Mountain vacation" } },
  { ru: { a: "Уметь читать мысли", b: "Уметь видеть будущее" }, en: { a: "Read minds", b: "See the future" } },
  { ru: { a: "Всегда быть немного голодным", b: "Всегда быть немного сонным" }, en: { a: "Always be a little hungry", b: "Always be a little sleepy" } },
  { ru: { a: "Жить в мире без зимы", b: "Жить в мире без лета" }, en: { a: "Live in a world without winter", b: "Live in a world without summer" } },
  { ru: { a: "Иметь дракона", b: "Быть драконом" }, en: { a: "Own a dragon", b: "Be a dragon" } },
  { ru: { a: "Выступить на сцене перед тысячей людей", b: "Спеть в караоке перед бывшими одноклассниками" }, en: { a: "Perform on stage for a thousand people", b: "Sing karaoke in front of your old classmates" } },
  { ru: { a: "Спать только 4 часа, но высыпаться", b: "Спать 12 часов и всё равно быть бодрым" }, en: { a: "Sleep 4 hours and feel rested", b: "Sleep 12 hours and still feel great" } },
  { ru: { a: "Никогда не стоять в очередях", b: "Никогда не стоять в пробках" }, en: { a: "Never wait in a queue", b: "Never sit in traffic" } },
  { ru: { a: "Жить в доме на дереве", b: "Жить в плавучем доме" }, en: { a: "Live in a treehouse", b: "Live in a houseboat" } },
  { ru: { a: "Есть только пиццу всю жизнь", b: "Есть только плов всю жизнь" }, en: { a: "Eat only pizza forever", b: "Eat only pilaf forever" } },
  { ru: { a: "Уметь телепортироваться", b: "Уметь останавливать время" }, en: { a: "Teleport anywhere", b: "Stop time" } },
  { ru: { a: "Быть знаменитым", b: "Быть очень богатым, но никому не известным" }, en: { a: "Be famous", b: "Be very rich but unknown" } },
  { ru: { a: "Работать из дома всегда", b: "Работать в офисе с лучшими друзьями" }, en: { a: "Always work from home", b: "Work in an office with your best friends" } },
  { ru: { a: "Иметь бесконечный запас билетов на концерты", b: "Иметь бесконечный запас авиабилетов" }, en: { a: "Have unlimited concert tickets", b: "Have unlimited plane tickets" } },
  { ru: { a: "Жить на Луне", b: "Жить на дне океана" }, en: { a: "Live on the Moon", b: "Live on the ocean floor" } },
  { ru: { a: "Пойти на свидание с героем любимого фильма", b: "Пойти в поход с героем любимой книги" }, en: { a: "Go on a date with a movie hero", b: "Go camping with a book hero" } },
  { ru: { a: "Знать все сплетни города", b: "Чтобы о тебе никогда не сплетничали" }, en: { a: "Know all the city's gossip", b: "Never be gossiped about" } },
  { ru: { a: "Всегда выигрывать в настолки", b: "Всегда выигрывать в споры" }, en: { a: "Always win board games", b: "Always win arguments" } },
  { ru: { a: "Перестать чувствовать холод", b: "Перестать чувствовать жару" }, en: { a: "Never feel cold", b: "Never feel heat" } },
  { ru: { a: "Уметь играть на любом инструменте", b: "Уметь танцевать любой танец" }, en: { a: "Play any instrument", b: "Dance any dance" } },
  { ru: { a: "Прожить год без выходных", b: "Прожить год без отпуска, но с длинными выходными" }, en: { a: "A year with no weekends", b: "A year with no vacation but long weekends" } },
  { ru: { a: "Иметь рост 2 метра", b: "Иметь рост 1,5 метра" }, en: { a: "Be 2 meters tall", b: "Be 1.5 meters tall" } },
  { ru: { a: "Никогда не пользоваться лифтом", b: "Никогда не пользоваться такси" }, en: { a: "Never use an elevator", b: "Never use a taxi" } },
  { ru: { a: "Дружить с единорогом", b: "Дружить с говорящим котом" }, en: { a: "Befriend a unicorn", b: "Befriend a talking cat" } },
  { ru: { a: "Пережить зомби-апокалипсис", b: "Пережить нашествие инопланетян" }, en: { a: "Survive a zombie apocalypse", b: "Survive an alien invasion" } },
  { ru: { a: "Жить в эпоху динозавров", b: "Жить в эпоху рыцарей" }, en: { a: "Live with the dinosaurs", b: "Live with the knights" } },
  { ru: { a: "Иметь хвост", b: "Иметь крылья, которые не умеют летать" }, en: { a: "Have a tail", b: "Have wings that cannot fly" } },
  { ru: { a: "Проснуться знаменитым блогером", b: "Проснуться лучшим поваром страны" }, en: { a: "Wake up a famous blogger", b: "Wake up the best chef in the country" } },
  { ru: { a: "Всегда носить костюм", b: "Всегда носить пижаму" }, en: { a: "Always wear a suit", b: "Always wear pajamas" } },
  { ru: { a: "Уметь дышать под водой", b: "Уметь видеть в темноте" }, en: { a: "Breathe underwater", b: "See in the dark" } },
  { ru: { a: "Жить без соцсетей", b: "Жить без стриминговых сервисов" }, en: { a: "Live without social media", b: "Live without streaming services" } },
  { ru: { a: "Читать только одну книгу всю жизнь", b: "Смотреть только один фильм всю жизнь" }, en: { a: "Read one book forever", b: "Watch one movie forever" } },
  { ru: { a: "Съесть живого червяка", b: "Три дня не мыться" }, en: { a: "Eat a live worm", b: "Skip showering for three days" } },
  { ru: { a: "Выучить любой навык за день", b: "Прожить на 20 лет дольше" }, en: { a: "Learn any skill in a day", b: "Live 20 years longer" } },
  { ru: { a: "Каждое утро начинать с холодного душа", b: "Каждый вечер заканчивать уборкой" }, en: { a: "Start every morning with a cold shower", b: "End every evening cleaning" } },
  { ru: { a: "Иметь фотографическую память", b: "Уметь забывать неприятное по желанию" }, en: { a: "Have a photographic memory", b: "Forget bad memories at will" } },
  { ru: { a: "Жить в фильме ужасов", b: "Жить в мюзикле" }, en: { a: "Live in a horror movie", b: "Live in a musical" } },
  { ru: { a: "Путешествовать только поездом", b: "Путешествовать только автостопом" }, en: { a: "Travel only by train", b: "Travel only by hitchhiking" } },
  { ru: { a: "Говорить всё, что думаешь", b: "Никогда больше не говорить" }, en: { a: "Say everything you think", b: "Never speak again" } },
  { ru: { a: "Получить кнопку мгновенной уборки", b: "Получить кнопку мгновенной готовки" }, en: { a: "A button that cleans the house", b: "A button that cooks dinner" } },
  { ru: { a: "Всегда знать, где север", b: "Всегда знать, который час" }, en: { a: "Always know where north is", b: "Always know the time" } },
  { ru: { a: "Быть лучшим в мире в игре, которую никто не знает", b: "Быть средним в самой популярной игре" }, en: { a: "Be world champion in an unknown game", b: "Be average at the most popular game" } },
  { ru: { a: "Иметь личного стилиста", b: "Иметь личного тренера" }, en: { a: "Have a personal stylist", b: "Have a personal trainer" } },
  { ru: { a: "Жить без сыра", b: "Жить без шоколада" }, en: { a: "Live without cheese", b: "Live without chocolate" } },
  { ru: { a: "Гулять под дождём без зонта", b: "Сидеть у камина в метель" }, en: { a: "Walk in the rain without an umbrella", b: "Sit by the fire during a blizzard" } },
  { ru: { a: "Встретить инопланетянина", b: "Встретить себя из будущего" }, en: { a: "Meet an alien", b: "Meet your future self" } },
  { ru: { a: "Стать президентом на один день", b: "Стать невидимкой на один день" }, en: { a: "Be president for a day", b: "Be invisible for a day" } },
  { ru: { a: "Отмечать день рождения каждый месяц", b: "Отмечать Новый год каждую неделю" }, en: { a: "Celebrate your birthday every month", b: "Celebrate New Year every week" } },
  { ru: { a: "Смеяться над каждой шуткой", b: "Никогда не смеяться вслух" }, en: { a: "Laugh at every joke", b: "Never laugh out loud" } },
  { ru: { a: "Всегда петь в душе на весь дом", b: "Всегда танцевать, когда слышишь музыку" }, en: { a: "Always sing loudly in the shower", b: "Always dance when you hear music" } },
  { ru: { a: "Выбирать фильм для всей компании", b: "Выбирать еду для всей компании" }, en: { a: "Pick the movie for the group", b: "Pick the food for the group" } },
  { ru: { a: "Иметь бесплатное такси навсегда", b: "Иметь бесплатную доставку еды навсегда" }, en: { a: "Free taxi rides forever", b: "Free food delivery forever" } },
  { ru: { a: "Жить в Алматы с видом на горы", b: "Жить в Астане с видом на Байтерек" }, en: { a: "Live in Almaty with a mountain view", b: "Live in Astana with a Baiterek view" } },
  { ru: { a: "Никогда не опаздывать на самолёт", b: "Никогда не терять багаж" }, en: { a: "Never miss a flight", b: "Never lose your luggage" } },
  { ru: { a: "Прочитать чужие переписки", b: "Чтобы все прочитали твои" }, en: { a: "Read everyone's messages", b: "Have everyone read yours" } },
  { ru: { a: "Иметь бесконечные деньги на еду", b: "Иметь бесконечные деньги на одежду" }, en: { a: "Unlimited money for food", b: "Unlimited money for clothes" } },
  { ru: { a: "Жить в квартире без окон", b: "Жить в квартире без дверей" }, en: { a: "Live in a flat with no windows", b: "Live in a flat with no doors" } },
  { ru: { a: "Уметь исправлять любые ошибки в речи", b: "Уметь мгновенно придумывать шутки" }, en: { a: "Instantly fix any grammar", b: "Instantly come up with jokes" } },
  { ru: { a: "Быть капитаном пиратского корабля", b: "Быть командиром космической станции" }, en: { a: "Captain a pirate ship", b: "Command a space station" } },
  { ru: { a: "Спать в палатке неделю", b: "Спать в аэропорту одну ночь" }, en: { a: "Sleep in a tent for a week", b: "Sleep in an airport for a night" } },
  { ru: { a: "Всегда говорить стихами", b: "Всегда говорить шёпотом" }, en: { a: "Always speak in rhymes", b: "Always whisper" } },
  { ru: { a: "Поменяться жизнью с котом", b: "Поменяться жизнью с начальником" }, en: { a: "Swap lives with a cat", b: "Swap lives with your boss" } },
  { ru: { a: "Иметь идеальный голос", b: "Иметь идеальную память на лица" }, en: { a: "Have a perfect singing voice", b: "Never forget a face" } },
  { ru: { a: "Проводить все выходные на даче", b: "Проводить все выходные в торговом центре" }, en: { a: "Every weekend at a country house", b: "Every weekend at a mall" } },
  { ru: { a: "Готовить для всех гостей", b: "Мыть посуду после всех гостей" }, en: { a: "Cook for all the guests", b: "Wash dishes after all the guests" } },
  { ru: { a: "Никогда не стареть внешне", b: "Никогда не стареть душой" }, en: { a: "Never age on the outside", b: "Never age on the inside" } },
  { ru: { a: "Жить в мире, где все поют", b: "Жить в мире, где все молчат" }, en: { a: "A world where everyone sings", b: "A world where everyone is silent" } },
  { ru: { a: "Уметь готовить любое блюдо", b: "Уметь чинить любую технику" }, en: { a: "Cook any dish", b: "Fix any gadget" } },
  { ru: { a: "Выиграть Олимпиаду", b: "Получить Оскар" }, en: { a: "Win an Olympic gold", b: "Win an Oscar" } },
  { ru: { a: "Жить без холодильника", b: "Жить без стиральной машины" }, en: { a: "Live without a fridge", b: "Live without a washing machine" } },
  { ru: { a: "Каждый день новая прическа", b: "Одна причёска на всю жизнь" }, en: { a: "A new hairstyle every day", b: "One hairstyle for life" } },
  { ru: { a: "Отправиться в кругосветку на яхте", b: "Отправиться в кругосветку на мотоцикле" }, en: { a: "Sail around the world", b: "Ride around the world on a motorbike" } },
  { ru: { a: "Потерять кошелёк", b: "Потерять телефон" }, en: { a: "Lose your wallet", b: "Lose your phone" } },
  { ru: { a: "Иметь говорящую машину", b: "Иметь летающую машину, которая молчит" }, en: { a: "Own a talking car", b: "Own a silent flying car" } },
  { ru: { a: "Устроить вечеринку на 100 человек", b: "Устроить ужин на 6 лучших друзей" }, en: { a: "Throw a party for 100 people", b: "Host dinner for your 6 best friends" } },
  { ru: { a: "Никогда не видеть снег", b: "Никогда не видеть море" }, en: { a: "Never see snow", b: "Never see the sea" } },
  { ru: { a: "Чувствовать чужие эмоции", b: "Скрывать свои эмоции идеально" }, en: { a: "Feel other people's emotions", b: "Hide your own emotions perfectly" } },
  { ru: { a: "Быть героем мема", b: "Быть героем песни" }, en: { a: "Become a meme", b: "Become the subject of a song" } },
  { ru: { a: "Вернуться в детство на день", b: "Заглянуть в старость на день" }, en: { a: "Go back to childhood for a day", b: "Visit your old age for a day" } },
  { ru: { a: "Есть острое каждый день", b: "Не есть ничего острого никогда" }, en: { a: "Eat spicy food every day", b: "Never eat spicy food" } },
  { ru: { a: "Жить в сказке", b: "Жить в фантастике" }, en: { a: "Live in a fairy tale", b: "Live in science fiction" } },
  { ru: { a: "Уметь уговорить кого угодно", b: "Уметь найти что угодно" }, en: { a: "Persuade anyone", b: "Find anything" } },
  { ru: { a: "Работать 4 дня по 10 часов", b: "Работать 6 дней по 6 часов" }, en: { a: "Work four 10-hour days", b: "Work six 6-hour days" } },
  { ru: { a: "Иметь лучший вид из окна", b: "Иметь лучших соседей" }, en: { a: "Have the best view", b: "Have the best neighbors" } },
  { ru: { a: "Всю жизнь ездить на велосипеде", b: "Всю жизнь ходить пешком" }, en: { a: "Cycle everywhere forever", b: "Walk everywhere forever" } },
  { ru: { a: "Прыгнуть с парашютом", b: "Нырнуть с акулами" }, en: { a: "Go skydiving", b: "Dive with sharks" } },
  { ru: { a: "Отказаться от сахара", b: "Отказаться от соли" }, en: { a: "Give up sugar", b: "Give up salt" } },
  { ru: { a: "Иметь брата-близнеца", b: "Иметь клона, который работает вместо тебя" }, en: { a: "Have a twin", b: "Have a clone who works for you" } },
  { ru: { a: "Знать все языки программирования", b: "Знать все языки мира" }, en: { a: "Know every programming language", b: "Know every human language" } },
  { ru: { a: "Встречать рассветы", b: "Провожать закаты" }, en: { a: "Watch every sunrise", b: "Watch every sunset" } },
  { ru: { a: "Быть лучшим другом знаменитости", b: "Быть знаменитостью без друзей" }, en: { a: "Be a celebrity's best friend", b: "Be a celebrity with no friends" } },
  { ru: { a: "Жить без зеркал", b: "Жить без фотографий" }, en: { a: "Live without mirrors", b: "Live without photos" } },
  { ru: { a: "Всегда угадывать погоду", b: "Всегда угадывать счёт матча" }, en: { a: "Always predict the weather", b: "Always predict match scores" } },
  { ru: { a: "Пройти квест из 10 комнат", b: "Прочитать детектив за ночь" }, en: { a: "Beat a 10-room escape game", b: "Finish a mystery novel overnight" } },
  { ru: { a: "Ходить в гости каждый день", b: "Принимать гостей каждый день" }, en: { a: "Visit friends every day", b: "Host friends every day" } },
  { ru: { a: "Уметь рисовать как Ван Гог", b: "Уметь писать как Толстой" }, en: { a: "Paint like Van Gogh", b: "Write like Tolstoy" } },
  { ru: { a: "Никогда не терять вещи", b: "Всегда находить потерянное за минуту" }, en: { a: "Never lose things", b: "Always find lost things in a minute" } },
  { ru: { a: "Спать с открытым окном зимой", b: "Спать без кондиционера летом" }, en: { a: "Sleep with the window open in winter", b: "Sleep without AC in summer" } },
];
