INSERT INTO cosmetics_catalogue (type, slug, name_ru, name_en, value, image_url, sort_order) VALUES
  ('cover', 'lime', 'Лайм', 'Lime', 'lime', '/cosmetics/covers/lime.svg', 0),
  ('cover', 'beta', 'Бета', 'Beta', 'beta', '/cosmetics/covers/beta.svg', 1),
  ('cover', 'midnight', 'Полночь', 'Midnight', 'midnight', '/cosmetics/covers/midnight.svg', 2),
  ('cover', 'sunset', 'Закат', 'Sunset', 'sunset', '/cosmetics/covers/sunset.svg', 3),
  ('cover', 'ocean', 'Океан', 'Ocean', 'ocean', '/cosmetics/covers/ocean.svg', 4),
  ('cover', 'forest', 'Лес', 'Forest', 'forest', '/cosmetics/covers/forest.svg', 5),
  ('cover', 'nebula', 'Туманность', 'Nebula', 'nebula', '/cosmetics/covers/nebula.svg', 6),
  ('cover', 'cosmos', 'Космос', 'Cosmos', 'cosmos', '/cosmetics/covers/cosmos.svg', 7),
  ('cover', 'retro', 'Ретро', 'Retro', 'retro', '/cosmetics/covers/retro.svg', 8),
  ('cover', 'gold', 'Золото', 'Gold', 'gold', '/cosmetics/covers/gold.svg', 9),
  ('avatarFrame', 'none', 'Нет', 'None', 'none', '/cosmetics/frames/none.svg', 0),
  ('avatarFrame', 'lime', 'Лайм', 'Lime', 'lime', '/cosmetics/frames/lime.svg', 1),
  ('avatarFrame', 'pink', 'Розовый', 'Pink', 'pink', '/cosmetics/frames/pink.svg', 2),
  ('avatarFrame', 'blue', 'Синий', 'Blue', 'blue', '/cosmetics/frames/blue.svg', 3),
  ('avatarFrame', 'neon', 'Неон', 'Neon', 'neon', '/cosmetics/frames/neon.svg', 4),
  ('avatarFrame', 'rainbow', 'Радуга', 'Rainbow', 'rainbow', '/cosmetics/frames/rainbow.svg', 5),
  ('avatarFrame', 'gold', 'Золото', 'Gold', 'gold', '/cosmetics/frames/gold.svg', 6),
  ('avatarFrame', 'crystal', 'Кристалл', 'Crystal', 'crystal', '/cosmetics/frames/crystal.svg', 7),
  ('avatarFrame', 'inferno', 'Инферно', 'Inferno', 'inferno', '/cosmetics/frames/inferno.svg', 8),
  ('avatarFrame', 'frost', 'Мороз', 'Frost', 'frost', '/cosmetics/frames/frost.svg', 9),
  ('chatEffect', 'none', 'Нет', 'None', 'none', '/cosmetics/chat-effects/none.svg', 0),
  ('chatEffect', 'sparkle', 'Искры', 'Sparkle', 'sparkle', '/cosmetics/chat-effects/sparkle.svg', 1),
  ('chatEffect', 'glow', 'Свечение', 'Glow', 'glow', '/cosmetics/chat-effects/glow.svg', 2),
  ('chatEffect', 'rainbow', 'Радуга', 'Rainbow', 'rainbow', '/cosmetics/chat-effects/rainbow.svg', 3),
  ('chatEffect', 'matrix', 'Матрица', 'Matrix', 'matrix', '/cosmetics/chat-effects/matrix.svg', 4),
  ('chatEffect', 'fire', 'Огонь', 'Fire', 'fire', '/cosmetics/chat-effects/fire.svg', 5),
  ('chatEffect', 'ice', 'Лёд', 'Ice', 'ice', '/cosmetics/chat-effects/ice.svg', 6),
  ('chatEffect', 'lightning', 'Молния', 'Lightning', 'lightning', '/cosmetics/chat-effects/lightning.svg', 7),
  ('chatEffect', 'heart', 'Сердце', 'Heart', 'heart', '/cosmetics/chat-effects/heart.svg', 8),
  ('chatEffect', 'star', 'Звезда', 'Star', 'star', '/cosmetics/chat-effects/star.svg', 9),
  ('chatBackground', 'paper', 'Бумага', 'Paper', 'paper', '/cosmetics/chat-backgrounds/paper.svg', 0),
  ('chatBackground', 'midnight', 'Полночь', 'Midnight', 'midnight', '/cosmetics/chat-backgrounds/midnight.svg', 1),
  ('chatBackground', 'candy', 'Конфетти', 'Candy', 'candy', '/cosmetics/chat-backgrounds/candy.svg', 2),
  ('chatBackground', 'neon', 'Неон', 'Neon', 'neon', '/cosmetics/chat-backgrounds/neon.svg', 3),
  ('nameColor', 'black', 'Чёрный', 'Black', '#000000', '/cosmetics/name-colors/black.svg', 0),
  ('nameColor', 'lime', 'Лаймовый', 'Lime', '#c9ff05', '/cosmetics/name-colors/lime.svg', 1),
  ('nameColor', 'pink', 'Розовый', 'Pink', '#ff1791', '/cosmetics/name-colors/pink.svg', 2),
  ('nameColor', 'blue', 'Синий', 'Blue', '#2196f3', '/cosmetics/name-colors/blue.svg', 3),
  ('nameColor', 'neon', 'Неоновый', 'Neon', '#b829ff', '/cosmetics/name-colors/neon.svg', 4),
  ('nameColor', 'red', 'Красный', 'Red', '#f44336', '/cosmetics/name-colors/red.svg', 5),
  ('nameColor', 'orange', 'Оранжевый', 'Orange', '#ff9800', '/cosmetics/name-colors/orange.svg', 6),
  ('nameColor', 'teal', 'Бирюзовый', 'Teal', '#009688', '/cosmetics/name-colors/teal.svg', 7),
  ('nameColor', 'white', 'Белый', 'White', '#ffffff', '/cosmetics/name-colors/white.svg', 8),
  ('nameColor', 'cream', 'Кремовый', 'Cream', '#f7f7f2', '/cosmetics/name-colors/cream.svg', 9),
  ('badge', 'newcomer', 'Новичок', 'Newcomer', 'newcomer', '/cosmetics/badges/newcomer.svg', 0),
  ('badge', 'veteran', 'Ветеран', 'Veteran', 'veteran', '/cosmetics/badges/veteran.svg', 1),
  ('badge', 'legend', 'Легенда', 'Legend', 'legend', '/cosmetics/badges/legend.svg', 2),
  ('badge', 'party_king', 'Король вечеринок', 'Party King', 'party_king', '/cosmetics/badges/party_king.svg', 3),
  ('badge', 'game_master', 'Мастер игр', 'Game Master', 'game_master', '/cosmetics/badges/game_master.svg', 4),
  ('badge', 'social_butterfly', 'Социальная бабочка', 'Social Butterfly', 'social_butterfly', '/cosmetics/badges/social_butterfly.svg', 5),
  ('badge', 'early_adopter', 'Первопроходец', 'Early Adopter', 'early_adopter', '/cosmetics/badges/early_adopter.svg', 6),
  ('badge', 'night_owl', 'Ночная сова', 'Night Owl', 'night_owl', '/cosmetics/badges/night_owl.svg', 7),
  ('badge', 'trivia_champ', 'Чемпион викторин', 'Trivia Champ', 'trivia_champ', '/cosmetics/badges/trivia_champ.svg', 8),
  ('badge', 'vibe_curator', 'Куратор вайба', 'Vibe Curator', 'vibe_curator', '/cosmetics/badges/vibe_curator.svg', 9),
  ('badge', 'animated_pulse', 'Пульсирующий', 'Pulse', 'animated_pulse', '/cosmetics/badges/animated_pulse.svg', 10),
  ('badge', 'animated_glow', 'Свечение', 'Glow', 'animated_glow', '/cosmetics/badges/animated_glow.svg', 11),
  ('badge', 'animated_shimmer', 'Мерцание', 'Shimmer', 'animated_shimmer', '/cosmetics/badges/animated_shimmer.svg', 12),
  ('badge', 'animated_rotate', 'Вращение', 'Spin', 'animated_rotate', '/cosmetics/badges/animated_rotate.svg', 13),
  ('badge', 'animated_bounce', 'Подпрыгивающий', 'Bounce', 'animated_bounce', '/cosmetics/badges/animated_bounce.svg', 14),
  ('cover', 'animated_wave', 'Волна', 'Wave', 'animated_wave', '/cosmetics/covers/animated_wave.svg', 10),
  ('cover', 'animated_aurora', 'Аврора', 'Aurora', 'animated_aurora', '/cosmetics/covers/animated_aurora.svg', 11),
  ('cover', 'animated_fireflies', 'Светлячки', 'Fireflies', 'animated_fireflies', '/cosmetics/covers/animated_fireflies.svg', 12),
  ('cover', 'animated_storm', 'Гроза', 'Storm', 'animated_storm', '/cosmetics/covers/animated_storm.svg', 13),
  ('cover', 'animated_rainbow', 'Радуга', 'Rainbow', 'animated_rainbow', '/cosmetics/covers/animated_rainbow.svg', 14),
  ('avatarFrame', 'animated_pulse', 'Пульсирующая', 'Pulse', 'animated_pulse', '/cosmetics/frames/animated_pulse.svg', 10),
  ('avatarFrame', 'animated_glow', 'Светящаяся', 'Glow', 'animated_glow', '/cosmetics/frames/animated_glow.svg', 11),
  ('avatarFrame', 'animated_rotate', 'Вращающаяся', 'Rotate', 'animated_rotate', '/cosmetics/frames/animated_rotate.svg', 12),
  ('avatarFrame', 'animated_chrome', 'Хром', 'Chrome', 'animated_chrome', '/cosmetics/frames/animated_chrome.svg', 13),
  ('avatarFrame', 'animated_neon_pulse', 'Неон-пульс', 'Neon Pulse', 'animated_neon_pulse', '/cosmetics/frames/animated_neon_pulse.svg', 14),
  ('chatEffect', 'animated_confetti', 'Конфетти', 'Confetti', 'animated_confetti', '/cosmetics/chat-effects/animated_confetti.svg', 10),
  ('chatEffect', 'animated_rain', 'Дождь', 'Rain', 'animated_rain', '/cosmetics/chat-effects/animated_rain.svg', 11),
  ('chatEffect', 'animated_bubbles', 'Пузырьки', 'Bubbles', 'animated_bubbles', '/cosmetics/chat-effects/animated_bubbles.svg', 12),
  ('chatEffect', 'animated_rings', 'Кольца', 'Rings', 'animated_rings', '/cosmetics/chat-effects/animated_rings.svg', 13),
  ('chatEffect', 'animated_comet', 'Комета', 'Comet', 'animated_comet', '/cosmetics/chat-effects/animated_comet.svg', 14),
  ('nameColor', 'animated_cycle', 'Цикл', 'Cycle', 'animated_cycle', '/cosmetics/name-colors/animated_cycle.svg', 10),
  ('nameColor', 'animated_gradient', 'Градиент', 'Gradient', 'animated_gradient', '/cosmetics/name-colors/animated_gradient.svg', 11),
  ('nameColor', 'animated_pulse', 'Пульс', 'Pulse', 'animated_pulse', '/cosmetics/name-colors/animated_pulse.svg', 12),
  ('nameColor', 'animated_shift', 'Сдвиг', 'Shift', 'animated_shift', '/cosmetics/name-colors/animated_shift.svg', 13),
  ('nameColor', 'animated_neon', 'Неон', 'Neon', 'animated_neon', '/cosmetics/name-colors/animated_neon.svg', 14)
ON CONFLICT (type, slug) DO NOTHING;
--> statement-breakpoint
INSERT INTO social_quests (id, title_key, desc_key, icon, requirements, reward_koins, reward_xp) VALUES
  ('hostparty', 'questHostParty', 'questDescHostParty', 'celebration', '{"minPlayers":4}'::jsonb, 50, 100),
  ('playgames', 'questPlayGames', 'questDescPlayGames', 'sports_esports', '{"minGames":3}'::jsonb, 30, 60),
  ('winrounds', 'questWinRounds', 'questDescWinRounds', 'emoji_events', '{"wins":5}'::jsonb, 40, 80),
  ('thankothers', 'questThankOthers', 'questDescThankOthers', 'favorite', '{"tips":3}'::jsonb, 20, 40)
ON CONFLICT (id) DO NOTHING;
