"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";
import { useLocale } from "@/app/components/LocaleProvider";
import LocaleToggle from "@/app/components/LocaleToggle";

export default function AdminLoginForm({ initialError = "", mfaRequired = false }: { initialError?: string; mfaRequired?: boolean }) {
  const [error, setError] = useState(initialError); const [loading, setLoading] = useState(false); const { locale } = useLocale();
  const c = locale === "ru" ? { title: <>Админ<br /><span>доступ.</span></>, intro: "Вход только для команды. Заявки и контакты остаются внутри.", label: "Пароль администратора", checking: "Проверяем…", open: "Открыть реестр", failure: "Не удалось войти.", connection: "Не удалось проверить пароль." } : { title: <>Admin<br /><span>access.</span></>, intro: "Team only. Applications and contact data stay inside.", label: "Admin password", checking: "Checking…", open: "Open console", failure: "Couldn't sign in.", connection: "Couldn't verify the password." };
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const password = form.get("password"); const totp = form.get("totp"); setLoading(true); setError(""); try { const response = await fetch("/api/admin/auth", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ password, totp }) }); if (!response.ok) { const data = await response.json(); setError(data.error ?? c.failure); return; } window.location.assign("/admin"); } catch { setError(c.connection); } finally { setLoading(false); } }
  return <main className="admin-login-page"><section className="admin-login-card"><div className="admin-login-locale"><LocaleToggle /></div><span className="admin-kicker">TUSA.game · control room</span><h1>{c.title}</h1><p>{c.intro}</p><form onSubmit={submit} action="/api/admin/auth" method="post"><label><span>{c.label}</span><input name="password" type="password" autoComplete="current-password" required autoFocus /></label>{mfaRequired && <label><span>{locale === "ru" ? "Код из приложения" : "Authenticator code"}</span><input name="totp" type="text" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" minLength={6} maxLength={6} required /></label>}<button type="submit" className="admin-button admin-button--lime" disabled={loading}>{loading ? c.checking : c.open}</button></form><div className="admin-login-divider"><span>{locale === "ru" ? "или" : "or"}</span></div><Link className="admin-account-login" href="/sign-in?redirect_url=%2Fadmin">{locale === "ru" ? "Войти назначенным аккаунтом" : "Sign in with assigned account"}</Link>{error && <p className="admin-error" role="alert">{error}</p>}</section></main>;
}
