"use client";
import { useMemo, useState } from "react";
const pad = (n:number) => String(n).padStart(2, "0");
export default function EventDateTimeFields({ dateLabel, timeLabel, dateDefault = "", timeDefault = "" }: { dateLabel:string; timeLabel:string; dateDefault?:string; timeDefault?:string }) {
  const today = new Date(); const [month, setMonth] = useState(new Date(today.getFullYear(), today.getMonth(), 1)); const [date, setDate] = useState(dateDefault); const [time, setTime] = useState(timeDefault); const [open, setOpen] = useState<"date"|"time"|null>(null);
  const days = useMemo(() => { const offset=(month.getDay()+6)%7; const count=new Date(month.getFullYear(),month.getMonth()+1,0).getDate(); return Array.from({length:offset+count},(_,i)=>i<offset?null:i-offset+1); }, [month]);
  const stamp=(day:number)=>`${pad(day)}.${pad(month.getMonth()+1)}.${month.getFullYear()}`;
  return <div className="form-split event-datetime-fields"><label>{dateLabel}<button className={`event-picker-trigger ${open==="date"?"is-open":""}`} type="button" onClick={()=>setOpen(open==="date"?null:"date")}><span>{date||"ДД.ММ.ГГГГ"}</span><span className="material-symbols-rounded">calendar_month</span></button><input className="event-picker-hidden" name="date" value={date} onChange={e=>setDate(e.target.value)} required />{open==="date"&&<div className="event-picker-popover"><header><button type="button" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))}>‹</button><b>{new Intl.DateTimeFormat("ru",{month:"long",year:"numeric"}).format(month)}</b><button type="button" onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))}>›</button></header><div className="event-weekdays">{["Пн","Вт","Ср","Чт","Пт","Сб","Вс"].map(x=><span key={x}>{x}</span>)}</div><div className="event-calendar-days">{days.map((day,i)=>day?<button className={date===stamp(day)?"is-selected":""} key={day} onClick={()=>{setDate(stamp(day));setOpen(null);}} type="button">{day}</button>:<span key={i}/>)}</div></div>}</label><label>{timeLabel}<button className={`event-picker-trigger ${open==="time"?"is-open":""}`} type="button" onClick={()=>setOpen(open==="time"?null:"time")}><span>{time||"21:00"}</span><span className="material-symbols-rounded">schedule</span></button><input className="event-picker-hidden" name="time" value={time} onChange={e=>setTime(e.target.value)} required />{open==="time"&&<div className="event-picker-popover event-time-popover"><p>Выбери время</p><div>{[16,17,18,19,20,21,22,23].map(h=><button className={time.startsWith(`${pad(h)}:`)?"is-selected":""} key={h} onClick={()=>{setTime(`${pad(h)}:00`);setOpen(null);}} type="button">{pad(h)}:00</button>)}</div></div>}</label></div>;
}
