export const ALIAS_WORDS_EN: readonly string[] = [
  "fridge", "microwave", "vacuum cleaner", "iron", "sofa", "armchair", "stool", "pillow", "blanket", "bed sheet",
  "wardrobe", "dresser", "nightstand", "chandelier", "floor lamp", "carpet", "curtain", "windowsill", "radiator",
  "air conditioner", "fan", "kettle", "frying pan", "saucepan", "ladle", "colander", "grater", "rolling pin",
  "whisk", "meat grinder", "blender", "toaster", "coffee maker", "dishwasher", "washing machine", "dryer",
  "coat hanger", "clothespin", "ironing board", "mop", "broom", "dustpan", "bucket", "sponge", "towel", "bathrobe",
  "slippers", "mirror", "sink", "bathtub", "shower", "toilet", "faucet", "power socket", "light switch",
  "light bulb", "extension cord", "remote control", "lock", "key", "doorbell", "peephole", "doormat", "staircase",
  "balcony", "attic", "basement", "pantry", "hallway", "living room", "bedroom", "nursery", "kitchen", "fireplace",
  "chimney", "blinds", "alarm clock", "calendar", "photo frame", "vase", "candle", "piggy bank", "jewelry box",
  "first aid kit", "thermometer", "band-aid", "umbrella", "flashlight", "battery", "lighter", "matches",
  "garden hose", "lawn mower", "mailbox", "fence", "doghouse", "bunk bed", "hammock", "rocking chair", "bookshelf",
  "laundry basket", "borscht", "dumplings", "pancakes", "waffles", "omelette", "fried egg", "porridge", "oatmeal",
  "pilaf", "beshbarmak", "lagman", "manty", "samsa", "baursak", "kebab", "meatball", "sausage", "salami",
  "ham", "bacon", "sushi", "pizza", "burger", "hot dog", "taco", "burrito", "nachos", "lasagna", "spaghetti",
  "risotto", "ramen", "dim sum", "curry", "falafel", "hummus", "shawarma", "fish and chips", "french fries",
  "mashed potatoes", "salad", "sandwich", "toast", "croissant", "bagel", "baguette", "pretzel", "muffin",
  "cupcake", "donut", "brownie", "cookie", "cheesecake", "tiramisu", "ice cream", "popsicle", "chocolate bar",
  "candy", "lollipop", "gummy bear", "marshmallow", "cotton candy", "caramel", "jam", "honey", "peanut butter",
  "condensed milk", "cottage cheese", "sour cream", "yogurt", "butter", "cheese", "egg", "mayonnaise", "ketchup",
  "mustard", "salt", "pepper", "sugar", "cinnamon", "vanilla", "garlic", "onion", "carrot", "beetroot", "cabbage",
  "potato", "cucumber", "tomato", "eggplant", "zucchini", "pumpkin", "radish", "corn", "peas", "beans", "lentils",
  "rice", "pasta", "flour", "mushroom", "apple", "pear", "plum", "apricot", "peach", "cherry", "strawberry",
  "raspberry", "blueberry", "watermelon", "melon", "grapes", "banana", "orange", "tangerine", "lemon", "lime",
  "grapefruit", "pineapple", "mango", "kiwi", "avocado", "pomegranate", "fig", "date", "raisin", "walnut",
  "almond", "pistachio", "peanut", "sunflower seeds", "popcorn", "potato chips", "crackers", "pickle", "olive",
  "coconut", "broccoli", "cauliflower", "spinach", "celery", "lettuce", "chili pepper", "tea", "coffee",
  "cappuccino", "latte", "espresso", "hot chocolate", "lemonade", "soda", "mineral water", "orange juice",
  "smoothie", "milkshake", "iced tea", "energy drink", "kumis", "ayran", "bubble tea", "matcha", "mulled wine",
  "eggnog", "cat", "dog", "puppy", "kitten", "hamster", "guinea pig", "parrot", "canary", "turtle", "rabbit",
  "horse", "pony", "donkey", "camel", "cow", "bull", "calf", "goat", "sheep", "ram", "pig", "chicken", "rooster",
  "chick", "duck", "goose", "turkey", "swan", "stork", "heron", "flamingo", "peacock", "ostrich", "penguin",
  "eagle", "falcon", "golden eagle", "owl", "crow", "sparrow", "pigeon", "swallow", "woodpecker", "nightingale",
  "seagull", "pelican", "wolf", "fox", "bear", "squirrel", "hedgehog", "hare", "badger", "raccoon", "beaver",
  "mole", "mouse", "rat", "moose", "deer", "wild boar", "lynx", "tiger", "lion", "leopard", "cheetah", "panther",
  "jaguar", "snow leopard", "elephant", "rhino", "hippo", "giraffe", "zebra", "antelope", "kangaroo", "koala",
  "panda", "sloth", "monkey", "gorilla", "chimpanzee", "dolphin", "whale", "shark", "octopus", "squid", "jellyfish",
  "starfish", "crab", "shrimp", "lobster", "seal", "walrus", "otter", "crocodile", "lizard", "chameleon",
  "snake", "cobra", "frog", "toad", "snail", "worm", "butterfly", "bee", "wasp", "bumblebee", "ant", "mosquito",
  "fly", "dragonfly", "grasshopper", "ladybug", "spider", "scorpion", "moth", "firefly", "dinosaur", "dragon",
  "unicorn", "mermaid", "yeti", "bigfoot", "phoenix", "griffin", "sun", "moon", "star", "comet", "meteor",
  "planet", "galaxy", "constellation", "rainbow", "cloud", "thunderstorm", "lightning", "thunder", "rain",
  "downpour", "snow", "snowflake", "snowdrift", "blizzard", "hail", "fog", "dew", "frost", "icicle", "wind",
  "hurricane", "tornado", "earthquake", "volcano", "lava", "geyser", "waterfall", "river", "stream", "lake",
  "sea", "ocean", "bay", "island", "peninsula", "beach", "sand", "dune", "desert", "oasis", "steppe", "forest",
  "taiga", "jungle", "swamp", "meadow", "field", "mountain", "hill", "gorge", "cave", "cliff", "glacier",
  "iceberg", "canyon", "valley", "spring", "wave", "tide", "sunset", "sunrise", "full moon", "eclipse", "northern lights",
  "drought", "flood", "rock", "pebble", "seashell", "tree bark", "root", "branch", "leaf", "pine cone", "acorn",
  "dandelion", "daisy", "rose", "tulip", "sunflower", "cactus", "palm tree", "birch", "oak", "pine", "fir tree",
  "maple", "willow", "poplar", "apple tree", "moss", "fern", "nettle", "reed", "lily", "lotus", "orchid",
  "bamboo", "mushroom ring", "tumbleweed", "airport", "train station", "subway", "bus stop", "traffic light",
  "crosswalk", "intersection", "bridge", "tunnel", "embankment", "town square", "fountain", "monument", "museum",
  "theater", "cinema", "circus", "zoo", "water park", "amusement park", "Ferris wheel", "stadium", "swimming pool",
  "gym", "ice rink", "library", "school", "university", "kindergarten", "hospital", "pharmacy", "post office",
  "bank", "ATM", "market", "bazaar", "supermarket", "shopping mall", "boutique", "barbershop", "beauty salon",
  "laundromat", "car wash", "gas station", "parking lot", "garage", "construction site", "skyscraper", "apartment block",
  "dormitory", "hotel", "hostel", "restaurant", "cafe", "coffee shop", "canteen", "bar", "karaoke bar", "nightclub",
  "bowling alley", "pool hall", "bathhouse", "sauna", "fire station", "police station", "courthouse", "city hall",
  "embassy", "church", "mosque", "temple", "cemetery", "farm", "village", "summer cottage", "yurt", "tent",
  "lighthouse", "harbor", "pier", "castle", "palace", "fortress", "tower", "pyramid", "maze", "prison", "casino",
  "observatory", "planetarium", "botanical garden", "laboratory", "warehouse", "office", "coworking space",
  "food court", "rooftop", "playground", "Medeu", "Shymbulak", "Kok-Tobe", "Big Almaty Lake", "Charyn Canyon",
  "Kolsai Lakes", "Baiterek", "Khan Shatyr", "Green Bazaar", "dombra", "kobyz", "asyk", "kazy", "kurt", "dastarkhan",
  "Kazakh wedding", "kokpar", "eagle hunter", "Caspian Sea", "Lake Balkhash", "Tian Shan", "Astana", "Shymkent",
  "Burabay", "Turkestan", "aport apple", "tenge", "shanyrak", "Nauryz", "Nauryz kozhe", "car", "taxi", "bus",
  "trolleybus", "tram", "commuter train", "train", "airplane", "helicopter", "airship", "hot air balloon",
  "rocket", "spaceship", "submarine", "yacht", "motorboat", "rowboat", "kayak", "ferry", "cruise ship", "bicycle",
  "scooter", "electric scooter", "motorcycle", "moped", "quad bike", "skateboard", "roller skates", "ice skates",
  "skis", "snowboard", "sled", "tractor", "combine harvester", "excavator", "crane", "bulldozer", "truck",
  "tow truck", "ambulance", "fire truck", "police car", "limousine", "convertible", "SUV", "carriage", "cart",
  "cable car", "funicular", "escalator", "elevator", "GPS navigator", "steering wheel", "wheel", "tire",
  "trunk", "headlight", "windshield wiper", "seat belt", "parachute", "hang glider", "jet ski", "double-decker bus",
  "tuk-tuk", "monorail", "doctor", "dentist", "surgeon", "nurse", "vet", "teacher", "nanny", "professor",
  "student", "chef", "waiter", "bartender", "barista", "pastry chef", "baker", "shop assistant", "cashier",
  "courier", "taxi driver", "driver", "pilot", "flight attendant", "captain", "sailor", "astronaut", "astronomer",
  "scientist", "chemist", "physicist", "programmer", "designer", "architect", "builder", "electrician", "plumber",
  "carpenter", "painter", "gardener", "farmer", "shepherd", "fisherman", "hunter", "forest ranger", "firefighter",
  "police officer", "investigator", "detective", "lawyer", "judge", "notary", "accountant", "banker", "economist",
  "manager", "CEO", "secretary", "journalist", "blogger", "photographer", "camera operator", "film director",
  "actor", "singer", "musician", "DJ", "dancer", "artist", "sculptor", "writer", "poet", "translator", "librarian",
  "tour guide", "hairdresser", "makeup artist", "model", "stylist", "tailor", "shoemaker", "jeweler", "watchmaker",
  "locksmith", "mechanic", "miner", "blacksmith", "lifeguard", "coach", "athlete", "football player", "boxer",
  "chess player", "clown", "magician", "animal trainer", "acrobat", "mail carrier", "janitor", "security guard",
  "president", "minister", "mayor", "king", "queen", "prince", "princess", "knight", "pirate", "ninja", "samurai",
  "viking", "cowboy", "sheriff", "spy", "superhero", "wizard", "witch", "vampire", "zombie", "ghost", "robot",
  "alien", "mermaid prince", "genie", "football", "basketball", "volleyball", "hockey", "tennis", "table tennis",
  "badminton", "golf", "boxing", "wrestling", "judo", "karate", "taekwondo", "fencing", "archery", "swimming",
  "scuba diving", "surfing", "rowing", "sailing", "running", "marathon", "long jump", "pole vault", "javelin",
  "barbell", "dumbbells", "pull-up bar", "jump rope", "hula hoop", "yoga", "pilates", "aerobics", "chess",
  "checkers", "backgammon", "dominoes", "bingo", "poker", "Monopoly", "Mafia", "charades", "Twister", "Jenga",
  "jigsaw puzzle", "Rubik's cube", "battleship", "tic-tac-toe", "hide and seek", "tag", "blind man's buff",
  "hopscotch", "snowball fight", "snowman", "sledding", "swing", "carousel", "trampoline", "kite", "soap bubbles",
  "paper airplane", "slingshot", "pinball", "darts", "bowling", "billiards", "curling", "biathlon", "figure skating",
  "slalom", "ski jump", "rock climbing", "mountaineering", "rafting", "paragliding", "skydiving", "parkour",
  "esports", "escape room", "paintball", "laser tag", "go-kart", "Olympics", "championship", "penalty", "offside",
  "goal", "timeout", "whistle", "referee", "trophy", "medal", "podium", "mascot", "cheerleader", "relay race",
  "tug of war", "sack race", "arm wrestling", "frisbee", "T-shirt", "shirt", "blouse", "sweater", "hoodie",
  "jacket", "coat", "fur coat", "down jacket", "raincoat", "vest", "blazer", "suit", "tuxedo", "dress", "skirt",
  "trousers", "jeans", "shorts", "overalls", "pajamas", "swimsuit", "swim trunks", "socks", "tights", "gloves",
  "mittens", "scarf", "beanie", "cap", "panama hat", "top hat", "beret", "baseball cap", "fur hat", "hood",
  "necktie", "bow tie", "belt", "suspenders", "handbag", "backpack", "suitcase", "wallet", "glasses", "sunglasses",
  "wristwatch", "bracelet", "ring", "earrings", "necklace", "pendant", "brooch", "hair clip", "crown", "wedding veil",
  "sneakers", "sandals", "high heels", "boots", "flip-flops", "rain boots", "button", "zipper", "pocket",
  "collar", "sleeve", "shoelaces", "apron", "uniform", "onesie", "kimono", "sombrero", "cowboy hat", "bathrobe belt",
  "smartphone", "tablet", "laptop", "computer", "keyboard", "computer mouse", "monitor", "printer", "scanner",
  "headphones", "speaker", "microphone", "webcam", "USB stick", "charger", "power bank", "router", "Wi-Fi",
  "password", "like button", "repost", "story", "meme", "hashtag", "selfie", "emoji", "sticker", "voice message",
  "video call", "follower", "livestream", "podcast", "playlist", "app", "software update", "computer virus",
  "antivirus", "spam", "screenshot", "cloud storage", "neural network", "chatbot", "robot vacuum", "smart speaker",
  "drone", "virtual reality", "game console", "joystick", "television", "projector", "camera", "tripod",
  "e-reader", "fitness tracker", "smartwatch", "calculator", "Bluetooth", "QR code", "barcode", "geolocation",
  "ride-hailing app", "food delivery", "online store", "cryptocurrency", "life hack", "spoiler", "clickbait",
  "music video", "movie trailer", "TV series", "cartoon", "comic book", "anime", "video game", "influencer",
  "unboxing", "dark mode", "autocorrect", "group chat", "notification", "loading bar", "captcha", "cookie banner",
  "birthday", "New Year", "wedding", "graduation", "office party", "bachelorette party", "bachelor party",
  "house party", "disco", "karaoke battle", "picnic", "barbecue", "fireworks", "sparkler", "party popper",
  "confetti", "streamers", "garland", "balloon", "gift", "greeting card", "birthday cake", "wine glass",
  "champagne", "Father Frost", "Santa Claus", "Christmas ornament", "tinsel", "masquerade", "costume party",
  "dress code", "photo booth", "host", "dance floor", "slow dance", "flash mob", "contest", "raffle", "prize",
  "surprise party", "pajama party", "foam party", "pool party", "Halloween", "jack-o'-lantern", "valentine",
  "Mother's Day", "parade", "carnival", "festival", "concert", "stand-up comedy", "open mic", "afterparty",
  "piñata", "party hat", "gift wrap", "candle wish", "guest list", "dress rehearsal", "bonfire night", "trick or treat",
  "Easter egg", "gender reveal", "housewarming", "baby shower", "farewell party", "love", "friendship", "jealousy",
  "envy", "joy", "sadness", "boredom", "fear", "surprise", "laughter", "tears", "smile", "resentment", "inspiration",
  "laziness", "dream", "sleep", "nightmare", "deja vu", "intuition", "luck", "destiny", "mystery", "secret",
  "gossip", "compliment", "apology", "promise", "oath", "argument", "quarrel", "making up", "flirting", "kiss",
  "hug", "first love", "friend zone", "nostalgia", "shyness", "bravery", "patience", "stubbornness", "generosity",
  "greed", "pride", "modesty", "talent", "habit", "routine", "deadline", "procrastination", "burnout", "vacation",
  "day off", "Monday", "Friday", "salary", "bonus", "loan", "mortgage", "tax", "fine", "discount", "sale",
  "queue", "traffic jam", "being late", "weekend", "hangover", "FOMO", "small talk", "awkward silence", "inside joke",
  "plot twist", "guilty pleasure", "comfort zone", "midlife crisis", "beginner's luck", "white lie", "cold feet",
  "painting", "portrait", "landscape", "still life", "sculpture", "fresco", "graffiti", "mosaic", "stained glass",
  "gallery", "exhibition", "auction", "masterpiece", "easel", "paintbrush", "palette", "canvas", "watercolor",
  "crayon", "pencil", "eraser", "ruler", "compass", "marker", "coloring book", "origami", "collage", "clay",
  "pottery wheel", "knitting", "embroidery", "play", "ballet", "opera", "musical", "orchestra", "choir",
  "conductor", "grand piano", "guitar", "violin", "cello", "drum", "flute", "saxophone", "trumpet", "harp",
  "accordion", "harmonica", "synthesizer", "stage", "backstage", "curtain call", "applause", "encore", "autograph",
  "premiere", "red carpet", "film festival", "poetry slam", "street musician", "tattoo", "selfie stick",
  "statue", "bust", "mural", "sketchbook", "comic strip", "cartoonist", "puppet show", "ventriloquist", "mime",
  "ballerina", "tap dance", "breakdance", "tango", "waltz", "salsa", "hip-hop", "rock concert", "mosh pit",
  "vinyl record", "cassette tape", "jukebox", "gramophone", "lesson", "recess", "school bell", "homework",
  "test", "exam", "cheat sheet", "report card", "grade", "A plus", "notebook", "textbook", "pencil case",
  "schoolbag", "blackboard", "chalk", "pointer", "globe", "map", "atlas", "microscope", "telescope", "test tube",
  "flask", "periodic table", "fraction", "equation", "theorem", "triangle", "square", "circle", "cube", "sphere",
  "spiral", "diploma", "scholarship", "lecture", "seminar", "essay", "term paper", "yearbook", "first day of school",
  "prom", "principal", "detention", "PE class", "chemistry", "geography", "history", "literature", "math",
  "biology", "physics", "computer science", "spelling bee", "science fair", "field trip", "school bus", "locker",
  "cafeteria", "hall pass", "pop quiz", "valedictorian", "dean", "campus", "graduation cap", "Gingerbread Man",
  "Baba Yaga", "Snow White", "Cinderella", "Little Red Riding Hood", "Pinocchio", "Cheburashka", "Winnie the Pooh",
  "Masha and the Bear", "Shrek", "Mickey Mouse", "SpongeBob", "Spider-Man", "Batman", "Superman", "Hulk",
  "Iron Man", "Harry Potter", "Sherlock Holmes", "Dracula", "Frankenstein", "Robin Hood", "Aladdin", "genie lamp",
  "flying carpet", "magic wand", "invisibility cloak", "seven-league boots", "goldfish wish", "Aldar Kose",
  "Santa's sleigh", "Tooth Fairy", "Easter Bunny", "Grinch", "Tarzan", "Mowgli", "Peter Pan", "Mary Poppins",
  "Jack Sparrow", "Terminator", "Godzilla", "King Kong", "Darth Vader", "lightsaber", "Hogwarts", "Narnia",
  "Middle-earth", "the One Ring", "time machine", "teleporter", "philosopher's stone", "yellow brick road",
  "Wonderland", "Mad Hatter", "Cheshire Cat", "Tinker Bell", "Captain Hook", "Rapunzel", "Sleeping Beauty",
  "Beauty and the Beast", "Little Mermaid", "Frozen", "Olaf", "Pikachu", "Mario", "Sonic", "Pac-Man", "Tetris",
  "Minecraft", "Lego", "Barbie", "Ken", "Toy Story", "Buzz Lightyear", "Minions", "Kung Fu Panda", "Lion King",
  "Simba", "Nemo", "Dory", "Stitch", "Yoda", "Chewbacca", "James Bond", "Indiana Jones", "Rocky", "Titanic",
  "Jurassic Park", "Home Alone", "Mr. Bean", "sneezing", "yawning", "snoring", "winking", "clapping", "pinching",
  "tickling", "hugging", "dancing", "singing", "whistling", "whispering", "shouting", "laughing", "crying",
  "jumping", "crawling", "diving", "sliding", "falling", "tripping", "juggling", "taking photos", "drawing",
  "cooking", "frying", "boiling", "baking", "chopping", "washing dishes", "doing laundry", "ironing", "sweeping",
  "digging", "planting", "watering plants", "picking mushrooms", "fishing", "sunbathing", "traveling", "running late",
  "hurrying", "waiting", "searching", "hiding", "eavesdropping", "peeking", "gossiping", "bragging", "daydreaming",
  "falling in love", "getting married", "moving house", "renovating", "bargaining", "saving money", "spending money",
  "borrowing", "giving gifts", "thanking", "apologizing", "arguing", "making peace", "voting", "joking",
  "imitating", "cheering for a team", "taking a selfie", "stuck in traffic", "oversleeping", "losing keys",
  "going on a diet", "winning the lottery", "getting lost", "getting soaked", "catching a cold", "brushing teeth",
  "shaving", "doing makeup", "getting a haircut", "playing guitar", "going hiking", "making a campfire",
  "pitching a tent", "skiing", "building a snowman", "setting off fireworks", "sleepwalking", "parallel parking",
  "speed dating", "binge-watching", "online shopping", "job interview", "first day at work", "blind date",
  "road rage", "photobombing", "moonwalking", "air guitar", "high five", "fist bump", "group hug", "head",
  "forehead", "eyebrow", "eyelash", "eye", "ear", "nose", "cheek", "lips", "tooth", "tongue", "chin", "neck",
  "shoulder", "elbow", "palm", "finger", "fingernail", "knee", "heel", "belly", "back", "heart", "lungs",
  "stomach", "brain", "bone", "muscle", "blood", "pulse", "freckle", "wrinkle", "blister", "bruise", "scratch",
  "hiccups", "runny nose", "cough", "fever", "allergy", "vaccine", "injection", "pill", "vitamins", "cast",
  "crutches", "bandage", "X-ray", "filling", "braces", "eyeglasses", "contact lenses", "hearing aid", "dimples",
  "goosebumps", "sunburn", "belly button", "wisdom tooth", "six-pack", "double chin", "bad breath", "sore throat",
  "stopwatch", "hourglass", "compass needle", "treasure map", "treasure", "chest", "pirate flag", "anchor",
  "ship's wheel", "binoculars", "spyglass", "magnifying glass", "magnet", "gear", "nut", "bolt", "screwdriver",
  "hammer", "nail", "saw", "drill", "tape measure", "duct tape", "sticky tape", "glue", "stapler", "paper clip",
  "thumbtack", "envelope", "stamp", "parcel", "postcard", "souvenir", "fridge magnet", "keychain", "lucky charm",
  "amulet", "horseshoe", "four-leaf clover", "black cat", "broken mirror", "fortune telling", "horoscope",
  "zodiac sign", "crystal ball", "tarot cards", "magic trick", "illusion", "riddle", "crossword", "rebus",
  "brain teaser", "soap opera", "TV show", "reality show", "talk show", "weather forecast", "commercial",
  "billboard", "signboard", "poster", "ticket", "ticket inspector", "turnstile", "boarding pass", "passport",
  "visa", "customs", "rolling suitcase", "duty-free", "carry-on", "turbulence", "porthole", "all-inclusive hotel",
  "buffet", "sightseeing tour", "guidebook", "gift shop", "beach umbrella", "sunbed", "inflatable ring",
  "flippers", "snorkel", "sunscreen", "suntan", "holiday romance", "message in a bottle", "sandcastle", "time capsule",
  "wishing well", "lucky number", "jackpot", "piggyback ride", "lemonade stand", "garage sale", "flea market",
  "lost and found", "hide-and-seek champion",
];
