// Generated content bank. Edit the source lists, keep RU and EN aligned.
export type BunkerText = { ru: string; en: string };

export const BUNKER_PROFESSIONS: readonly BunkerText[] = [
  { ru: "врач-хирург", en: "surgeon" },
  { ru: "повар", en: "chef" },
  { ru: "инженер-электрик", en: "electrical engineer" },
  { ru: "агроном", en: "agronomist" },
  { ru: "учитель физики", en: "physics teacher" },
  { ru: "сантехник", en: "plumber" },
  { ru: "ветеринар", en: "veterinarian" },
  { ru: "пилот", en: "pilot" },
  { ru: "программист", en: "programmer" },
  { ru: "психолог", en: "psychologist" },
  { ru: "химик", en: "chemist" },
  { ru: "строитель", en: "builder" },
  { ru: "медсестра", en: "nurse" },
  { ru: "охотник", en: "hunter" },
  { ru: "пчеловод", en: "beekeeper" },
  { ru: "механик", en: "mechanic" },
  { ru: "радиолюбитель", en: "radio amateur" },
  { ru: "фармацевт", en: "pharmacist" },
  { ru: "геолог", en: "geologist" },
  { ru: "военный", en: "soldier" },
  { ru: "пожарный", en: "firefighter" },
  { ru: "швея", en: "seamstress" },
  { ru: "пекарь", en: "baker" },
  { ru: "блогер", en: "blogger" },
  { ru: "юрист", en: "lawyer" },
  { ru: "актёр", en: "actor" },
  { ru: "музыкант", en: "musician" },
  { ru: "альпинист", en: "mountaineer" },
  { ru: "биолог", en: "biologist" },
  { ru: "тренер по фитнесу", en: "fitness coach" },
  { ru: "священник", en: "priest" },
  { ru: "бухгалтер", en: "accountant" },
  { ru: "дизайнер", en: "designer" },
  { ru: "рыбак", en: "fisherman" },
  { ru: "стоматолог", en: "dentist" },
  { ru: "электрик", en: "electrician" },
  { ru: "фермер", en: "farmer" },
  { ru: "лингвист", en: "linguist" },
  { ru: "водитель грузовика", en: "truck driver" },
  { ru: "архитектор", en: "architect" },
  { ru: "кузнец", en: "blacksmith" },
  { ru: "метеоролог", en: "meteorologist" },
];

export const BUNKER_HEALTH: readonly BunkerText[] = [
  { ru: "полностью здоров", en: "perfectly healthy" },
  { ru: "аллергия на пыль", en: "dust allergy" },
  { ru: "астма", en: "asthma" },
  { ru: "плохое зрение", en: "poor eyesight" },
  { ru: "идеальная физическая форма", en: "peak physical fitness" },
  { ru: "бессонница", en: "insomnia" },
  { ru: "боится темноты", en: "afraid of the dark" },
  { ru: "клаустрофобия", en: "claustrophobia" },
  { ru: "сломана рука", en: "broken arm" },
  { ru: "диабет", en: "diabetes" },
  { ru: "храпит очень громко", en: "snores very loudly" },
  { ru: "отличный иммунитет", en: "excellent immunity" },
  { ru: "лишний вес", en: "overweight" },
  { ru: "слабое сердце", en: "weak heart" },
  { ru: "плохой слух", en: "poor hearing" },
  { ru: "мигрени", en: "migraines" },
  { ru: "возраст 75 лет, здоровье отличное", en: "75 years old, in great health" },
  { ru: "ждёт ребёнка", en: "expecting a baby" },
  { ru: "лунатизм", en: "sleepwalking" },
  { ru: "аллергия на орехи", en: "nut allergy" },
  { ru: "дальтонизм", en: "color blindness" },
  { ru: "хромает", en: "walks with a limp" },
  { ru: "вечная простуда", en: "constant cold" },
  { ru: "сила как у быка", en: "strong as an ox" },
  { ru: "боится крови", en: "afraid of blood" },
  { ru: "панические атаки", en: "panic attacks" },
  { ru: "не может уснуть без сериалов", en: "healthy but can't sleep without TV" },
  { ru: "отличное ночное зрение", en: "great night vision" },
  { ru: "хроническая усталость", en: "chronic fatigue" },
  { ru: "абсолютный слух", en: "perfect pitch" },
];

export const BUNKER_HOBBIES: readonly BunkerText[] = [
  { ru: "вязание", en: "knitting" },
  { ru: "шахматы", en: "chess" },
  { ru: "выживание в лесу", en: "wilderness survival" },
  { ru: "игра на гитаре", en: "playing guitar" },
  { ru: "кулинария", en: "cooking" },
  { ru: "йога", en: "yoga" },
  { ru: "стрельба из лука", en: "archery" },
  { ru: "садоводство", en: "gardening" },
  { ru: "рыбалка", en: "fishing" },
  { ru: "фокусы", en: "magic tricks" },
  { ru: "паркур", en: "parkour" },
  { ru: "чтение детективов", en: "reading mysteries" },
  { ru: "бокс", en: "boxing" },
  { ru: "рисование", en: "painting" },
  { ru: "пение в караоке", en: "karaoke singing" },
  { ru: "ремонт техники", en: "fixing gadgets" },
  { ru: "танцы", en: "dancing" },
  { ru: "астрономия", en: "astronomy" },
  { ru: "охота за грибами", en: "mushroom foraging" },
  { ru: "компьютерные игры", en: "video games" },
  { ru: "настольные игры", en: "board games" },
  { ru: "стендап", en: "stand-up comedy" },
  { ru: "оригами", en: "origami" },
  { ru: "плавание", en: "swimming" },
  { ru: "плотничество", en: "woodworking" },
  { ru: "коллекционирование монет", en: "coin collecting" },
  { ru: "медитация", en: "meditation" },
  { ru: "изучение языков", en: "learning languages" },
  { ru: "пивоварение", en: "home brewing" },
  { ru: "первая помощь", en: "first aid" },
  { ru: "скалолазание", en: "rock climbing" },
  { ru: "шитьё", en: "sewing" },
  { ru: "ведение дневника", en: "journaling" },
  { ru: "езда верхом", en: "horse riding" },
  { ru: "фотография", en: "photography" },
  { ru: "игра на домбре", en: "playing the dombra" },
  { ru: "велоспорт", en: "cycling" },
  { ru: "разведение кур", en: "raising chickens" },
  { ru: "радиосвязь", en: "ham radio" },
  { ru: "кулинария на костре", en: "campfire cooking" },
];

export const BUNKER_BAGGAGE: readonly BunkerText[] = [
  { ru: "аптечка", en: "first aid kit" },
  { ru: "мешок семян", en: "bag of seeds" },
  { ru: "гитара", en: "guitar" },
  { ru: "топор", en: "axe" },
  { ru: "ящик тушёнки", en: "crate of canned meat" },
  { ru: "рация", en: "walkie-talkie" },
  { ru: "солнечная панель", en: "solar panel" },
  { ru: "набор инструментов", en: "toolbox" },
  { ru: "удочка", en: "fishing rod" },
  { ru: "пачка книг", en: "stack of books" },
  { ru: "кошка", en: "a cat" },
  { ru: "собака", en: "a dog" },
  { ru: "10 литров воды", en: "10 liters of water" },
  { ru: "палатка", en: "tent" },
  { ru: "спальный мешок", en: "sleeping bag" },
  { ru: "фонарик без батареек", en: "flashlight with no batteries" },
  { ru: "коробка батареек", en: "box of batteries" },
  { ru: "ноутбук", en: "laptop" },
  { ru: "колода карт", en: "deck of cards" },
  { ru: "мешок риса", en: "sack of rice" },
  { ru: "семейный альбом", en: "family photo album" },
  { ru: "противогаз", en: "gas mask" },
  { ru: "пистолет без патронов", en: "gun with no bullets" },
  { ru: "швейный набор", en: "sewing kit" },
  { ru: "компас", en: "compass" },
  { ru: "карта местности", en: "local map" },
  { ru: "бутылка коньяка", en: "bottle of brandy" },
  { ru: "настольная игра", en: "board game" },
  { ru: "учебник по медицине", en: "medical textbook" },
  { ru: "велосипед", en: "bicycle" },
  { ru: "генератор", en: "generator" },
  { ru: "бинокль", en: "binoculars" },
  { ru: "курица-несушка", en: "laying hen" },
  { ru: "ящик мыла", en: "crate of soap" },
  { ru: "зажигалки", en: "lighters" },
  { ru: "верёвка 30 метров", en: "30 meters of rope" },
  { ru: "плюшевый медведь", en: "teddy bear" },
  { ru: "водяной фильтр", en: "water filter" },
  { ru: "тёплая одежда на всех", en: "warm clothes for everyone" },
  { ru: "мешок сахара", en: "sack of sugar" },
];

export const BUNKER_SECRETS: readonly BunkerText[] = [
  { ru: "умеет водить любой транспорт", en: "can drive any vehicle" },
  { ru: "знает, где спрятан склад еды", en: "knows where a food stash is hidden" },
  { ru: "судимость в прошлом", en: "has been in prison" },
  { ru: "есть опыт принятия родов", en: "has delivered a baby before" },
  { ru: "не умеет плавать", en: "can't swim" },
  { ru: "говорит на пяти языках", en: "speaks five languages" },
  { ru: "умеет чинить генераторы", en: "can fix generators" },
  { ru: "по ночам тайно ест запасы", en: "secretly eats at night" },
  { ru: "скрывает настоящую профессию", en: "lies about their profession" },
  { ru: "боится всех животных", en: "afraid of all animals" },
  { ru: "знает азбуку Морзе", en: "knows Morse code" },
  { ru: "может не спать двое суток", en: "can stay awake for two days" },
  { ru: "отлично готовит из ничего", en: "cooks great meals from nothing" },
  { ru: "бывший чемпион по боксу", en: "former boxing champion" },
  { ru: "носит с собой семена редких растений", en: "carries rare plant seeds" },
  { ru: "умеет делать мыло", en: "can make soap" },
  { ru: "знает код от соседнего бункера", en: "knows the code to the next bunker" },
  { ru: "знает сюжеты всех фильмов о катастрофах", en: "has watched every disaster movie" },
  { ru: "не переносит шум", en: "can't stand noise" },
  { ru: "умеет разжигать огонь без спичек", en: "can start a fire without matches" },
  { ru: "бывший вожатый в лагере", en: "former summer camp counselor" },
  { ru: "очень громко чихает", en: "sneezes very loudly" },
  { ru: "храпит только по вторникам", en: "snores only on Tuesdays" },
  { ru: "знает всё о ядовитых грибах", en: "knows everything about poisonous mushrooms" },
  { ru: "умеет стричь", en: "can cut hair" },
  { ru: "профессионально торгуется", en: "haggles like a pro" },
  { ru: "может починить радио", en: "can fix a radio" },
  { ru: "умеет шить одежду", en: "can sew clothes" },
  { ru: "готовит еду во сне", en: "sleepwalks and cooks in their sleep" },
  { ru: "знает сотню анекдотов", en: "knows a hundred jokes" },
];

export const BUNKER_SCENARIOS: readonly BunkerText[] = [
  { ru: "Ядерная зима: выходить можно будет через 3 года", en: "Nuclear winter: you can go outside in 3 years" },
  { ru: "Зомби-апокалипсис: снаружи опасно ещё год", en: "Zombie apocalypse: it's dangerous outside for a year" },
  { ru: "Глобальный потоп: вода сойдёт через 8 месяцев", en: "Global flood: the water recedes in 8 months" },
  { ru: "Падение астероида: пыль осядет через 2 года", en: "Asteroid impact: the dust settles in 2 years" },
  { ru: "Восстание машин: роботы захватили города", en: "Machine uprising: robots have taken the cities" },
  { ru: "Пандемия неизвестного вируса: карантин на 1 год", en: "Unknown pandemic: a 1-year quarantine" },
  { ru: "Извержение супервулкана: небо тёмное полтора года", en: "Supervolcano eruption: dark skies for a year and a half" },
  { ru: "Вторжение инопланетян: они ищут людей по теплу", en: "Alien invasion: they track people by body heat" },
  { ru: "Новый ледниковый период: снаружи минус 60", en: "New ice age: minus 60 outside" },
  { ru: "Солнечная вспышка: вся электроника сгорела", en: "Solar flare: all electronics are fried" },
  { ru: "Гигантские муравьи захватили степь", en: "Giant ants have taken over the steppe" },
  { ru: "Землетрясение: город ушёл под землю", en: "Earthquake: the city sank underground" },
  { ru: "Химическая авария: воздух очистится через 10 месяцев", en: "Chemical accident: the air clears in 10 months" },
  { ru: "Все интернет-мемы стали реальностью", en: "Every internet meme became real" },
  { ru: "Кончился кофе во всём мире", en: "The world ran out of coffee" },
  { ru: "Мир захватили голуби", en: "Pigeons took over the world" },
];
