// Generated content bank. Edit the source lists, keep RU and EN aligned.
export type MusicQuizEntry = { answer: string; artist: string; year: string; fact: { ru: string; en: string }; locales: ReadonlyArray<"ru" | "en"> };

export const MUSIC_QUIZ_BANK: readonly MusicQuizEntry[] = [
  { answer: "Bohemian Rhapsody", artist: "Queen", year: "1975", fact: { ru: "Рок-эпос с несколькими разными музыкальными частями", en: "A genre-bending rock epic with several distinct sections" }, locales: ["ru", "en"] },
  { answer: "Imagine", artist: "John Lennon", year: "1971", fact: { ru: "Фортепианный гимн миру от бывшего участника The Beatles", en: "A piano-led peace anthem from a former Beatle" }, locales: ["ru", "en"] },
  { answer: "Billie Jean", artist: "Michael Jackson", year: "1982", fact: { ru: "Поп-хит с узнаваемой басовой партией с альбома Thriller", en: "A landmark pop hit with an instantly recognisable bassline" }, locales: ["ru", "en"] },
  { answer: "Smells Like Teen Spirit", artist: "Nirvana", year: "1991", fact: { ru: "Гранж-гимн, определивший звучание начала девяностых", en: "A grunge anthem that defined the early nineties" }, locales: ["ru", "en"] },
  { answer: "Hey Jude", artist: "The Beatles", year: "1968", fact: { ru: "Длинная песня с огромным хоровым финалом", en: "A long singalong with a huge chorus finale" }, locales: ["ru", "en"] },
  { answer: "Rolling in the Deep", artist: "Adele", year: "2010", fact: { ru: "Соул-поп хит о драматичном расставании", en: "A soul-pop breakthrough about a dramatic breakup" }, locales: ["ru", "en"] },
  { answer: "Stairway to Heaven", artist: "Led Zeppelin", year: "1971", fact: { ru: "Рок-композиция, начинающаяся с тихой акустики и разгоняющаяся к финалу", en: "A rock epic that builds from quiet acoustic to a loud finale" }, locales: ["ru", "en"] },
  { answer: "Hotel California", artist: "Eagles", year: "1976", fact: { ru: "Песня о загадочном отеле, откуда невозможно уйти", en: "A song about a mysterious hotel you can never leave" }, locales: ["ru", "en"] },
  { answer: "Like a Prayer", artist: "Madonna", year: "1989", fact: { ru: "Поп-песня с госпел-хором", en: "A pop song featuring a gospel choir" }, locales: ["ru", "en"] },
  { answer: "Wonderwall", artist: "Oasis", year: "1995", fact: { ru: "Британский хит, который играют под гитару у каждого костра", en: "A Britpop hit strummed at every campfire" }, locales: ["ru", "en"] },
  { answer: "Yesterday", artist: "The Beatles", year: "1965", fact: { ru: "Меланхоличная баллада под акустическую гитару и струнные", en: "A melancholy ballad with acoustic guitar and strings" }, locales: ["ru", "en"] },
  { answer: "Let It Be", artist: "The Beatles", year: "1970", fact: { ru: "Фортепианная баллада о словах мудрости", en: "A piano ballad about words of wisdom" }, locales: ["ru", "en"] },
  { answer: "Dancing Queen", artist: "ABBA", year: "1976", fact: { ru: "Диско-хит о семнадцатилетней королеве танцпола", en: "A disco hit about a seventeen-year-old queen of the dance floor" }, locales: ["ru", "en"] },
  { answer: "Take On Me", artist: "a-ha", year: "1985", fact: { ru: "Синти-поп хит с культовым рисованным клипом", en: "A synth-pop hit famous for its sketch-animation video" }, locales: ["ru", "en"] },
  { answer: "Sweet Child o' Mine", artist: "Guns N' Roses", year: "1987", fact: { ru: "Рок-баллада с легендарным гитарным вступлением", en: "A rock ballad with a legendary guitar intro" }, locales: ["ru", "en"] },
  { answer: "Nothing Else Matters", artist: "Metallica", year: "1991", fact: { ru: "Спокойная баллада от метал-группы", en: "A gentle ballad from a metal band" }, locales: ["ru", "en"] },
  { answer: "Wind of Change", artist: "Scorpions", year: "1990", fact: { ru: "Песня со свистом во вступлении о переменах в Европе", en: "A whistled ballad about change sweeping across Europe" }, locales: ["ru", "en"] },
  { answer: "Livin' on a Prayer", artist: "Bon Jovi", year: "1986", fact: { ru: "Рок-гимн о паре Томми и Джине", en: "A rock anthem about a couple named Tommy and Gina" }, locales: ["ru", "en"] },
  { answer: "I Will Always Love You", artist: "Whitney Houston", year: "1992", fact: { ru: "Баллада из фильма «Телохранитель»", en: "A power ballad from the film The Bodyguard" }, locales: ["ru", "en"] },
  { answer: "My Heart Will Go On", artist: "Celine Dion", year: "1997", fact: { ru: "Главная песня фильма «Титаник»", en: "The main theme from the film Titanic" }, locales: ["ru", "en"] },
  { answer: "...Baby One More Time", artist: "Britney Spears", year: "1998", fact: { ru: "Дебютный хит в школьной форме", en: "A debut hit with a school-uniform music video" }, locales: ["ru", "en"] },
  { answer: "Crazy in Love", artist: "Beyoncé", year: "2003", fact: { ru: "Первый сольный хит с яркой духовой секцией", en: "A debut solo smash with a bold horn hook" }, locales: ["ru", "en"] },
  { answer: "Umbrella", artist: "Rihanna", year: "2007", fact: { ru: "Хит с повторяющимся «эла-эла»", en: "A hit with a repeating \"ella, ella\" hook" }, locales: ["ru", "en"] },
  { answer: "Poker Face", artist: "Lady Gaga", year: "2008", fact: { ru: "Электропоп-хит о покерном лице", en: "An electropop hit about keeping a poker face" }, locales: ["ru", "en"] },
  { answer: "Someone Like You", artist: "Adele", year: "2011", fact: { ru: "Фортепианная баллада о встрече с бывшим", en: "A piano ballad about seeing an ex again" }, locales: ["ru", "en"] },
  { answer: "Shape of You", artist: "Ed Sheeran", year: "2017", fact: { ru: "Поп-хит с марими-подобным ритмом о влюблённости в спортзале", en: "A marimba-flavored pop hit about falling for someone" }, locales: ["ru", "en"] },
  { answer: "Uptown Funk", artist: "Mark Ronson feat. Bruno Mars", year: "2014", fact: { ru: "Фанк-хит, под который невозможно не танцевать", en: "A funk hit that is impossible not to dance to" }, locales: ["ru", "en"] },
  { answer: "Happy", artist: "Pharrell Williams", year: "2013", fact: { ru: "Песня из мультфильма «Гадкий я 2» о счастье", en: "A feel-good song from Despicable Me 2" }, locales: ["ru", "en"] },
  { answer: "Despacito", artist: "Luis Fonsi feat. Daddy Yankee", year: "2017", fact: { ru: "Испаноязычный хит-рекордсмен YouTube", en: "A Spanish-language YouTube record-breaker" }, locales: ["ru", "en"] },
  { answer: "Gangnam Style", artist: "PSY", year: "2012", fact: { ru: "Корейский хит с танцем «на лошади»", en: "A Korean hit with a famous horse-riding dance" }, locales: ["ru", "en"] },
  { answer: "bad guy", artist: "Billie Eilish", year: "2019", fact: { ru: "Минималистичный хит с шёпотом и басом", en: "A minimalist hit built on whispers and bass" }, locales: ["ru", "en"] },
  { answer: "Blinding Lights", artist: "The Weeknd", year: "2019", fact: { ru: "Синтвейв-хит, звучащий как восьмидесятые", en: "A synthwave hit that sounds like the eighties" }, locales: ["ru", "en"] },
  { answer: "Shallow", artist: "Lady Gaga & Bradley Cooper", year: "2018", fact: { ru: "Дуэт из фильма «Звезда родилась»", en: "A duet from the film A Star Is Born" }, locales: ["ru", "en"] },
  { answer: "Believer", artist: "Imagine Dragons", year: "2017", fact: { ru: "Мощная песня о боли, которая делает сильнее", en: "A pounding anthem about pain making you stronger" }, locales: ["ru", "en"] },
  { answer: "Radioactive", artist: "Imagine Dragons", year: "2012", fact: { ru: "Хит с тяжёлыми барабанами о пробуждении", en: "A drum-heavy hit about waking up to a new world" }, locales: ["ru", "en"] },
  { answer: "Viva la Vida", artist: "Coldplay", year: "2008", fact: { ru: "Песня от лица свергнутого короля", en: "A song sung by a fallen king" }, locales: ["ru", "en"] },
  { answer: "Yellow", artist: "Coldplay", year: "2000", fact: { ru: "Ранний хит о звёздах, которые светят для тебя", en: "An early hit about the stars shining for you" }, locales: ["ru", "en"] },
  { answer: "Numb", artist: "Linkin Park", year: "2003", fact: { ru: "Ню-метал хит о давлении ожиданий", en: "A nu-metal hit about the pressure of expectations" }, locales: ["ru", "en"] },
  { answer: "In the End", artist: "Linkin Park", year: "2000", fact: { ru: "Хит с чередованием рэпа и мощного припева", en: "A hit alternating rap verses and a huge chorus" }, locales: ["ru", "en"] },
  { answer: "Lose Yourself", artist: "Eminem", year: "2002", fact: { ru: "Рэп из фильма «8 миля» о единственном шансе", en: "A rap from 8 Mile about one shot at success" }, locales: ["ru", "en"] },
  { answer: "Hips Don't Lie", artist: "Shakira", year: "2006", fact: { ru: "Латино-хит о бёдрах, которые не врут", en: "A Latin pop hit about hips that don't lie" }, locales: ["ru", "en"] },
  { answer: "Waka Waka", artist: "Shakira", year: "2010", fact: { ru: "Официальная песня чемпионата мира по футболу в ЮАР", en: "The official song of the 2010 World Cup in South Africa" }, locales: ["ru", "en"] },
  { answer: "Bad Romance", artist: "Lady Gaga", year: "2009", fact: { ru: "Электропоп-хит о плохом романе", en: "An electropop hit about a bad romance" }, locales: ["ru", "en"] },
  { answer: "(I Can't Get No) Satisfaction", artist: "The Rolling Stones", year: "1965", fact: { ru: "Рок-хит с узнаваемым гитарным риффом о недовольстве", en: "A riff-driven rock hit about dissatisfaction" }, locales: ["ru", "en"] },
  { answer: "We Will Rock You", artist: "Queen", year: "1977", fact: { ru: "Песня, под которую топают и хлопают на стадионах", en: "The stomp-stomp-clap stadium anthem" }, locales: ["ru", "en"] },
  { answer: "We Are the Champions", artist: "Queen", year: "1977", fact: { ru: "Гимн победителей на любых соревнованиях", en: "The anthem for winners everywhere" }, locales: ["ru", "en"] },
  { answer: "Africa", artist: "Toto", year: "1982", fact: { ru: "Софт-рок хит о дождях в Африке", en: "A soft-rock hit about rains down in Africa" }, locales: ["ru", "en"] },
  { answer: "Every Breath You Take", artist: "The Police", year: "1983", fact: { ru: "Песня о слежке, которую часто принимают за любовную", en: "A song about watching someone, often mistaken for a love song" }, locales: ["ru", "en"] },
  { answer: "Losing My Religion", artist: "R.E.M.", year: "1991", fact: { ru: "Хит с партией мандолины", en: "A hit built on a mandolin riff" }, locales: ["ru", "en"] },
  { answer: "Hello", artist: "Adele", year: "2015", fact: { ru: "Баллада, начинающаяся со слова «привет»", en: "A ballad that opens with a single greeting" }, locales: ["ru", "en"] },
  { answer: "Perfect", artist: "Ed Sheeran", year: "2017", fact: { ru: "Свадебная баллада о танце босиком", en: "A wedding ballad about dancing barefoot" }, locales: ["ru", "en"] },
  { answer: "Paradise", artist: "Coldplay", year: "2011", fact: { ru: "Песня о девушке, мечтающей о рае", en: "A song about a girl dreaming of paradise" }, locales: ["ru", "en"] },
  { answer: "Wake Me Up", artist: "Avicii", year: "2013", fact: { ru: "Смесь электроники и кантри-гитары", en: "A mix of EDM and country guitar" }, locales: ["ru", "en"] },
  { answer: "Get Lucky", artist: "Daft Punk feat. Pharrell Williams", year: "2013", fact: { ru: "Диско-фанк хит двух роботов из Франции", en: "A disco-funk hit from two French robots" }, locales: ["ru", "en"] },
  { answer: "Another One Bites the Dust", artist: "Queen", year: "1980", fact: { ru: "Хит на одной басовой линии", en: "A hit driven by one iconic bassline" }, locales: ["ru", "en"] },
  { answer: "Mamma Mia", artist: "ABBA", year: "1975", fact: { ru: "Песня, давшая имя мюзиклу", en: "The song that gave a musical its name" }, locales: ["ru", "en"] },
  { answer: "Here Comes the Sun", artist: "The Beatles", year: "1969", fact: { ru: "Светлая песня о конце долгой зимы", en: "A bright song about the end of a long winter" }, locales: ["ru", "en"] },
  { answer: "Jailhouse Rock", artist: "Elvis Presley", year: "1957", fact: { ru: "Рок-н-ролл о вечеринке в тюрьме", en: "A rock and roll song about a party in jail" }, locales: ["ru", "en"] },
  { answer: "Johnny B. Goode", artist: "Chuck Berry", year: "1958", fact: { ru: "Рок-н-ролл о парне из деревни, который играет на гитаре", en: "A rock and roll tale of a country boy who plays guitar" }, locales: ["ru", "en"] },
  { answer: "No Woman, No Cry", artist: "Bob Marley & The Wailers", year: "1974", fact: { ru: "Регги-баллада с утешением", en: "A comforting reggae ballad" }, locales: ["ru", "en"] },
  { answer: "I Wanna Dance with Somebody", artist: "Whitney Houston", year: "1987", fact: { ru: "Поп-хит о желании потанцевать с кем-то", en: "A pop hit about wanting to dance with someone" }, locales: ["ru", "en"] },
  { answer: "Girls Just Want to Have Fun", artist: "Cyndi Lauper", year: "1983", fact: { ru: "Гимн девичьего веселья", en: "An anthem about girls wanting fun" }, locales: ["ru", "en"] },
  { answer: "Without Me", artist: "Eminem", year: "2002", fact: { ru: "Рэп-хит о возвращении", en: "A rap hit about making a comeback" }, locales: ["ru", "en"] },
  { answer: "In da Club", artist: "50 Cent", year: "2003", fact: { ru: "Хит про день рождения в клубе", en: "A hit about a birthday in the club" }, locales: ["ru", "en"] },
  { answer: "Hey Ya!", artist: "OutKast", year: "2003", fact: { ru: "Весёлый хит, где просят трясти как полароидный снимок", en: "An upbeat hit that tells you to shake it like a Polaroid picture" }, locales: ["ru", "en"] },
  { answer: "Somebody That I Used to Know", artist: "Gotye feat. Kimbra", year: "2011", fact: { ru: "Песня о человеке, которого когда-то знал", en: "A song about someone you used to know" }, locales: ["ru", "en"] },
  { answer: "Call Me Maybe", artist: "Carly Rae Jepsen", year: "2011", fact: { ru: "Поп-хит о том, чтобы дать номер незнакомцу", en: "A pop hit about giving your number to a stranger" }, locales: ["ru", "en"] },
  { answer: "As It Was", artist: "Harry Styles", year: "2022", fact: { ru: "Поп-хит о том, что всё уже не как раньше", en: "A pop hit about things not being as they were" }, locales: ["ru", "en"] },
  { answer: "Levitating", artist: "Dua Lipa", year: "2020", fact: { ru: "Диско-поп о полёте под луной", en: "A disco-pop song about floating under the moonlight" }, locales: ["ru", "en"] },
  { answer: "Heat Waves", artist: "Glass Animals", year: "2020", fact: { ru: "Инди-хит о жаре и ностальгии", en: "An indie hit about heat and longing" }, locales: ["ru", "en"] },
  { answer: "Flowers", artist: "Miley Cyrus", year: "2023", fact: { ru: "Песня о том, чтобы самой покупать себе цветы", en: "A song about buying yourself flowers" }, locales: ["ru", "en"] },
  { answer: "Dance Monkey", artist: "Tones and I", year: "2019", fact: { ru: "Хит о просьбах станцевать ещё раз", en: "A hit about being asked to dance again and again" }, locales: ["ru", "en"] },
  { answer: "Old Town Road", artist: "Lil Nas X", year: "2018", fact: { ru: "Смесь кантри и трэпа о лошади", en: "A country-trap mix about riding a horse" }, locales: ["ru", "en"] },
  { answer: "Кукушка", artist: "Кино", year: "1990", fact: { ru: "Песня с последнего альбома группы о свободе и судьбе", en: "A song about fate from the band's final album" }, locales: ["ru"] },
  { answer: "Группа крови", artist: "Кино", year: "1988", fact: { ru: "Песня о солдате с группой крови на рукаве", en: "A song about a soldier with his blood type on his sleeve" }, locales: ["ru"] },
  { answer: "Звезда по имени Солнце", artist: "Кино", year: "1989", fact: { ru: "Песня о звезде по имени Солнце", en: "A song about a star named the Sun" }, locales: ["ru"] },
];
