export const SHOWABLE_WORDS: { readonly ru: readonly string[]; readonly en: readonly string[] } = {
 ru: [
  "Динозавр", "Ниндзя", "Фейерверк", "Пингвин", "Гитара", "Лунная походка", "Пират", "Вертолёт", "Торнадо",
  "Робот", "Медуза", "Маяк", "Слон", "Жираф", "Кенгуру", "Обезьяна", "Змея", "Лягушка", "Краб", "Осьминог",
  "Курица", "Петух", "Корова", "Лошадь", "Кошка", "Собака", "Зайчик", "Медведь", "Волк", "Орёл", "Бабочка",
  "Пчела", "Комар", "Паук", "Черепаха", "Улитка", "Дельфин", "Акула", "Кит", "Крокодил", "Лев", "Горилла",
  "Ленивец", "Фламинго", "Страус", "Сова", "Летучая мышь", "Белка", "Ёж", "Скорпион", "Зомби", "Вампир",
  "Привидение", "Мумия", "Супермен", "Человек-паук", "Русалка", "Фея", "Ведьма на метле", "Джинн из лампы",
  "Рыцарь", "Самурай", "Ковбой", "Космонавт", "Водолаз", "Пожарный", "Полицейский", "Врач", "Стоматолог",
  "Парикмахер", "Повар", "Официант", "Дирижёр", "Фокусник", "Клоун", "Жонглёр", "Канатоходец", "Штангист",
  "Боксёр", "Вратарь", "Баскетболист", "Теннисист", "Пловец", "Серфер", "Лыжник", "Фигурист", "Сноубордист",
  "Скалолаз", "Балерина", "Диджей", "Рок-звезда", "Барабанщик", "Скрипач", "Пианист", "Оперная певица", "Фотограф",
  "Художник", "Скульптор", "Строитель", "Дровосек", "Рыбак", "Охотник", "Садовник", "Пастух", "Почтальон",
  "Курьер", "Таксист", "Пилот", "Стюардесса", "Капитан корабля", "Светофор", "Стиральная машина", "Пылесос",
  "Миксер", "Холодильник", "Будильник", "Телефон", "Фотоаппарат", "Зонтик", "Чемодан", "Ножницы", "Молоток",
  "Пила", "Дрель", "Лестница", "Качели", "Карусель", "Батут", "Американские горки", "Лифт", "Эскалатор",
  "Вращающаяся дверь", "Душ", "Ванна", "Зеркало", "Расчёска", "Зубная щётка", "Фен", "Утюг", "Швабра", "Веник",
  "Мыльные пузыри", "Воздушный шарик", "Воздушный змей", "Бумажный самолётик", "Снеговик", "Снежки", "Санки",
  "Лыжи", "Коньки", "Велосипед", "Самокат", "Скейтборд", "Мотоцикл", "Машина", "Автобус", "Поезд", "Самолёт",
  "Ракета", "Подводная лодка", "Корабль", "Лодка", "Парашют", "Воздушный шар", "Колесо обозрения", "Тачка",
  "Трактор", "Экскаватор", "Кран", "Светлячок", "Вулкан", "Землетрясение", "Дождь", "Гроза", "Снегопад",
  "Ветер", "Радуга", "Солнце", "Луна", "Звезда", "Облако", "Волна", "Водопад", "Костёр", "Палатка", "Рюкзак",
  "Компас", "Бинокль", "Телескоп", "Микроскоп", "Магнит", "Пружина", "Мяч", "Гантели", "Скакалка", "Обруч",
  "Штанга", "Удочка", "Лук и стрелы", "Меч", "Щит", "Пушка", "Катапульта", "Пистолет-водяной", "Шахматы",
  "Кубик Рубика", "Пазл", "Дженга", "Карты", "Кости", "Пинг-понг", "Боулинг", "Гольф", "Бильярд", "Дартс",
  "Хоккей", "Футбол", "Баскетбол", "Волейбол", "Бадминтон", "Бокс", "Армрестлинг", "Перетягивание каната",
  "Прятки", "Жмурки", "Классики", "Чехарда", "Бег в мешках", "Танец маленьких утят", "Макарена", "Брейк-данс",
  "Вальс", "Танго", "Лезгинка", "Кадриль", "Аэробика", "Йога", "Медитация", "Планка", "Отжимания", "Приседания",
  "Чихать", "Зевать", "Храпеть", "Икать", "Кашлять", "Плакать", "Смеяться", "Хлопать", "Свистеть", "Подмигивать",
  "Щекотать", "Обнимать", "Целовать руку", "Кланяться", "Отдавать честь", "Махать рукой", "Показывать класс",
  "Пожимать плечами", "Грызть ногти", "Чесать затылок", "Считать деньги", "Торговаться", "Писать письмо",
  "Читать газету", "Печатать на машинке", "Играть на пианино", "Играть в видеоигру", "Делать селфи", "Фотографировать",
  "Звонить по телефону", "Ждать лифт", "Стоять в пробке", "Ловить такси", "Садиться в автобус", "Бежать за автобусом",
  "Опаздывать на поезд", "Проходить досмотр", "Тащить чемодан", "Загорать", "Плыть кролем", "Нырять", "Кататься на серфе",
  "Ловить рыбу", "Собирать грибы", "Колоть дрова", "Разжигать костёр", "Ставить палатку", "Жарить шашлык",
  "Варить суп", "Резать лук", "Печь блины", "Месить тесто", "Пробовать горячее", "Есть спагетти", "Есть арбуз",
  "Пить через трубочку", "Открывать банку", "Чистить банан", "Чистить апельсин", "Взбивать яйца", "Мыть посуду",
  "Пылесосить", "Гладить бельё", "Развешивать бельё", "Мыть окна", "Поливать цветы", "Стричь газон", "Копать огород",
  "Забивать гвоздь", "Пилить доску", "Красить стену", "Менять лампочку", "Чинить кран", "Собирать мебель",
  "Наряжать ёлку", "Распаковывать подарок", "Задувать свечи", "Надувать шарик", "Лопать шарик", "Ловить бабочку",
  "Гнаться за мухой", "Отбиваться от комара", "Наступить на лего", "Поскользнуться на банане", "Застрять в двери",
  "Заблудиться в лесу", "Увидеть мышь", "Испугаться паука", "Поймать букет", "Делать предложение", "Танцевать на свадьбе",
  "Укачивать младенца", "Менять подгузник", "Выгуливать собаку", "Дрессировать собаку", "Кормить голубей",
  "Доить корову", "Ездить верхом", "Ловить курицу", "Стричь овцу", "Чистить зубы", "Бриться", "Краситься",
  "Завязывать галстук", "Надевать узкие джинсы", "Завязывать шнурки", "Примерять шляпу", "Ходить на каблуках",
  "Дефилировать", "Позировать", "Давать автограф", "Дирижировать оркестром", "Петь в караоке", "Играть на гитаре",
  "Играть на барабанах", "Играть на скрипке", "Играть на дудочке", "Показывать фокус", "Жонглировать", "Кататься на роликах",
  "Кататься на коньках", "Прыгать на батуте", "Качаться на качелях", "Кататься с горки", "Лепить снеговика",
  "Играть в снежки", "Строить замок из песка", "Запускать змея", "Пускать мыльные пузыри", "Стрелять из лука",
  "Фехтовать", "Биться на мечах", "Грабить банк", "Красться как шпион", "Открывать сейф", "Убегать от полиции",
  "Ловить вора", "Сидеть в засаде", "Выступать на сцене", "Забыть слова", "Получать награду", "Произносить тост",
  "Открывать шампанское", "Ловить такси под дождём", "Ехать в переполненном метро", "Ругаться с навигатором",
  "Парковаться задом", "Заводить машину зимой", "Менять колесо", "Заправлять машину", "Мыть машину", "Спускаться на парашюте",
  "Лететь в самолёте при турбулентности", "Проходить через турникет", "Играть в теннис", "Бить пенальти",
  "Отбивать мяч", "Забивать гол", "Поднимать штангу", "Крутить обруч", "Прыгать через скакалку", "Бежать марафон",
  "Финишировать первым", "Болеть за команду", "Делать волну на стадионе", "Собирать пазл", "Играть в шахматы",
  "Строить башню из кубиков", "Сдавать экзамен", "Списывать", "Отвечать у доски", "Спать на уроке", "Поднимать руку",
  "Писать на доске", "Ловить шпаргалку", "Открывать зонт против ветра", "Прыгать по лужам", "Лепить пельмени",
  "Есть палочками", "Пить горячий чай", "Дуть на суп", "Обжечься", "Найти волос в супе", "Открывать упрямую банку",
  "Резать торт", "Делить пиццу", "Ждать доставку", "Спорить о пульте", "Засыпать перед телевизором", "Искать носок",
  "Будить соседа", "Ловить Wi-Fi", "Заряжать телефон", "Уронить телефон в воду", "Фоткать еду", "Записывать сторис",
  "Танцевать тикток",
 ],
 en: [
  "Dinosaur", "Ninja", "Fireworks", "Penguin", "Guitar", "Moonwalk", "Pirate", "Helicopter", "Tornado", "Robot",
  "Jellyfish", "Lighthouse", "Elephant", "Giraffe", "Kangaroo", "Monkey", "Snake", "Frog", "Crab", "Octopus",
  "Chicken", "Rooster", "Cow", "Horse", "Cat", "Dog", "Bunny", "Bear", "Wolf", "Eagle", "Butterfly", "Bee",
  "Mosquito", "Spider", "Turtle", "Snail", "Dolphin", "Shark", "Whale", "Crocodile", "Lion", "Gorilla", "Sloth",
  "Flamingo", "Ostrich", "Owl", "Bat", "Squirrel", "Hedgehog", "Scorpion", "Zombie", "Vampire", "Ghost",
  "Mummy", "Superman", "Spider-Man", "Mermaid", "Fairy", "Witch on a broom", "Genie in a lamp", "Knight",
  "Samurai", "Cowboy", "Astronaut", "Scuba diver", "Firefighter", "Police officer", "Doctor", "Dentist",
  "Hairdresser", "Chef", "Waiter", "Conductor", "Magician", "Clown", "Juggler", "Tightrope walker", "Weightlifter",
  "Boxer", "Goalkeeper", "Basketball player", "Tennis player", "Swimmer", "Surfer", "Skier", "Figure skater",
  "Snowboarder", "Rock climber", "Ballerina", "DJ", "Rock star", "Drummer", "Violinist", "Pianist", "Opera singer",
  "Photographer", "Painter", "Sculptor", "Builder", "Lumberjack", "Fisherman", "Hunter", "Gardener", "Shepherd",
  "Mail carrier", "Courier", "Taxi driver", "Pilot", "Flight attendant", "Ship captain", "Traffic light",
  "Washing machine", "Vacuum cleaner", "Mixer", "Fridge", "Alarm clock", "Phone", "Camera", "Umbrella", "Suitcase",
  "Scissors", "Hammer", "Saw", "Drill", "Ladder", "Swing", "Carousel", "Trampoline", "Roller coaster", "Elevator",
  "Escalator", "Revolving door", "Shower", "Bathtub", "Mirror", "Comb", "Toothbrush", "Hair dryer", "Iron",
  "Mop", "Broom", "Soap bubbles", "Balloon", "Kite", "Paper airplane", "Snowman", "Snowballs", "Sled", "Skis",
  "Ice skates", "Bicycle", "Scooter", "Skateboard", "Motorcycle", "Car", "Bus", "Train", "Airplane", "Rocket",
  "Submarine", "Ship", "Rowboat", "Parachute", "Hot air balloon", "Ferris wheel", "Wheelbarrow", "Tractor",
  "Excavator", "Crane", "Firefly", "Volcano", "Earthquake", "Rain", "Thunderstorm", "Snowfall", "Wind", "Rainbow",
  "Sun", "Moon", "Star", "Cloud", "Wave", "Waterfall", "Campfire", "Tent", "Backpack", "Compass", "Binoculars",
  "Telescope", "Microscope", "Magnet", "Spring", "Ball", "Dumbbells", "Jump rope", "Hula hoop", "Barbell",
  "Fishing rod", "Bow and arrow", "Sword", "Shield", "Cannon", "Catapult", "Water gun", "Chess", "Rubik's cube",
  "Jigsaw puzzle", "Jenga", "Playing cards", "Dice", "Ping pong", "Bowling", "Golf", "Billiards", "Darts",
  "Hockey", "Football", "Basketball", "Volleyball", "Badminton", "Boxing", "Arm wrestling", "Tug of war",
  "Hide and seek", "Blind man's buff", "Hopscotch", "Leapfrog", "Sack race", "Chicken dance", "Macarena",
  "Breakdance", "Waltz", "Tango", "Conga line", "Aerobics", "Yoga", "Meditation", "Plank", "Push-ups", "Squats",
  "Sneezing", "Yawning", "Snoring", "Hiccups", "Coughing", "Crying", "Laughing", "Clapping", "Whistling",
  "Winking", "Tickling", "Hugging", "Kissing a hand", "Bowing", "Saluting", "Waving", "Thumbs up", "Shrugging",
  "Biting nails", "Scratching your head", "Counting money", "Haggling", "Writing a letter", "Reading a newspaper",
  "Typing on a typewriter", "Playing piano", "Playing a video game", "Taking a selfie", "Taking photos",
  "Making a phone call", "Waiting for an elevator", "Stuck in traffic", "Hailing a taxi", "Getting on a bus",
  "Chasing a bus", "Missing a train", "Airport security check", "Dragging a suitcase", "Sunbathing", "Swimming front crawl",
  "Diving", "Surfing", "Fishing", "Picking mushrooms", "Chopping wood", "Lighting a fire", "Pitching a tent",
  "Grilling kebabs", "Cooking soup", "Chopping onions", "Making pancakes", "Kneading dough", "Tasting something hot",
  "Eating spaghetti", "Eating watermelon", "Drinking through a straw", "Opening a jar", "Peeling a banana",
  "Peeling an orange", "Whisking eggs", "Washing dishes", "Vacuuming", "Ironing clothes", "Hanging laundry",
  "Cleaning windows", "Watering flowers", "Mowing the lawn", "Digging a garden", "Hammering a nail", "Sawing a board",
  "Painting a wall", "Changing a light bulb", "Fixing a faucet", "Assembling furniture", "Decorating a tree",
  "Unwrapping a gift", "Blowing out candles", "Blowing up a balloon", "Popping a balloon", "Catching a butterfly",
  "Chasing a fly", "Swatting a mosquito", "Stepping on Lego", "Slipping on a banana", "Stuck in a door",
  "Lost in the woods", "Seeing a mouse", "Scared of a spider", "Catching the bouquet", "Proposing", "Dancing at a wedding",
  "Rocking a baby", "Changing a diaper", "Walking a dog", "Training a dog", "Feeding pigeons", "Milking a cow",
  "Horse riding", "Catching a chicken", "Shearing a sheep", "Brushing teeth", "Shaving", "Putting on makeup",
  "Tying a tie", "Putting on tight jeans", "Tying shoelaces", "Trying on a hat", "Walking in high heels",
  "Catwalk", "Posing", "Signing an autograph", "Conducting an orchestra", "Singing karaoke", "Playing guitar",
  "Playing drums", "Playing violin", "Playing a flute", "Doing a magic trick", "Juggling", "Roller skating",
  "Ice skating", "Jumping on a trampoline", "Swinging on a swing", "Going down a slide", "Building a snowman",
  "Snowball fight", "Building a sandcastle", "Flying a kite", "Blowing bubbles", "Archery", "Fencing", "Sword fight",
  "Robbing a bank", "Sneaking like a spy", "Cracking a safe", "Running from the police", "Catching a thief",
  "Stakeout", "Performing on stage", "Forgetting your lines", "Receiving an award", "Giving a toast", "Opening champagne",
  "Taxi in the rain", "Crowded subway", "Arguing with GPS", "Parallel parking", "Starting a car in winter",
  "Changing a tire", "Filling up the car", "Washing the car", "Parachute jump", "Airplane turbulence", "Going through a turnstile",
  "Playing tennis", "Taking a penalty", "Hitting a baseball", "Scoring a goal", "Lifting weights", "Spinning a hula hoop",
  "Skipping rope", "Running a marathon", "Winning a race", "Cheering for a team", "Stadium wave", "Doing a puzzle",
  "Playing chess", "Building a block tower", "Taking an exam", "Cheating on a test", "Answering at the board",
  "Sleeping in class", "Raising your hand", "Writing on the board", "Opening an umbrella in the wind", "Jumping in puddles",
  "Making dumplings", "Eating with chopsticks", "Drinking hot tea", "Blowing on soup", "Burning your tongue",
  "Hair in the soup", "Stubborn jar lid", "Cutting a cake", "Sharing pizza", "Waiting for delivery", "Fighting over the remote",
  "Falling asleep in front of the TV", "Looking for a sock", "Waking a neighbor", "Searching for Wi-Fi",
  "Charging a phone", "Dropping a phone in water", "Photographing food", "Recording a story", "TikTok dance",
 ],
};
