// Generated content bank. Edit the source lists, keep RU and EN aligned.
export const SOCIAL_PROMPTS = {
  ru: {
    truth: [
      "Какой твой самый недооценённый навык?",
      "Кто из присутствующих лучше всех спланировал бы поездку?",
      "Какая песня всегда поднимает тебе настроение?",
      "Какую самую странную вещь ты ел?",
      "О чём ты мечтал в детстве, а теперь смешно вспоминать?",
      "Какой фильм ты пересматривал больше всего раз?",
      "Какое твоё самое неловкое воспоминание со школы?",
      "Кому из присутствующих ты доверил бы свой телефон на день?",
      "Какая привычка у тебя самая странная?",
      "Что ты делал бы, если бы выиграл миллион?",
      "Какую ложь ты чаще всего говоришь?",
      "Какая была твоя первая работа?",
      "Какое приложение ты открываешь чаще всего?",
      "Что последнее ты гуглил?",
      "Какой самый глупый повод для ссоры у тебя был?",
      "В кого из знаменитостей ты был влюблён в детстве?",
      "Какую суперсилу ты бы выбрал и почему?",
      "Какое блюдо ты готовишь лучше всего?",
      "Когда ты последний раз плакал из-за фильма?",
      "Что тебя бесит в людях сильнее всего?",
      "Какую вещь ты никогда не выбросишь?",
      "Какой самый смелый поступок ты совершал?",
      "Что бы ты изменил в своём прошлом, если бы мог?",
      "Какое прозвище у тебя было в детстве?",
      "Кого из присутствующих ты знаешь дольше всех?",
      "Чего ты боишься, хотя понимаешь, что это глупо?",
      "Какой подарок тебе понравился больше всего?",
      "Какой подарок был самым неудачным?",
      "Кого бы ты взял с собой на необитаемый остров?",
      "Какую песню ты поёшь в караоке?",
      "Что ты делаешь, когда никто не видит?",
      "Какой сериал ты смотрел запоем?",
      "Какой был твой самый неудачный наряд?",
      "Какая черта в тебе нравится тебе больше всего?",
      "Что ты хотел бы уметь, но стесняешься начать?",
      "Кто твой кумир и почему?",
      "Когда тебе было по-настоящему стыдно?",
      "Какое самое необычное место, где ты спал?",
      "Какую самую долгую дорогу ты проделал ради человека?",
      "Какая эмодзи описывает тебя лучше всего?",
      "Что ты откладываешь уже больше месяца?",
      "О какой покупке ты жалеешь?",
      "Какой совет ты дал бы себе в 15 лет?",
      "Кто из присутствующих самый смешной?",
      "Кто из присутствующих чаще всех опаздывает?",
      "Какой твой самый странный сон?",
      "Какой город ты хочешь посетить больше всего?",
      "Что ты ешь, когда грустно?",
      "Какое правило ты нарушал чаще всего?",
      "Какой запах напоминает тебе детство?",
      "Какую знаменитость ты хотел бы пригласить на эту тусу?",
      "Когда ты последний раз врал, чтобы не идти куда-то?",
      "Что ты сделаешь в первую очередь, если станешь невидимым?",
      "Какой самый дорогой ужин у тебя был?",
      "Какую игру ты проигрываешь чаще всего?",
      "Что тебя удивило в тебе самом в этом году?",
      "Какое самое долгое время ты не спал?",
      "Какую фразу ты говоришь слишком часто?",
      "Кто из присутствующих лучше всех танцует?",
      "Какое хобби ты бросил быстрее всего?",
      "Какую профессию ты выбрал бы, если бы начал сначала?",
      "Какая вещь в твоей комнате самая старая?",
      "Что ты скрывал от родителей дольше всего?",
      "Какой самый неловкий момент на свидании у тебя был?",
      "Какая твоя самая любимая традиция?",
      "Кто из присутствующих первым выживет в зомби-апокалипсис?",
      "Что тебя заставит уйти с вечеринки раньше всех?",
      "Какой был твой самый спонтанный поступок?",
      "Какую вещь ты покупаешь снова и снова?",
      "Какой момент своей жизни ты хотел бы пережить ещё раз?",
      "Что ты думал о человеке слева при первой встрече?",
      "Какой навык ты освоил сам через YouTube?",
      "Какую песню ты стесняешься любить?",
      "Кто из присутствующих лучший советчик?",
      "Какой был твой самый громкий провал?",
      "Как ты обычно проводишь идеальное воскресенье?",
      "Какое слово ты долго произносил неправильно?",
      "О чём ты споришь с друзьями чаще всего?",
      "Какое у тебя самое сильное суеверие?",
      "Какой комплимент ты помнишь до сих пор?",
      "Когда ты последний раз танцевал один дома?",
      "Кто в твоей семье самый смешной?",
      "Какой был твой первый телефон?",
      "Сколько непрочитанных сообщений у тебя сейчас?",
      "Что ты сделаешь, если завтра выходной на неделю?",
      "Какая еда тебе нравится, хотя многие её терпеть не могут?",
      "Кто из присутствующих лучше всех хранит секреты?",
      "Какой самый безумный поступок ты сделал ради любви?",
      "Каким был бы твой идеальный день рождения?",
      "Какую роль в фильме ты сыграл бы без подготовки?",
      "Какая черта тебя привлекает в людях?",
      "Какую книгу ты советуешь всем?",
      "Что ты никогда не сделаешь даже за деньги?",
      "Если бы ты был блюдом, то каким?",
      "Какой момент этой тусы тебе запомнится?",
      "Какая погода у тебя любимая?",
      "Что ты обычно заказываешь в кофейне?",
      "Что ты смотришь, чтобы уснуть?",
      "Кто научил тебя самому важному в жизни?",
      "Какой навык у тебя совершенно бесполезный, но крутой?",
      "Какую страну ты посетил последней?",
      "Какой звук тебя раздражает больше всего?",
      "Кто из присутствующих чаще всего сидит в телефоне?",
      "Что было самым сложным в этом году?",
      "Какую эпоху ты хотел бы посетить?",
      "Какой был самый странный вопрос на собеседовании?",
      "Ты больше сова или жаворонок и почему?",
      "Кого ты позвонишь первым, если случится беда?",
      "Какой твой любимый мем?",
      "Сколько будильников ты ставишь по утрам?",
      "Какое животное похоже на тебя?",
      "Что ты сказал бы себе через 10 лет?",
      "Какую вещь ты всегда забываешь дома?",
      "Какой твой самый большой страх перед путешествием?",
      "Кто из присутствующих лучше всех готовит?",
      "Какой был самый смешной случай в такси?",
      "Что ты делаешь первым делом утром?",
      "Кому ты давно хочешь написать, но не решаешься?",
      "Что бы ты сделал, если бы проснулся другим человеком?",
      "Какую знаменитость ты считаешь переоценённой?",
      "Какую мелочь ты ценишь больше всего?",
      "Как ты обычно выбираешь фильм на вечер?",
      "Какое слово описывает эту компанию?",
    ],
    dare: [
      "Придумай танцевальное движение на 10 секунд",
      "Сделай искренний комплимент соседу справа",
      "Озвучь эту тусу как трейлер фильма",
      "Спой куплет любимой песни",
      "Изобрази любое животное, пока все не угадают",
      "Расскажи анекдот с серьёзным лицом",
      "Говори с акцентом до следующего хода",
      "Покажи последнее фото в галерее",
      "Сделай 10 приседаний",
      "Прочитай вслух последнее сообщение, которое ты отправил",
      "Изобрази знаменитость, пусть угадают",
      "Поставь песню и станцуй 20 секунд",
      "Нарисуй портрет соседа за 30 секунд",
      "Сделай селфи с самой смешной гримасой",
      "Расскажи скороговорку три раза подряд",
      "Изобрази робота, который влюбился",
      "Произнеси тост за хозяина тусы",
      "Пройдись по комнате как модель на подиуме",
      "Опиши свой день в стиле спортивного комментатора",
      "Сыграй сцену расставания с подушкой",
      "Говори только вопросами следующие две минуты",
      "Покажи, как ты танцуешь на свадьбе",
      "Изобрази кота, который видит огурец",
      "Придумай рэп про человека слева",
      "Держи планку 30 секунд",
      "Сделай голосовое сообщение другу в стиле оперы",
      "Расскажи историю, в которой каждое слово на одну букву",
      "Изобрази, как ты просыпаешься в понедельник",
      "Научи всех своему фирменному жесту",
      "Покажи лучший танец из 2000-х",
      "Изобрази рекламу обычной ложки",
      "Сделай комплимент каждому в комнате",
      "Поменяйся местами с любым игроком",
      "Минуту говори как ведущий новостей",
      "Изобрази любимого персонажа мультфильма",
      "Сделай фирменную позу для обложки журнала",
      "Прочитай стих так, будто это драма века",
      "Изобрази спортсмена в замедленной съёмке",
      "Расскажи о себе как о товаре на маркетплейсе",
      "Попробуй сделать стойку у стены",
      "Спой «С днём рождения» на свой лад",
      "Изобрази, как ты заказываешь кофе в спешке",
      "Придумай новое название этой тусе",
      "Изобрази звук любого предмета, пусть угадают",
      "Станцуй под песню, которую выберет сосед",
      "Пять секунд смотри в глаза соседу, не смеясь",
      "Покажи свой лучший смех злодея",
      "Опиши любимое блюдо, не называя его",
      "Изобрази голос навигатора",
      "Сделай комплимент себе как лучший друг",
      "Покажи, как ты фотографируешь еду",
      "Разыграй сценку «опоздал на самолёт»",
      "Изобрази первое свидание двух пингвинов",
      "Сделай мини-стендап на 30 секунд",
      "Изобрази, как ты ищешь ключи перед выходом",
      "Произнеси скороговорку с полным ртом воды",
      "Покажи самый медленный танец в мире",
      "Нарисуй дом с закрытыми глазами",
      "Изобрази знаменитую сцену из фильма",
      "Придумай слоган для этой компании",
      "Покажи, как бы ты вёл кулинарное шоу",
      "Изобрази человека, который впервые видит снег",
      "Сыграй на воображаемой гитаре соло",
      "Сделай 5 комплиментов подряд без повторов",
      "Изобрази, как ты уговариваешь кота слезть со стола",
      "Расскажи о своём дне задом наперёд",
      "Покажи позу йоги и держи 15 секунд",
      "Изобрази блогера, распаковывающего подарок",
      "Скажи «спасибо» на пяти языках",
      "Прошепчи секрет на ухо соседу",
      "Изобрази реакцию на выигрыш в лотерею",
      "Станцуй лезгинку или любой народный танец",
      "Изобрази, как ты едешь в переполненном автобусе",
      "Придумай историю из трёх слов, которые назовут игроки",
      "Говори голосом мультяшного героя до конца раунда",
      "Покажи любимое упражнение из зала",
      "Изобрази дирижёра оркестра под любую песню",
      "Сделай вид, что ты ведущий свадьбы",
      "Нарисуй себя в виде супергероя",
      "Изобрази, как ты торгуешься на базаре",
      "Сделай танец маленьких утят",
      "Покажи, как ты тайно ешь ночью из холодильника",
      "Изобрази робота-пылесоса, который застрял",
      "Придумай прозвище каждому игроку",
      "Изобрази футболиста, который празднует гол",
      "Расскажи, как прошёл бы твой идеальный день, в стиле сказки",
      "Изобрази модель из рекламы шампуня",
      "Спой любую песню, заменив слова на «мяу»",
      "Покажи, как ты танцуешь, когда никто не видит",
      "Изобрази гида, который ведёт экскурсию по этой комнате",
      "Попробуй удержать ложку на носу 5 секунд",
      "Изобрази, как ты впервые пробуешь очень острое",
      "Скажи комплимент человеку, с которым меньше всего общался",
      "Сделай волну руками вместе со всеми",
      "Изобрази человека, который говорит по телефону и теряет связь",
      "Покажи самую пафосную позу для фото",
      "Расскажи, за что ты благодарен сегодня",
      "Изобрази, как ты встречаешь курьера с едой",
      "Попробуй станцевать брейк-данс",
      "Изобрази динозавра, который пытается сделать селфи",
      "Изобрази, как ты спишь на совещании",
      "Спой припев любой песни шёпотом",
      "Покажи, как ты празднуешь пятницу",
      "Изобрази детектива, который ищет виноватого среди игроков",
      "Сделай «змейку» из игроков и проведи её по комнате",
      "Изобрази, как ты впервые встал на коньки",
      "Устрой минуту аплодисментов самому тихому игроку",
      "Изобрази бабушку, которая впервые пользуется смартфоном",
      "Придумай и покажи новое приветствие для компании",
    ],
    never: [
      "Я никогда не забывал имя собеседника прямо во время разговора",
      "Я никогда не отправлял сообщение не тому человеку",
      "Я никогда не притворялся, что знаю песню",
      "Я никогда не засыпал в кино",
      "Я никогда не опаздывал на самолёт",
      "Я никогда не пел в караоке",
      "Я никогда не выдумывал болезнь, чтобы не идти на работу или учёбу",
      "Я никогда не терял ключи дважды за неделю",
      "Я никогда не смотрел сериал за одни выходные",
      "Я никогда не ел торт прямо из коробки",
      "Я никогда не падал на льду при людях",
      "Я никогда не звонил маме, чтобы узнать рецепт",
      "Я никогда не прыгал с парашютом",
      "Я никогда не был на концерте в первом ряду",
      "Я никогда не менял цвет волос",
      "Я никогда не отвечал «уже выхожу», ещё не встав с кровати",
      "Я никогда не ходил в поход с палаткой",
      "Я никогда не катался на лошади",
      "Я никогда не видел рассвет в горах",
      "Я никогда не терял телефон в такси",
      "Я никогда не смеялся в неподходящий момент",
      "Я никогда не выигрывал в лотерею",
      "Я никогда не готовил блюдо, которое никто не смог есть",
      "Я никогда не был на Шымбулаке",
      "Я никогда не купался в горной реке",
      "Я никогда не заблудился в торговом центре",
      "Я никогда не притворялся, что мне звонят, чтобы уйти от разговора",
      "Я никогда не удалял фото, потому что плохо на нём вышел",
      "Я никогда не ставил больше пяти будильников",
      "Я никогда не путал левое и правое при навигаторе",
      "Я никогда не танцевал на столе",
      "Я никогда не был на свадьбе больше чем на 300 гостей",
      "Я никогда не пробовал кумыс",
      "Я никогда не отправлял голосовое больше чем на пять минут",
      "Я никогда не плакал из-за мультфильма",
      "Я никогда не менял планы в последний момент ради сна",
      "Я никогда не выступал на сцене",
      "Я никогда не путешествовал один",
      "Я никогда не ел в ресторане, где не понимал меню",
      "Я никогда не брался за хобби и бросал через неделю",
      "Я никогда не проспал экзамен",
      "Я никогда не получал штраф за парковку",
      "Я никогда не говорил «я на диете» с тортом в руке",
      "Я никогда не писал бывшему ночью",
      "Я никогда не сидел в телефоне на семейном ужине",
      "Я никогда не видел северное сияние",
      "Я никогда не выигрывал спор, будучи неправым",
      "Я никогда не ходил на свидание вслепую",
      "Я никогда не прятался от соседей в подъезде",
      "Я никогда не притворялся, что читал книгу",
      "Я никогда не пытался повторить рецепт из TikTok",
      "Я никогда не учил танец по видео",
      "Я никогда не был на рыбалке",
      "Я никогда не терялся в чужом городе без интернета",
      "Я никогда не ломал телефон",
      "Я никогда не пел в душе так, что слышали соседи",
      "Я никогда не ел шашлык на завтрак",
      "Я никогда не ночевал в аэропорту",
      "Я никогда не заказывал еду дважды за день",
      "Я никогда не отправлял сообщение и сразу его удалял",
      "Я никогда не записывал видео для соцсетей больше 10 раз подряд",
      "Я никогда не притворялся, что понял шутку",
      "Я никогда не ходил в кино один",
      "Я никогда не говорил тост на свадьбе",
      "Я никогда не прыгал на батуте после 25 лет",
      "Я никогда не выгуливал чужую собаку",
      "Я никогда не забывал про день рождения близкого человека",
      "Я никогда не опаздывал на собственный праздник",
      "Я никогда не смотрел фильм ужасов один ночью",
      "Я никогда не покупал вещь, потому что она была со скидкой",
      "Я никогда не ел больше десяти баурсаков за раз",
      "Я никогда не был на Медеу",
      "Я никогда не поднимался на Кок-Тобе пешком",
      "Я никогда не спал больше 12 часов подряд",
      "Я никогда не работал в выходные ради денег",
      "Я никогда не стеснялся заказать то, что хочу",
      "Я никогда не выдавал чужую идею за свою",
      "Я никогда не писал любовное письмо от руки",
      "Я никогда не получал подарок, который сразу передарил",
      "Я никогда не записывался в зал и не ходил туда",
      "Я никогда не отправлял скриншот переписки тому, о ком она была",
      "Я никогда не ел то, что упало на пол",
      "Я никогда не смеялся так, что падал со стула",
      "Я никогда не выигрывал спортивный турнир",
      "Я никогда не сдавал экзамен без подготовки на отлично",
      "Я никогда не терял голос после концерта",
      "Я никогда не звонил не тому человеку ночью",
      "Я никогда не учил язык по приложению больше месяца",
      "Я никогда не был на Чарынском каньоне",
      "Я никогда не ездил в поезде больше суток",
      "Я никогда не прятал конфеты от семьи",
      "Я никогда не притворялся спящим",
      "Я никогда не говорил «я почти готов», будучи в пижаме",
      "Я никогда не выбирал фильм полчаса и так ничего не посмотрел",
      "Я никогда не записывал голосовое вместо звонка, чтобы не разговаривать",
      "Я никогда не стоял в очереди больше двух часов",
      "Я никогда не был на рок-концерте",
      "Я никогда не менял работу из-за начальника",
      "Я никогда не сочинял песню",
      "Я никогда не выходил из дома в тапочках по ошибке",
      "Я никогда не дарил подарок, который сделал сам",
      "Я никогда не брал в долг и забывал вернуть",
      "Я никогда не был волонтёром",
      "Я никогда не видел знаменитость вживую",
      "Я никогда не устраивал вечеринку-сюрприз",
      "Я никогда не выигрывал в настольную игру у всех друзей сразу",
      "Я никогда не терял обувь на вечеринке",
      "Я никогда не звонил в прямой эфир радио",
      "Я никогда не был в стране, язык которой совсем не знал",
      "Я никогда не ел суши палочками с первого раза правильно",
      "Я никогда не делал татуировку",
      "Я никогда не прокалывал уши или что-то ещё",
      "Я никогда не катался на сноуборде",
      "Я никогда не видел, как рождается котёнок или щенок",
      "Я никогда не выигрывал приз в конкурсе",
      "Я никогда не сидел в прямом эфире в соцсетях",
      "Я никогда не пробовал бешбармак руками",
      "Я никогда не ездил автостопом",
      "Я никогда не отвечал на звонок во сне",
      "Я никогда не ел плов руками",
      "Я никогда не покупал вещь, которую ни разу не надел",
      "Я никогда не засыпал на паре или совещании",
      "Я никогда не отвечал на звонок и молчал",
      "Я никогда не делал вид, что не заметил знакомого на улице",
      "Я никогда не пересматривал один фильм больше десяти раз",
      "Я никогда не писал письмо самому себе в будущее",
      "Я никогда не сжигал еду так, что срабатывала сигнализация",
      "Я никогда не звонил в службу поддержки больше часа",
      "Я никогда не менял имя в соцсетях ради шутки",
      "Я никогда не ел суши палочками с первого раза",
      "Я никогда не выигрывал в настольную игру у всей семьи",
      "Я никогда не засиживался в гостях до утра",
      "Я никогда не опаздывал на собственный день рождения",
      "Я никогда не путал двери в туалет",
      "Я никогда не кормил голубей с руки",
      "Я никогда не видел верблюда вживую",
      "Я никогда не бегал марафон",
      "Я никогда не заводил растение, которое выжило больше года",
      "Я никогда не записывался в спортзал и не ходил туда",
      "Я никогда не притворялся, что работаю, когда начальник проходил мимо",
      "Я никогда не пробовал бешбармак",
      "Я никогда не ночевал в палатке зимой",
      "Я никогда не выбирал фильм дольше, чем смотрел его",
      "Я никогда случайно не лайкал старое фото",
      "Я никогда не прятал сладкое от семьи",
      "Я никогда не разговаривал с котом как с человеком",
      "Я никогда не отправлял скриншот тому, о ком он был",
      "Я никогда не терял паспорт",
      "Я никогда не путал имена близнецов",
      "Я никогда не ел мороженое зимой на улице",
      "Я никогда не играл в компьютерную игру всю ночь",
      "Я никогда не отвечал преподавателю «я знал, но забыл»",
      "Я никогда не звонил не тому человеку посреди ночи",
      "Я никогда не ходил на свидание в кино и не смотрел фильм",
      "Я никогда не забывал, зачем пришёл в комнату",
      "Я никогда не ел целую пиццу один",
      "Я никогда не записывал подкаст",
      "Я никогда не вёл блог дольше месяца",
      "Я никогда не прыгал в воду с пирса",
      "Я никогда не летал на воздушном шаре",
      "Я никогда не ехал не в ту сторону на метро",
      "Я никогда не стоял в очереди за новым телефоном",
      "Я никогда не выбрасывал подарок, не распаковав его",
      "Я никогда не пел колыбельную взрослому",
      "Я никогда не узнавал о сюрпризе заранее",
      "Я никогда не терял друга в торговом центре",
      "Я никогда не просыпался в другом городе, не помня дороги",
      "Я никогда не играл на музыкальном инструменте на публике",
      "Я никогда не собирал мебель без инструкции",
      "Я никогда не оставлял лишние детали после сборки",
      "Я никогда не отправлял работу за минуту до дедлайна",
      "Я никогда не смотрел турецкий сериал",
      "Я никогда не спорил с навигатором вслух",
      "Я никогда не просил у бабушки добавки три раза",
      "Я никогда не надевал вещь наизнанку на весь день",
      "Я никогда не прокалывал уши",
      "Я никогда не пробовал острое блюдо и не жалел об этом",
      "Я никогда не ходил на квиз",
      "Я никогда не выигрывал квиз",
      "Я никогда не притворялся, что умею плавать",
      "Я никогда не терял кошелёк",
      "Я никогда не возвращался домой, потому что забыл выключить утюг",
      "Я никогда не видел падающую звезду",
      "Я никогда не загадывал желание на 11:11",
      "Я никогда не ходил на свидание, которое длилось меньше 15 минут",
      "Я никогда не переписывался с кем-то всю ночь",
      "Я никогда не звонил в радиоэфир",
      "Я никогда не попадал в кадр новостей",
      "Я никогда не стоял в пробке больше двух часов",
      "Я никогда не ел дыню на завтрак, обед и ужин",
      "Я никогда не собирал яблоки прямо с дерева",
      "Я никогда не видел, как рождается жеребёнок",
    ],
    pair: [
      "Придумайте гимн для двоих",
      "Найдите три общие вещи",
      "Сделайте драматичную позу дуэта",
      "Придумайте общее прозвище для вашей пары",
      "Нарисуйте друг друга за 30 секунд",
      "Станцуйте синхронно 15 секунд",
      "Расскажите историю, где каждый говорит по одному слову",
      "Покажите сценку «встреча старых друзей»",
      "Угадайте любимую еду друг друга",
      "Придумайте рекламу несуществующего товара",
      "Сделайте рукопожатие, которое никто не повторит",
      "Назовите по три комплимента друг другу",
      "Изобразите пару на первом свидании",
      "Придумайте стартап и его название за минуту",
      "Покажите пантомиму «перенос дивана по лестнице»",
      "Найдите одну вещь, которую вы оба ненавидите",
      "Сфотографируйтесь в стиле обложки альбома",
      "Придумайте короткий стих про компанию",
      "Угадайте любимый фильм друг друга с трёх попыток",
      "Изобразите ведущих утреннего шоу",
      "Придумайте блюдо из того, что есть на столе",
      "Покажите сценку «потерялись в аэропорту»",
      "Сделайте живую статую на 20 секунд",
      "Расскажите, где бы вы провели общий отпуск",
      "Придумайте песню из пяти слов",
      "Изобразите спортивных комментаторов матча между игроками",
      "Разыграйте продажу машины на базаре",
      "Найдите общее детское воспоминание",
      "Изобразите звёзд на красной дорожке",
      "Придумайте тост для всей компании",
      "Покажите «зеркало»: один двигается, второй повторяет",
      "Угадайте, сколько пальцев покажет партнёр",
      "Изобразите путешественников во времени",
      "Придумайте правило, которое ввели бы для всех тус",
      "Изобразите двух котов, которые делят место на диване",
      "Скажите одновременно, не сговариваясь, любимое время года",
      "Придумайте название для совместной группы",
      "Разыграйте звонок в службу поддержки",
      "Сделайте общий сэлфи с самой странной гримасой",
      "Назовите пять городов на одну букву по очереди",
      "Изобразите экскурсию по Алматы",
      "Придумайте новый вид спорта",
      "Покажите сценку «родители узнают о вечеринке»",
      "Сыграйте в «камень, ножницы, бумага» до трёх побед",
      "Опишите друг друга одним словом",
      "Придумайте свой праздник и как его отмечать",
      "Изобразите двух роботов, которые учатся танцевать",
      "Спойте любую песню дуэтом",
      "Назовите по очереди 10 фруктов без повторов",
      "Разыграйте интервью со звездой",
    ],
  },
  en: {
    truth: [
      "What is your most underrated skill?",
      "Who here would plan the best trip?",
      "What song always lifts your mood?",
      "What is the strangest thing you have ever eaten?",
      "What childhood dream makes you laugh now?",
      "Which movie have you rewatched the most?",
      "What is your most awkward school memory?",
      "Who here would you trust with your phone for a day?",
      "What is your weirdest habit?",
      "What would you do if you won a million?",
      "What lie do you tell most often?",
      "What was your first job?",
      "Which app do you open most often?",
      "What was the last thing you googled?",
      "What is the silliest thing you have argued about?",
      "Which celebrity was your childhood crush?",
      "Which superpower would you pick and why?",
      "What dish do you cook best?",
      "When did a movie last make you cry?",
      "What annoys you most in people?",
      "What item would you never throw away?",
      "What is the bravest thing you have done?",
      "What would you change in your past if you could?",
      "What was your childhood nickname?",
      "Who here have you known the longest?",
      "What are you afraid of even though it is silly?",
      "What is the best gift you have ever received?",
      "What was the worst gift you have received?",
      "Who would you take to a desert island?",
      "What is your go-to karaoke song?",
      "What do you do when nobody is watching?",
      "Which series did you binge-watch?",
      "What was your worst outfit ever?",
      "What trait do you like most about yourself?",
      "What would you like to learn but feel shy to start?",
      "Who is your idol and why?",
      "When did you feel truly embarrassed?",
      "What is the strangest place you have slept?",
      "What is the longest trip you made for someone?",
      "Which emoji describes you best?",
      "What have you been putting off for over a month?",
      "Which purchase do you regret?",
      "What advice would you give your 15-year-old self?",
      "Who here is the funniest?",
      "Who here is late most often?",
      "What is the strangest dream you remember?",
      "Which city do you most want to visit?",
      "What do you eat when you are sad?",
      "Which rule have you broken the most?",
      "Which smell reminds you of childhood?",
      "Which celebrity would you invite to this party?",
      "When did you last lie to skip an event?",
      "What is the first thing you would do if you were invisible?",
      "What is the most expensive dinner you have had?",
      "Which game do you lose most often?",
      "What surprised you about yourself this year?",
      "What is the longest you have stayed awake?",
      "Which phrase do you say too often?",
      "Who here dances best?",
      "Which hobby did you quit fastest?",
      "Which job would you choose if you started over?",
      "What is the oldest thing in your room?",
      "What did you hide from your parents the longest?",
      "What was your most awkward date moment?",
      "What is your favorite tradition?",
      "Who here would survive a zombie apocalypse first?",
      "What would make you leave a party first?",
      "What is the most spontaneous thing you have done?",
      "What do you keep buying again and again?",
      "Which moment of your life would you relive?",
      "What did you think of the person on your left when you first met?",
      "What skill did you learn from YouTube?",
      "Which song are you embarrassed to love?",
      "Who here gives the best advice?",
      "What was your biggest fail?",
      "What does your perfect Sunday look like?",
      "Which word did you mispronounce for years?",
      "What do you argue about with friends most?",
      "What is your strongest superstition?",
      "Which compliment do you still remember?",
      "When did you last dance alone at home?",
      "Who is the funniest person in your family?",
      "What was your first phone?",
      "How many unread messages do you have right now?",
      "What would you do with a surprise week off?",
      "Which food do you love that most people hate?",
      "Who here keeps secrets best?",
      "What is the craziest thing you have done for love?",
      "What would your perfect birthday look like?",
      "Which movie role could you play with no rehearsal?",
      "What trait attracts you in people?",
      "Which book do you recommend to everyone?",
      "What would you never do even for money?",
      "If you were a dish, what would you be?",
      "Which moment of this party will you remember?",
      "What is your favorite weather?",
      "What do you usually order at a coffee shop?",
      "What do you watch to fall asleep?",
      "Who taught you the most important lesson?",
      "Which useless skill of yours is still cool?",
      "Which country did you visit last?",
      "Which sound annoys you most?",
      "Who here is on their phone the most?",
      "What was the hardest part of this year?",
      "Which era would you like to visit?",
      "What was the weirdest interview question you got?",
      "Are you a night owl or an early bird, and why?",
      "Who would you call first in an emergency?",
      "What is your favorite meme?",
      "How many alarms do you set in the morning?",
      "Which animal is most like you?",
      "What would you tell yourself in ten years?",
      "What do you always forget at home?",
      "What is your biggest travel fear?",
      "Who here cooks best?",
      "What is the funniest thing that happened in a taxi?",
      "What is the first thing you do in the morning?",
      "Who have you wanted to text but haven't?",
      "What would you do if you woke up as someone else?",
      "Which celebrity do you find overrated?",
      "What small thing do you appreciate most?",
      "How do you usually pick a movie for the night?",
      "Which word describes this group?",
    ],
    dare: [
      "Invent a 10-second dance move",
      "Give a sincere compliment to the person on your right",
      "Narrate this party like a movie trailer",
      "Sing a verse of your favorite song",
      "Act out an animal until everyone guesses",
      "Tell a joke with a straight face",
      "Speak with an accent until your next turn",
      "Show the last photo in your gallery",
      "Do 10 squats",
      "Read your last sent message aloud",
      "Impersonate a celebrity and let others guess",
      "Play a song and dance for 20 seconds",
      "Draw the person next to you in 30 seconds",
      "Take a selfie with your funniest face",
      "Say a tongue twister three times in a row",
      "Act out a robot falling in love",
      "Give a toast to the host",
      "Walk across the room like a runway model",
      "Describe your day like a sports commentator",
      "Act out a breakup with a pillow",
      "Speak only in questions for two minutes",
      "Show how you dance at a wedding",
      "Act out a cat seeing a cucumber",
      "Make up a rap about the person on your left",
      "Hold a plank for 30 seconds",
      "Send a friend a voice message in opera style",
      "Tell a story where every word starts with the same letter",
      "Act out waking up on a Monday",
      "Teach everyone your signature gesture",
      "Show the best dance move from the 2000s",
      "Pitch an ordinary spoon like a TV ad",
      "Compliment everyone in the room",
      "Swap seats with any player",
      "Speak like a news anchor for one minute",
      "Impersonate your favorite cartoon character",
      "Strike a magazine cover pose",
      "Recite a poem like the drama of the century",
      "Act out an athlete in slow motion",
      "Describe yourself like a product on a marketplace",
      "Try a handstand against the wall",
      "Sing Happy Birthday in your own style",
      "Act out ordering coffee in a hurry",
      "Come up with a new name for this party",
      "Make the sound of an object and let others guess",
      "Dance to a song your neighbor picks",
      "Hold eye contact with your neighbor for five seconds without laughing",
      "Show your best villain laugh",
      "Describe your favorite dish without naming it",
      "Imitate a GPS voice",
      "Compliment yourself like your best friend would",
      "Show how you photograph food",
      "Act out missing a flight",
      "Act out a first date between two penguins",
      "Do 30 seconds of stand-up",
      "Act out searching for keys before leaving",
      "Say a tongue twister with a mouthful of water",
      "Show the slowest dance in the world",
      "Draw a house with your eyes closed",
      "Recreate a famous movie scene",
      "Invent a slogan for this group",
      "Show how you would host a cooking show",
      "Act out someone seeing snow for the first time",
      "Play an air guitar solo",
      "Give five compliments in a row without repeating",
      "Act out persuading a cat off the table",
      "Tell your day backwards",
      "Hold a yoga pose for 15 seconds",
      "Act out a blogger unboxing a gift",
      "Say thank you in five languages",
      "Whisper a secret to your neighbor",
      "Show your reaction to winning the lottery",
      "Dance any folk dance",
      "Act out riding a packed bus",
      "Tell a story using three words the players give you",
      "Speak like a cartoon character until the round ends",
      "Show your favorite gym exercise",
      "Conduct an imaginary orchestra to any song",
      "Pretend you are a wedding host",
      "Draw yourself as a superhero",
      "Act out bargaining at a bazaar",
      "Do the chicken dance",
      "Show how you sneak food from the fridge at night",
      "Act out a robot vacuum that got stuck",
      "Give every player a nickname",
      "Act out a footballer celebrating a goal",
      "Tell your perfect day like a fairy tale",
      "Act out a shampoo commercial model",
      "Sing any song replacing the words with meow",
      "Show how you dance when nobody is watching",
      "Give a tour of this room like a guide",
      "Balance a spoon on your nose for five seconds",
      "Act out tasting something very spicy for the first time",
      "Compliment the person you have talked to least",
      "Start a hand wave with everyone",
      "Act out losing signal on a phone call",
      "Strike your most dramatic photo pose",
      "Share what you are grateful for today",
      "Act out greeting a food delivery courier",
      "Try some breakdance moves",
      "Act out a dinosaur taking a selfie",
      "Act out falling asleep in a meeting",
      "Whisper-sing the chorus of any song",
      "Show how you celebrate Friday",
      "Act out a detective finding the culprit among players",
      "Lead the players in a conga line around the room",
      "Act out ice skating for the first time",
      "Lead a minute of applause for the quietest player",
      "Act out a grandma using a smartphone for the first time",
      "Invent a new greeting for the group",
    ],
    never: [
      "Never have I ever forgotten someone's name mid-conversation",
      "Never have I ever texted the wrong person",
      "Never have I ever pretended to know a song",
      "Never have I ever fallen asleep at the cinema",
      "Never have I ever missed a flight",
      "Never have I ever sung karaoke",
      "Never have I ever faked being sick to skip work or school",
      "Never have I ever lost my keys twice in one week",
      "Never have I ever finished a series in one weekend",
      "Never have I ever eaten cake straight from the box",
      "Never have I ever fallen on ice in public",
      "Never have I ever called my mom for a recipe",
      "Never have I ever gone skydiving",
      "Never have I ever stood in the front row at a concert",
      "Never have I ever dyed my hair",
      "Never have I ever said I am leaving while still in bed",
      "Never have I ever gone camping in a tent",
      "Never have I ever ridden a horse",
      "Never have I ever watched a sunrise in the mountains",
      "Never have I ever lost my phone in a taxi",
      "Never have I ever laughed at the wrong moment",
      "Never have I ever won a lottery",
      "Never have I ever cooked something nobody could eat",
      "Never have I ever been to Shymbulak",
      "Never have I ever swum in a mountain river",
      "Never have I ever gotten lost in a shopping mall",
      "Never have I ever faked a phone call to escape a conversation",
      "Never have I ever deleted a photo because I looked bad",
      "Never have I ever set more than five alarms",
      "Never have I ever mixed up left and right while navigating",
      "Never have I ever danced on a table",
      "Never have I ever attended a wedding with over 300 guests",
      "Never have I ever tried kumis",
      "Never have I ever sent a voice message longer than five minutes",
      "Never have I ever cried over a cartoon",
      "Never have I ever cancelled plans last minute to sleep",
      "Never have I ever performed on stage",
      "Never have I ever traveled alone",
      "Never have I ever eaten somewhere without understanding the menu",
      "Never have I ever quit a new hobby after a week",
      "Never have I ever overslept an exam",
      "Never have I ever gotten a parking ticket",
      "Never have I ever said I am on a diet while holding cake",
      "Never have I ever texted an ex at night",
      "Never have I ever scrolled my phone at a family dinner",
      "Never have I ever seen the northern lights",
      "Never have I ever won an argument while being wrong",
      "Never have I ever been on a blind date",
      "Never have I ever hidden from neighbors in the stairwell",
      "Never have I ever pretended to have read a book",
      "Never have I ever tried a TikTok recipe",
      "Never have I ever learned a dance from a video",
      "Never have I ever gone fishing",
      "Never have I ever been lost in a new city without internet",
      "Never have I ever broken a phone",
      "Never have I ever sung in the shower loud enough for neighbors to hear",
      "Never have I ever eaten kebab for breakfast",
      "Never have I ever spent a night in an airport",
      "Never have I ever ordered delivery twice in one day",
      "Never have I ever sent a message and deleted it right away",
      "Never have I ever reshot a social video more than ten times",
      "Never have I ever pretended to get a joke",
      "Never have I ever gone to the movies alone",
      "Never have I ever given a wedding toast",
      "Never have I ever jumped on a trampoline after 25",
      "Never have I ever walked someone else's dog",
      "Never have I ever forgotten a loved one's birthday",
      "Never have I ever been late to my own celebration",
      "Never have I ever watched a horror movie alone at night",
      "Never have I ever bought something just because it was on sale",
      "Never have I ever eaten more than ten baursaks at once",
      "Never have I ever been to Medeu",
      "Never have I ever walked up Kok-Tobe",
      "Never have I ever slept more than 12 hours straight",
      "Never have I ever worked a weekend just for the money",
      "Never have I ever been too shy to order what I want",
      "Never have I ever passed off someone's idea as mine",
      "Never have I ever written a love letter by hand",
      "Never have I ever regifted a present",
      "Never have I ever paid for a gym and never went",
      "Never have I ever sent a screenshot to the person it was about",
      "Never have I ever eaten food off the floor",
      "Never have I ever laughed so hard I fell off a chair",
      "Never have I ever won a sports tournament",
      "Never have I ever aced an exam without studying",
      "Never have I ever lost my voice after a concert",
      "Never have I ever called the wrong person at night",
      "Never have I ever kept a language app streak over a month",
      "Never have I ever been to Charyn Canyon",
      "Never have I ever been on a train for over a day",
      "Never have I ever hidden sweets from my family",
      "Never have I ever pretended to be asleep",
      "Never have I ever said almost ready while in pajamas",
      "Never have I ever spent 30 minutes picking a movie and watched nothing",
      "Never have I ever sent a voice note to avoid a call",
      "Never have I ever queued for more than two hours",
      "Never have I ever been to a rock concert",
      "Never have I ever quit a job because of a boss",
      "Never have I ever written a song",
      "Never have I ever left home in slippers by accident",
      "Never have I ever given a handmade gift",
      "Never have I ever borrowed something and forgot to return it",
      "Never have I ever volunteered",
      "Never have I ever seen a celebrity in person",
      "Never have I ever thrown a surprise party",
      "Never have I ever beaten all my friends at a board game",
      "Never have I ever lost a shoe at a party",
      "Never have I ever called into a live radio show",
      "Never have I ever visited a country without knowing a word of the language",
      "Never have I ever used chopsticks correctly on the first try",
      "Never have I ever gotten a tattoo",
      "Never have I ever gotten a piercing",
      "Never have I ever snowboarded",
      "Never have I ever seen a kitten or puppy being born",
      "Never have I ever won a contest prize",
      "Never have I ever gone live on social media",
      "Never have I ever eaten beshbarmak with my hands",
      "Never have I ever hitchhiked",
      "Never have I ever answered a call while asleep",
      "Never have I ever eaten pilaf with my hands",
      "Never have I ever been to the Medeu skating rink",
      "Never have I ever walked all the way up Kok-Tobe",
      "Never have I ever bought clothes I never wore",
      "Never have I ever fallen asleep in class or a meeting",
      "Never have I ever picked up a call and said nothing",
      "Never have I ever pretended not to see someone I know on the street",
      "Never have I ever rewatched a movie more than ten times",
      "Never have I ever written a letter to my future self",
      "Never have I ever gone snowboarding",
      "Never have I ever burned food bad enough to set off the alarm",
      "Never have I ever spent over an hour on a support call",
      "Never have I ever changed my social media name as a joke",
      "Never have I ever managed sushi with chopsticks on the first try",
      "Never have I ever beaten my whole family at a board game",
      "Never have I ever stayed at a friend's place until morning",
      "Never have I ever been late to my own birthday party",
      "Never have I ever walked into the wrong restroom",
      "Never have I ever fed pigeons from my hand",
      "Never have I ever seen a camel in real life",
      "Never have I ever run a marathon",
      "Never have I ever kept a plant alive for over a year",
      "Never have I ever signed up for a gym and never gone",
      "Never have I ever pretended to work when the boss walked by",
      "Never have I ever tried beshbarmak",
      "Never have I ever slept in a tent in winter",
      "Never have I ever spent longer choosing a movie than watching it",
      "Never have I ever accidentally liked an old photo",
      "Never have I ever talked to a cat like a person",
      "Never have I ever lost my passport",
      "Never have I ever mixed up twins' names",
      "Never have I ever eaten ice cream outside in winter",
      "Never have I ever gamed all night",
      "Never have I ever told a teacher \"I knew it but forgot\"",
      "Never have I ever won a prize in a contest",
      "Never have I ever called the wrong person in the middle of the night",
      "Never have I ever gone on a movie date and missed the movie",
      "Never have I ever forgotten why I walked into a room",
      "Never have I ever eaten a whole pizza by myself",
      "Never have I ever recorded a podcast",
      "Never have I ever kept a blog going for over a month",
      "Never have I ever jumped into water from a pier",
      "Never have I ever ridden in a hot air balloon",
      "Never have I ever taken the metro in the wrong direction",
      "Never have I ever queued for a new phone",
      "Never have I ever thrown out a gift without opening it",
      "Never have I ever sung a lullaby to an adult",
      "Never have I ever found out about a surprise in advance",
      "Never have I ever lost a friend in a mall",
      "Never have I ever woken up in another city without remembering the trip",
      "Never have I ever played an instrument in public",
      "Never have I ever eaten food that fell on the floor",
      "Never have I ever built furniture without the instructions",
      "Never have I ever had spare parts left after assembly",
      "Never have I ever submitted work a minute before the deadline",
      "Never have I ever watched a Turkish TV series",
      "Never have I ever argued out loud with a GPS",
      "Never have I ever asked grandma for thirds",
      "Never have I ever worn something inside out all day",
      "Never have I ever had my ears pierced",
      "Never have I ever tried a spicy dish and not regretted it",
      "Never have I ever gone to a pub quiz",
      "Never have I ever won a pub quiz",
      "Never have I ever pretended I could swim",
      "Never have I ever lost my wallet",
      "Never have I ever gone back home to check the iron",
      "Never have I ever seen a shooting star",
      "Never have I ever made a wish at 11:11",
      "Never have I ever been on a date that lasted under 15 minutes",
      "Never have I ever texted someone all night",
      "Never have I ever called in to a radio show",
      "Never have I ever appeared in a news shot",
      "Never have I ever been stuck in traffic for over two hours",
      "Never have I ever spent over a day on a train",
      "Never have I ever eaten melon for breakfast, lunch and dinner",
      "Never have I ever picked apples straight from the tree",
      "Never have I ever seen a foal being born",
    ],
    pair: [
      "Create a two-person anthem",
      "Find three things you have in common",
      "Strike a dramatic duo pose",
      "Invent a nickname for your duo",
      "Draw each other in 30 seconds",
      "Dance in sync for 15 seconds",
      "Tell a story one word each",
      "Act out old friends meeting again",
      "Guess each other's favorite food",
      "Pitch a product that does not exist",
      "Invent a secret handshake",
      "Give each other three compliments",
      "Act out a couple on a first date",
      "Invent a startup and its name in one minute",
      "Mime carrying a sofa up the stairs",
      "Find one thing you both hate",
      "Pose like an album cover",
      "Write a short poem about the group",
      "Guess each other's favorite movie in three tries",
      "Act out morning show hosts",
      "Invent a dish from what is on the table",
      "Act out getting lost in an airport",
      "Be a living statue for 20 seconds",
      "Plan a vacation together",
      "Make up a five-word song",
      "Commentate a match between two players",
      "Act out selling a car at a bazaar",
      "Find a shared childhood memory",
      "Act out celebrities on a red carpet",
      "Make up a toast for the whole group",
      "Mirror game: one moves, the other copies",
      "Guess how many fingers your partner will show",
      "Act out time travelers",
      "Invent a rule for every party",
      "Act out two cats fighting over the sofa",
      "Say your favorite season at the same time",
      "Name your band",
      "Act out a customer support call",
      "Take a joint selfie with the weirdest faces",
      "Name five cities starting with the same letter, taking turns",
      "Give a tour of Almaty together",
      "Invent a new sport",
      "Act out parents finding out about the party",
      "Play rock-paper-scissors to three wins",
      "Describe each other in one word",
      "Invent a holiday and how to celebrate it",
      "Act out two robots learning to dance",
      "Sing any song as a duet",
      "Name ten fruits in turns without repeats",
      "Act out a celebrity interview",
    ],
  },
} as const satisfies Record<"ru" | "en", Record<"truth" | "dare" | "never" | "pair", readonly string[]>>;
