"use client";
import { useEffect, useState } from "react";
import { useUser } from "@clerk/nextjs";
import { useLocale } from "@/app/components/LocaleProvider";
import { useStageGame } from "@/app/components/useStageGame";
import { useControllerGame } from "@/app/components/useControllerGame";
type State={phase:"lobby"|"play"|"judge"|"result";players:string[];prompt:string;hands:Record<string,string[]>;submissions:Record<string,string>;judgeIndex:number;winner:string;scores:Record<string,number>;round:number};
const P={ru:["Худший способ познакомиться — это ___","На следующую тусу я принесу ___","Мой секретный талант — ___","Нас спасло только ___"],en:["The worst way to meet someone is ___","At the next party I'll bring ___","My secret talent is ___","The only thing that saved us was ___"]};const C={ru:["танец у холодильника","очень подозрительный плов","голосовое на 12 минут","мамин тапок","караоке без музыки","пакет пакетов","последний кусок пиццы","легендарный сосед"],en:["a fridge dance","suspicious pilaf","a 12-minute voice note","mom's slipper","karaoke without music","a bag of bags","the last pizza slice","a legendary neighbour"]};
const initial=():State=>({phase:"lobby",players:[],prompt:"",hands:{},submissions:{},judgeIndex:0,winner:"",scores:{},round:0});
export default function CardsOfChaos({sessionId,onSave,role}:{partyId:string;sessionId?:string|null;onSave:(score:number)=>void;role?:"stage"|"controller"}){const{user}=useUser();const me=user?.id??"";const{locale}=useLocale();const ru=locale==="ru";const host=role==="stage";const stage=useStageGame<State>(host?sessionId??null:null,initial);const controller=useControllerGame<State>(!host?sessionId??null:null,initial());const state=host?stage.state:controller.state;const send=host?stage.sendAction:controller.sendAction;const set=host?stage.setState:undefined;const actions=host?stage.playerActions:[];const clear=host?stage.clearActions:undefined;const[picked,setPicked]=useState("");
const deal=(players:string[],round:number,scores:Record<string,number>,judgeIndex:number)=>{const cards=C[ru?"ru":"en"];const hands:Record<string,string[]>={};players.forEach((id,i)=>hands[id]=Array.from({length:4},(_,n)=>cards[(i*3+n+round)%cards.length]));return{phase:"play" as const,players,prompt:P[ru?"ru":"en"][round%P.en.length],hands,submissions:{},judgeIndex,winner:"",scores,round}};
useEffect(()=>{if(!host||!actions.length)return;for(const a of actions){if(a.actionType==="join"&&state.phase==="lobby")set?.(p=>({...p,players:p.players.includes(a.userId)?p.players:[...p.players,a.userId]}));if(a.actionType==="submit"&&state.phase==="play"&&a.userId!==state.players[state.judgeIndex])set?.(p=>({...p,submissions:{...p.submissions,[a.userId]:String((a.payload as {card?:string}).card??"")}}));if(a.actionType==="judge"&&state.phase==="judge"&&a.userId===state.players[state.judgeIndex]){const winner=String((a.payload as {winner?:string}).winner??"");set?.(p=>({...p,phase:"result",winner,scores:{...p.scores,[winner]:(p.scores[winner]??0)+1}}))}}clear?.()},[actions,clear,host,set,state.judgeIndex,state.phase,state.players]);
useEffect(()=>{if(host&&state.phase==="play"&&state.players.length>1&&Object.keys(state.submissions).length>=state.players.length-1)set?.(p=>({...p,phase:"judge"}))},[host,set,state.phase,state.players.length,state.submissions]);const judge=state.players[state.judgeIndex];const next=()=>{const round=state.round+1;if(round>=5){stage.complete();onSave(Math.max(0,...Object.values(state.scores)));return}set?.(()=>deal(state.players,round,state.scores,(state.judgeIndex+1)%state.players.length))};
return <div className="party-game-board game-board-enter"><span className="game-step">Cards of Chaos · {state.phase}</span>{state.phase==="lobby"&&<><h3>{ru?"Собираем самую хаотичную колоду":"Building the chaos deck"}</h3><p>{state.players.length} {ru?"игроков":"players"}</p>{host&&<button className="demo-action demo-action--lime" disabled={state.players.length<3} onClick={()=>set?.(()=>deal(state.players,0,{},0))} type="button">{ru?"Раздать":"Deal"}</button>}</>}{state.phase!=="lobby"&&<><h3>{state.prompt}</h3><p>{judge===me?(ru?"Ты судья этого раунда":"You are the judge"):`${ru?"Судья":"Judge"}: ${judge?.slice(-6)}`}</p>{state.phase==="play"&&judge!==me&&<div className="chaos-hand">{(state.hands[me]??[]).map(card=><button className={picked===card?"active":""} key={card} onClick={()=>{setPicked(card);send("submit",{card})}} disabled={Boolean(picked)} type="button">{card}</button>)}</div>}{state.phase==="play"&&judge===me&&<p>{ru?"Ждём карты игроков":"Waiting for player cards"}</p>}{state.phase==="judge"&&judge===me&&<div className="chaos-hand">{Object.entries(state.submissions).map(([id,card])=><button key={id} onClick={()=>send("judge",{winner:id})} type="button">{card}</button>)}</div>}{state.phase==="judge"&&judge!==me&&<p>{ru?"Судья выбирает лучший ответ":"The judge is choosing"}</p>}{state.phase==="result"&&<><h3>{ru?"Победитель раунда":"Round winner"}: {state.winner.slice(-6)}</h3>{host&&<button className="demo-action demo-action--lime" onClick={next} type="button">{state.round>=4?(ru?"Завершить":"Finish"):(ru?"Следующий раунд":"Next round")}</button>}</>}</>}{sessionId&&<span className="multiplayer-badge">LIVE</span>}</div>}
