"use client";

import type { PointerEvent } from "react";
import { useEffect, useRef, useState } from "react";
import { useControllerGame } from "@/app/components/useControllerGame";
import { useStageGame } from "@/app/components/useStageGame";

type Point={x:number;y:number;draw:boolean}; type State={phase:"lobby"|"prompt"|"draw"|"guess"|"reveal"|"finished";players:string[];assignments:Record<string,string>;drawings:Record<string,Point[]>;guesses:Record<string,string>;revealIndex:number;scores:Record<string,number>;privatePrompt?:string;privateDrawing?:Point[];viewerId?:string}; const empty=():State=>({phase:"lobby",players:[],assignments:{},drawings:{},guesses:{},revealIndex:0,scores:{}}); const path=(points:Point[])=>points.reduce((value,item)=>`${value}${item.draw?" L":" M"}${item.x} ${item.y}`,"");

export default function GarticPhone({sessionId,onSave,role}:{partyId:string;sessionId?:string|null;onSave:(score:number)=>void;role?:"stage"|"controller"}) { const stageRole=role==="stage";const stage=useStageGame<State>(stageRole?sessionId??null:null,empty);const controller=useControllerGame<State>(!stageRole?sessionId??null:null,empty());const state=stageRole?stage.state:controller.state;const send=stageRole?stage.sendAction:controller.sendAction;const[prompt,setPrompt]=useState("");const[guess,setGuess]=useState("");const drawing=useRef(false);const pending=useRef<Point[]>([]);const completed=useRef(false);const me=state.viewerId??"";const own=state.drawings[me]??[];const reveal=state.players[state.revealIndex]??"";
useEffect(()=>{if(!stageRole||state.phase!=="finished"||completed.current)return;completed.current=true;stage.complete();onSave(Math.max(0,...Object.values(state.scores)))},[onSave,stage,stageRole,state.phase,state.scores]);
const point=(event:PointerEvent<SVGSVGElement>,draw:boolean)=>{if(state.phase!=="draw")return;const rect=event.currentTarget.getBoundingClientRect();pending.current.push({x:Math.round((event.clientX-rect.left)/rect.width*600),y:Math.round((event.clientY-rect.top)/rect.height*360),draw});if(pending.current.length>=5||!draw){send("stroke",{points:pending.current});pending.current=[];}};
return <section className="party-game-board game-board-enter drawing-game"><span className="game-step">DRAW CHAIN · {state.phase}</span>{state.phase==="lobby"&&<><h3>Фраза превращается в рисунок и новую фразу</h3><p>Игроков: {state.players.length}</p>{stageRole&&<button className="demo-action demo-action--lime" onClick={()=>send("start")} type="button">Начать</button>}</>}{state.phase==="prompt"&&!stageRole&&<div className="bs-input-group"><input className="bs-input" value={prompt} onChange={(event)=>setPrompt(event.target.value)} placeholder="Придумай фразу"/><button className="demo-action demo-action--lime" onClick={()=>{if(prompt.trim()){send("prompt",{text:prompt.trim()});setPrompt("")}}} type="button">Отправить</button></div>}{state.phase==="draw"&&!stageRole&&<><h3>{state.privatePrompt||"Ждём задание"}</h3><svg className="drawing-canvas" viewBox="0 0 600 360" onPointerDown={(event)=>{drawing.current=true;point(event,false)}} onPointerMove={(event)=>{if(drawing.current)point(event,true)}} onPointerUp={(event)=>{drawing.current=false;point(event,false)}}><path d={path(own)} fill="none" stroke="currentColor" strokeWidth="7" strokeLinecap="round"/></svg><button className="demo-action demo-action--lime" onClick={()=>send("drawingDone")} type="button">Готово</button></>}{state.phase==="guess"&&!stageRole&&<><svg className="drawing-canvas" viewBox="0 0 600 360"><path d={path(state.privateDrawing??[])} fill="none" stroke="currentColor" strokeWidth="7" strokeLinecap="round"/></svg><div className="bs-input-group"><input className="bs-input" value={guess} onChange={(event)=>setGuess(event.target.value)} placeholder="Что здесь нарисовано?"/><button className="demo-action demo-action--lime" onClick={()=>{if(guess.trim()){send("guess",{text:guess.trim()});setGuess("")}}} type="button">Угадать</button></div></>}{["prompt","draw","guess"].includes(state.phase)&&stageRole&&<p>Ждём ходы участников…</p>}{state.phase==="reveal"&&<><h3>Цепочка #{state.revealIndex+1}</h3><svg className="drawing-canvas" viewBox="0 0 600 360"><path d={path(state.drawings[reveal]??[])} fill="none" stroke="currentColor" strokeWidth="7" strokeLinecap="round"/></svg><p>{state.guesses[reveal]??"—"}</p>{stageRole&&<button className="demo-action demo-action--lime" onClick={()=>send("advance")} type="button">{state.revealIndex>=state.players.length-1?"Завершить":"Дальше"}</button>}</>}{sessionId&&<span className="multiplayer-badge">LIVE</span>}</section>; }
