"use client";

import { PointerEvent, useEffect, useRef, useState } from "react";
import { useUser } from "@clerk/nextjs";
import { useLocale } from "@/app/components/LocaleProvider";
import { useStageGame } from "@/app/components/useStageGame";
import { useControllerGame } from "@/app/components/useControllerGame";
type Point={x:number;y:number;draw:boolean}; type State={phase:"lobby"|"prompt"|"draw"|"guess"|"reveal"|"finished";players:string[];prompts:Record<string,string>;assignments:Record<string,string>;drawings:Record<string,Point[]>;guesses:Record<string,string>;revealIndex:number;scores:Record<string,number>};
const initial=():State=>({phase:"lobby",players:[],prompts:{},assignments:{},drawings:{},guesses:{},revealIndex:0,scores:{}});
export default function GarticPhone({sessionId,onSave,role}:{partyId:string;sessionId?:string|null;onSave:(score:number)=>void;role?:"stage"|"controller"}){const{user}=useUser();const me=user?.id??"";const{t}=useLocale();const host=role==="stage";const stage=useStageGame<State>(host?sessionId??null:null,initial);const controller=useControllerGame<State>(!host?sessionId??null:null,initial());const state=host?stage.state:controller.state;const send=host?stage.sendAction:controller.sendAction;const set=host?stage.setState:undefined;const actions=host?stage.playerActions:[];const clear=host?stage.clearActions:undefined;const[prompt,setPrompt]=useState("");const[guess,setGuess]=useState("");const drawing=useRef(false);const pending=useRef<Point[]>([]);
useEffect(()=>{if(!host||!actions.length)return;for(const a of actions){if(a.actionType==="join"&&state.phase==="lobby")set?.(p=>({...p,players:p.players.includes(a.userId)?p.players:[...p.players,a.userId]}));if(a.actionType==="prompt"&&state.phase==="prompt")set?.(p=>({...p,prompts:{...p.prompts,[a.userId]:String((a.payload as {text?:string}).text??"").slice(0,80)}}));if(a.actionType==="stroke"&&state.phase==="draw")set?.(p=>({...p,drawings:{...p.drawings,[a.userId]:[...(p.drawings[a.userId]??[]),...((a.payload as {points?:Point[]}).points??[])].slice(-2200)}}));if(a.actionType==="drawingDone"&&state.phase==="draw")set?.(p=>({...p,guesses:{...p.guesses,[`done:${a.userId}`]:"1"}}));if(a.actionType==="guess"&&state.phase==="guess")set?.(p=>({...p,guesses:{...p.guesses,[a.userId]:String((a.payload as {text?:string}).text??"").slice(0,80)}}));}clear?.()},[actions,clear,host,set,state.phase]);
useEffect(()=>{if(!host)return;if(state.phase==="prompt"&&state.players.length>1&&Object.keys(state.prompts).length>=state.players.length){const assignments:Record<string,string>={};state.players.forEach((id,i)=>assignments[id]=state.players[(i+1)%state.players.length]);set?.(p=>({...p,phase:"draw",assignments,drawings:{},guesses:{}}))}if(state.phase==="draw"&&state.players.every(id=>state.guesses[`done:${id}`]))set?.(p=>({...p,phase:"guess",guesses:{}}));if(state.phase==="guess"&&Object.keys(state.guesses).length>=state.players.length)set?.(p=>({...p,phase:"reveal",revealIndex:0}))},[host,set,state]);
const point=(e:PointerEvent<SVGSVGElement>,draw:boolean)=>{if(state.phase!=="draw")return;const r=e.currentTarget.getBoundingClientRect();pending.current.push({x:Math.round((e.clientX-r.left)/r.width*600),y:Math.round((e.clientY-r.top)/r.height*360),draw});if(pending.current.length>=5||!draw){send("stroke",{points:pending.current});pending.current=[]}};const mySource=state.assignments[me];const myPrompt=state.prompts[mySource]??"";const myDrawing=state.drawings[mySource]??[];const ownPath=(state.drawings[me]??[]).reduce((v,p)=>`${v}${p.draw?" L":" M"}${p.x} ${p.y}`,"");const revealId=state.players[state.revealIndex];const revealPath=(state.drawings[revealId]??[]).reduce((v,p)=>`${v}${p.draw?" L":" M"}${p.x} ${p.y}`,"");
return <div className="party-game-board game-board-enter drawing-game"><span className="game-step">Gartic Phone · {state.phase}</span>{state.phase==="lobby"&&<>{<h3>{t("garticDesc")}</h3>}<p>{state.players.length} {t("garticPlayers")}</p>{host&&<button className="demo-action demo-action--lime" disabled={state.players.length<3} onClick={()=>set?.(p=>({...p,phase:"prompt"}))} type="button">{t("garticStart")}</button>}</>}{state.phase==="prompt"&&!host&&<div className="bs-input-group"><input className="bs-input" value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder={t("garticPhrasePlace")}/><button className="demo-action demo-action--lime" onClick={()=>{send("prompt",{text:prompt});setPrompt("")}} type="button">{t("garticSend")}</button></div>}{state.phase==="draw"&&!host&&<><h3>{myPrompt}</h3><svg className="drawing-canvas" viewBox="0 0 600 360" onPointerDown={e=>{drawing.current=true;point(e,false)}} onPointerMove={e=>{if(drawing.current)point(e,true)}} onPointerUp={e=>{drawing.current=false;point(e,false)}}><path d={ownPath} fill="none" stroke="currentColor" strokeWidth="7" strokeLinecap="round"/></svg><button className="demo-action demo-action--lime" onClick={()=>send("drawingDone")} type="button">{t("garticDone")}</button></>}{state.phase==="guess"&&!host&&<><svg className="drawing-canvas" viewBox="0 0 600 360"><path d={myDrawing.reduce((v,p)=>`${v}${p.draw?" L":" M"}${p.x} ${p.y}`,"")} fill="none" stroke="currentColor" strokeWidth="7" strokeLinecap="round"/></svg><div className="bs-input-group"><input className="bs-input" value={guess} onChange={e=>setGuess(e.target.value)} placeholder={t("garticGuessPlace")}/><button className="demo-action demo-action--lime" onClick={()=>{send("guess",{text:guess});setGuess("")}} type="button">{t("garticGuess")}</button></div></>}{host&&["prompt","draw","guess"].includes(state.phase)&&<h3>{t("garticWaiting")}</h3>}{state.phase==="reveal"&&<div className="gartic-reveal"><p>#{state.revealIndex+1} {t("garticReveal")} · {state.players[state.revealIndex]?.slice(-5)}</p><p>{state.prompts[revealId]}</p><svg className="drawing-canvas" viewBox="0 0 600 360"><path d={revealPath} fill="none" stroke="currentColor" strokeWidth="7" strokeLinecap="round"/></svg><p>{state.guesses[revealId]}</p><div className="trivia-scores">{Object.entries(state.scores).sort(([,a],[,b])=>b-a).map(([id,score])=><p key={id}><span>{id.slice(-5)}</span><strong>{score}</strong></p>)}</div>{host&&<button className="demo-action demo-action--lime" onClick={()=>{const next=state.revealIndex+1;if(state.revealIndex>=state.players.length-1){set?.({...state,phase:"finished"});stage.complete();onSave(Math.max(0,...Object.values(state.scores)))}else set?.(p=>({...p,revealIndex:next}))}} type="button">{state.revealIndex>=state.players.length-1?t("garticFinish"):t("garticNext")}</button>}</div>}{sessionId&&<span className="multiplayer-badge">LIVE</span>}</div>}