"use client";
import { useEffect,useRef } from "react";
import { usePlayerName } from "@/app/components/PlayerNames";
import { useLocale } from "@/app/components/LocaleProvider";
import { useControllerGame } from "@/app/components/useControllerGame";
import { useStageGame } from "@/app/components/useStageGame";
type State={engine:string;game:"truth"|"never"|"pairs";phase:"choose"|"round"|"finished";round:number;prompt:string;mode:string;responses:Record<string,boolean>;pairs:string[][];viewerId?:string}; const empty=(game:State["game"]):State=>({engine:"server-v1",game,phase:game==="truth"?"choose":"round",round:0,prompt:"",mode:game==="never"?"never":game==="pairs"?"pair":"truth",responses:{},pairs:[]});
const COPY = {
  ru: { truth: "Правда или действие", never: "Я никогда не", pairs: "Случайные пары", pickTruth: "Правда", pickDare: "Действие", waiting: "Ведущий выбирает карточку", truthYes: "Сделано", truthNo: "Пропустить", neverYes: "Было", neverNo: "Не было", neverCount: "Было у", next: "Дальше", finish: "Завершить", answered: "Ответ принят" },
  en: { truth: "Truth or Dare", never: "Never Have I Ever", pairs: "Random Pairs", pickTruth: "Truth", pickDare: "Dare", waiting: "The host is picking a card", truthYes: "Done", truthNo: "Skip", neverYes: "I have", neverNo: "Never", neverCount: "Done it", next: "Next", finish: "Finish", answered: "Answer saved" },
} as const;
export default function SocialTool({sessionId,onSave,role,game}:{partyId:string;sessionId?:string|null;onSave:(score:number)=>void;role?:"stage"|"controller";game:State["game"]}){
  const playerName = usePlayerName();const host=role==="stage";const stage=useStageGame<State>(host?sessionId??null:null,()=>empty(game));const controller=useControllerGame<State>(!host?sessionId??null:null,empty(game));const state=host?stage.state:controller.state;const send=host?stage.sendAction:controller.sendAction;const complete=useRef(false);useEffect(()=>{if(!host||state.phase!=="finished"||complete.current)return;complete.current=true;stage.complete();onSave(state.round);},[host,onSave,stage,state.phase,state.round]);const {locale}=useLocale();const c=COPY[locale==="en"?"en":"ru"];const title=c[game];const answered=Boolean(state.responses[state.viewerId??""]);const yesCount=Object.values(state.responses).filter(Boolean).length;return <section className="party-game-board game-board-enter"><span className="game-step">{title} · {state.round+1}</span>{state.phase==="choose"&&host&&<div className="game-primary-actions"><button className="demo-action demo-action--lime" onClick={()=>send("choose",{mode:"truth"})} type="button">{c.pickTruth}</button><button className="demo-action demo-action--pink" onClick={()=>send("choose",{mode:"dare"})} type="button">{c.pickDare}</button></div>}{state.phase==="choose"&&!host&&<p className="tt-prompt">{c.waiting}</p>}{state.phase==="round"&&<><h3 className="game-prompt-swap">{state.prompt}</h3>{game==="pairs"&&<div className="pairs-grid">{state.pairs.map(pair=><article className="pair-card-pop" key={pair.join("-")}>{pair.map(id=><strong key={id}>{playerName(id)}</strong>)}</article>)}</div>}{game!=="pairs"&&<div className="game-primary-actions"><button className="demo-action demo-action--white" disabled={answered} onClick={()=>send("respond",{value:false})} type="button">{game==="never"?c.neverNo:c.truthNo}</button><button className="demo-action demo-action--lime" disabled={answered} onClick={()=>send("respond",{value:true})} type="button">{game==="never"?c.neverYes:c.truthYes}</button></div>}{game==="never"&&<p className="tt-prompt">{c.neverCount}: <b>{yesCount}</b></p>}{answered&&<p className="tt-prompt">{c.answered}</p>}{host&&<div className="game-primary-actions"><button className="demo-action demo-action--lime" onClick={()=>send("next")} type="button">{c.next}</button><button className="demo-action demo-action--white" onClick={()=>send("finish")} type="button">{c.finish}</button></div>}</>}{sessionId&&<span className="multiplayer-badge">LIVE</span>}</section>;}
