"use client";
import { useEffect, useRef, useState } from "react";
import { usePlayerName } from "@/app/components/PlayerNames";
import { useLocale } from "@/app/components/LocaleProvider";
import { useControllerGame } from "@/app/components/useControllerGame";
import { useStageGame } from "@/app/components/useStageGame";
type Color="red"|"yellow"|"green"|"blue";const COLOR_NAMES:Record<"ru"|"en",Record<Color,string>>={ru:{red:"красный",yellow:"жёлтый",green:"зелёный",blue:"синий"},en:{red:"red",yellow:"yellow",green:"green",blue:"blue"}};type Card={id:string;color:Color|null;kind:"number"|"skip"|"reverse"|"draw2"|"wild"|"wild4";value?:number};type State={phase:"playing"|"finished";players:string[];hands:Record<string,Card[]>;drawPile:Card[];discard:Card[];currentIndex:number;activeColor:Color;winner:string;uno:string[];viewerId?:string};const empty=():State=>({phase:"playing",players:[],hands:{},drawPile:[],discard:[],currentIndex:0,activeColor:"red",winner:"",uno:[]});const label=(card:Card)=>card.kind==="number"?String(card.value):card.kind==="draw2"?"+2":card.kind==="wild4"?"+4":card.kind==="wild"?"W":card.kind==="skip"?"⊘":"↻";
export default function UnoTracker({sessionId,onSave,role}:{partyId:string;sessionId?:string|null;onSave:(score:number)=>void;role?:"stage"|"controller"}){
  const { locale } = useLocale(); const ru = locale === "ru";
  const playerName = usePlayerName();const stageRole=role==="stage";const stage=useStageGame<State>(stageRole?sessionId??null:null,empty);const controller=useControllerGame<State>(!stageRole?sessionId??null:null,empty());const state=stageRole?stage.state:controller.state;const send=stageRole?stage.sendAction:controller.sendAction;const[color,setColor]=useState<Color>("red");const completed=useRef(false);const me=state.viewerId??"";const hand=state.hands[me]??[];const top=state.discard.at(-1);const myTurn=state.players[state.currentIndex]===me;useEffect(()=>{if(!stageRole||state.phase!=="finished"||completed.current)return;completed.current=true;stage.complete();onSave(1)},[onSave,stage,stageRole,state.phase]);return <section className="party-game-board game-board-enter uno-multiplayer"><span className="game-step">{ru ? "УНО" : "UNO"} · {state.currentIndex+1}/{state.players.length}</span>{top&&<div className="uno-table"><button className="uno-card uno-card--back" disabled={!myTurn} onClick={()=>send("draw")} type="button">+</button><div className={`uno-card uno-card--${top.color??"wild"}`}><strong>{label(top)}</strong><small>{COLOR_NAMES[ru ? "ru" : "en"][state.activeColor as Color] ?? state.activeColor}</small></div></div>}<p>{myTurn?(ru?"Твой ход":"Your turn"):(ru?"Ход игрока":"Turn")+": "+playerName(state.players[state.currentIndex])}</p><div className="uno-color-choice">{(["red","yellow","green","blue"] as Color[]).map(item=><button aria-label={COLOR_NAMES[ru ? "ru" : "en"][item]} className={color===item?"active":""} key={item} onClick={()=>setColor(item)} style={{background:item}} type="button"/>)}</div><div className="uno-hand">{hand.map(card=><button className={`uno-card uno-card--${card.color??"wild"}`} disabled={!myTurn} key={card.id} onClick={()=>send("play",{cardId:card.id,color})} type="button"><strong>{label(card)}</strong></button>)}</div>{state.phase==="finished"&&<h3>{state.winner===me?(ru?"Ты выиграл!":"You won!"):(ru?"Победитель: ":"Winner: ")+playerName(state.winner)}</h3>}{sessionId&&<span className="multiplayer-badge">LIVE</span>}</section>}
