"use client";

import { FormEvent, useEffect, useState } from "react";
import { useLocale } from "./components/LocaleProvider";

type WaitlistStats = { capacity: number; baseline: number; applications: number; total: number; remaining: number; registeredUsers: number };
const initialStats: WaitlistStats = { capacity: 765, baseline: 254, applications: 0, registeredUsers: 0, total: 254, remaining: 511 };
function Icon({ name, className }: { name: string; className?: string }) { return <span className={`material-symbols-rounded${className ? ` ${className}` : ""}`} aria-hidden="true">{name}</span>; }

export default function WaitlistForm() {
  const [stats, setStats] = useState(initialStats); const [submitted, setSubmitted] = useState(false); const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const { t } = useLocale();
  useEffect(() => { fetch("/api/waitlist", { cache: "no-store" }).then((response) => response.ok ? response.json() : null).then((data) => { if (data) setStats(data); }).catch(() => undefined); }, []);
  async function handleSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; if (!form.reportValidity() || loading) return; setLoading(true); setError(""); setSubmitted(false); const data = new FormData(form); try { const response = await fetch("/api/waitlist", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ name: data.get("name"), city: data.get("city"), contact: data.get("contact"), beta: data.get("beta") === "on", company: data.get("company") }) }); const result = await response.json(); if (!response.ok) { if (result.stats) setStats(result.stats); setError(result.error ?? t("waitlistError")); return; } setStats(result.stats); setSubmitted(true); form.reset(); } catch { setError(t("waitlistOffline")); } finally { setLoading(false); } }
  const progress = `${Math.min(100, (stats.total / stats.capacity) * 100)}%`;
  return <div className="waitlist-grid"><div className="form-card"><div className="form-head"><div><p>WAITLIST · 2026</p><h3>{t("waitlistTitleForm")}</h3></div><span className="badge badge-lime">{t("waitlistKicker")}</span></div><form onSubmit={handleSubmit} noValidate><input className="waitlist-honeypot" name="company" tabIndex={-1} autoComplete="off" aria-hidden="true" /><div className="field-grid"><label><span>{t("waitlistName")}</span><input name="name" type="text" placeholder={t("waitlistNamePlace")} maxLength={100} required /></label><label><span>{t("waitlistCity")}</span><input name="city" type="text" placeholder={t("waitlistCityPlace")} maxLength={100} required /></label></div><label><span>Email / WhatsApp</span><input name="contact" type="text" placeholder={t("waitlistContactPlace")} maxLength={160} required /></label><label className="checkbox-label"><input name="beta" type="checkbox" /><span><Icon name="check" /> {t("waitlistBeta")}</span></label><button className="button button-primary submit-button" type="submit" disabled={loading || stats.remaining === 0}>{loading ? t("waitlistSave") : stats.remaining === 0 ? t("waitlistFull") : <>{t("waitlistJoin")} <Icon name="arrow_forward" /></>}</button></form>{submitted && <div className="form-success" role="status" aria-live="polite"><Icon name="check" className="success-icon" /><div><strong>{t("waitlistSuccessTitle")}</strong><span>{t("waitlistSuccessText")}</span></div></div>}{error && <p className="form-error" role="alert">{error}</p>}</div><aside className="wave-card" aria-label={t("waitlistTitleRight")}><span className="badge badge-pink">{t("waitlistLive")}</span><p>{t("waitlistTitleRight")}</p><h3>{stats.total}<span>/{stats.capacity}</span></h3><div className="progress" aria-label={`${stats.total}/${stats.capacity}`}><span style={{ width: progress }} /></div><ul><li><Icon name="check" /> {t("waitlistFirst")}: {stats.baseline + stats.applications}</li><li><Icon name="check" /> {t("waitlistRegistered")}: {stats.registeredUsers}</li><li><Icon name="check" /> {t("waitlistRemaining")}: {stats.remaining}</li></ul></aside></div>;
}
